use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

use crate::term::{BOLD, DIM, GREEN, RED, RESET, YELLOW};

const SCHEMA: &str = include_str!("../../schema/project.cue");
const SLOTS: &[&str] = &["apps", "infra", "nix", "packages", "services", "tools"];

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka project generate-justfiles` to update; CI fails on drift.\n\n";

const RUST_TEMPLATE: &str = r#"build:
    cargo build --release

test:
    cargo test

fmt:
    cargo fmt

fmt-check:
    cargo fmt --check

lint:
    cargo clippy --all-targets -- -D warnings

doc-check:
    RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --document-private-items

deny:
    cargo deny check

# Macro-only deps can register as false positives — allowlist via
# `package.metadata.cargo-machete.ignored` in the offending Cargo.toml.
machete:
    cargo machete

coverage:
    #!/usr/bin/env bash
    set -euo pipefail
    thresholds=$(cue export ../../tools/shaka/schema/project.cue project.cue)
    fail_line=$(jq <<<"$thresholds" '.coverage.line.fail')
    fail_branch=$(jq <<<"$thresholds" '.coverage.branch.fail')
    measured=$(cargo llvm-cov --json --summary-only --branch)
    line=$(jq <<<"$measured" '.data[0].totals.lines.percent')
    branch=$(jq <<<"$measured" '.data[0].totals.branches.percent')
    printf 'coverage: line=%.1f%% branch=%.1f%% (gates: line>=%s%% branch>=%s%%)\n' \
        "$line" "$branch" "$fail_line" "$fail_branch"
    awk -v l="$line" -v b="$branch" -v fl="$fail_line" -v fb="$fail_branch" \
        'BEGIN { exit (l < fl || b < fb) ? 1 : 0 }'

nix-fmt-check:
    nix fmt -- --check $(find . -type f -name '*.nix' -not -path './.*')

flake-check:
    nix flake check

whitespace-check:
    ../../tools/shaka/bin/shaka whitespace check

validate: fmt-check lint doc-check deny machete test coverage nix-fmt-check flake-check whitespace-check
"#;

const NIX_LIB_TEMPLATE: &str = r#"nix-fmt-check:
    nix fmt -- --check $(find . -type f -name '*.nix' -not -path './.*')

flake-check:
    nix flake check

whitespace-check:
    ../../tools/shaka/bin/shaka whitespace check

validate: nix-fmt-check flake-check whitespace-check
"#;

// Infra projects intentionally do NOT run `nix flake check` in `validate`.
// The devbox eval-check forces `system.build.toplevel.drvPath` evaluation,
// which pulls a NixOS closure larger than a stock GitHub runner's disk
// (see #170). The `Build Linode image` CI job runs `nix build` on the
// same outputs whenever infra files change, which is a strict superset of
// the eval check; local equivalence is `nix build` on the relevant flake
// output rather than `just validate`.
const INFRA_TEMPLATE_WITH_TF: &str = r#"tofu-validate:
    cd terraform && tofu init -backend=false -input=false && tofu validate

nix-fmt-check:
    nix fmt -- --check $(find . -type f -name '*.nix' -not -path './.*')

whitespace-check:
    ../../tools/shaka/bin/shaka whitespace check

validate: tofu-validate nix-fmt-check whitespace-check

plan:
    cd terraform && tofu init -input=false && tofu plan

apply:
    cd terraform && tofu apply
"#;

// Infra projects without a `terraform/` directory (nix-only infra such
// as `infra/home`). The tofu recipes are omitted because they would
// fail on a missing directory; carrying an empty `terraform/` placeholder
// would be worse than this branch.
const INFRA_TEMPLATE_NO_TF: &str = r#"nix-fmt-check:
    nix fmt -- --check $(find . -type f -name '*.nix' -not -path './.*')

whitespace-check:
    ../../tools/shaka/bin/shaka whitespace check

validate: nix-fmt-check whitespace-check
"#;

#[derive(Deserialize)]
struct ProjectMeta {
    #[allow(dead_code)]
    name: String,
    kind: String,
}

pub fn run(check: bool) {
    let schema_path = match write_schema() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("{RED}{BOLD}error:{RESET} could not write schema: {e}");
            std::process::exit(1);
        }
    };

    let mut items: Vec<(PathBuf, String)> = Vec::new();

    let projects = discover_projects(Path::new("."));
    for project in &projects {
        match read_meta(&schema_path, project) {
            Ok(meta) => match template_for(&meta.kind, project) {
                Some(body) => items.push((project.join("justfile"), render(body))),
                None => {
                    eprintln!(
                        "{RED}{BOLD}error:{RESET} {} has unknown kind {:?}",
                        project.display(),
                        meta.kind
                    );
                    std::process::exit(1);
                }
            },
            Err(e) => {
                eprintln!(
                    "{RED}{BOLD}error:{RESET} could not read {}: {e}",
                    project.display()
                );
                std::process::exit(1);
            }
        }
    }

    if check {
        check_drift(&items);
    } else {
        write_all(&items);
    }
}

fn template_for(kind: &str, project_dir: &Path) -> Option<&'static str> {
    match kind {
        "rust" => Some(RUST_TEMPLATE),
        "infra" => Some(if project_dir.join("terraform").is_dir() {
            INFRA_TEMPLATE_WITH_TF
        } else {
            INFRA_TEMPLATE_NO_TF
        }),
        "nix-lib" => Some(NIX_LIB_TEMPLATE),
        _ => None,
    }
}

fn render(body: &str) -> String {
    format!("{HEADER}{body}")
}

fn write_all(items: &[(PathBuf, String)]) {
    for (path, content) in items {
        if let Err(e) = std::fs::write(path, content) {
            eprintln!("{RED}{BOLD}error:{RESET} writing {}: {e}", path.display());
            std::process::exit(1);
        }
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-justfiles:{RESET} wrote {} files",
        items.len()
    );
}

fn check_drift(items: &[(PathBuf, String)]) {
    let mut drift = Vec::new();
    for (path, expected) in items {
        match std::fs::read_to_string(path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(path.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(path.clone());
            }
        }
    }
    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-justfiles --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka project generate-justfiles` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        std::process::exit(1);
    }
    println!("{GREEN}{BOLD}generate-justfiles --check passed{RESET}");
}

fn discover_projects(root: &Path) -> Vec<PathBuf> {
    let mut projects = Vec::new();
    for slot in SLOTS {
        let slot_dir = root.join(slot);
        let entries = match std::fs::read_dir(&slot_dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                projects.push(path);
            }
        }
    }
    projects.sort();
    projects
}

fn read_meta(schema_path: &Path, project_dir: &Path) -> Result<ProjectMeta, String> {
    let project_file = project_dir.join("project.cue");
    if !project_file.exists() {
        return Err("missing project.cue".into());
    }

    let output = Command::new("cue")
        .arg("export")
        .arg(schema_path)
        .arg(&project_file)
        .output()
        .map_err(|e| format!("failed to spawn cue: {e}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!("cue export failed: {stderr}"));
    }

    serde_json::from_slice::<ProjectMeta>(&output.stdout)
        .map_err(|e| format!("could not parse cue export output: {e}"))
}

fn write_schema() -> std::io::Result<PathBuf> {
    // Per-process filename — see schema_check::write_schema for the
    // rationale (parallel test invocations race on a shared path).
    let path =
        std::env::temp_dir().join(format!("shaka-generate-schema-{}.cue", std::process::id()));
    let mut f = std::fs::File::create(&path)?;
    f.write_all(SCHEMA.as_bytes())?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_project(name: &str) -> tempfile::TempDir {
        tempfile::Builder::new()
            .prefix(&format!("shaka-tpl-{name}-"))
            .tempdir()
            .expect("tempdir")
    }

    #[test]
    fn template_for_rust_returns_rust_template() {
        let dir = tmp_project("rust");
        assert_eq!(template_for("rust", dir.path()), Some(RUST_TEMPLATE));
    }

    #[test]
    fn template_for_infra_with_terraform_dir_returns_with_tf_template() {
        let dir = tmp_project("infra-tf");
        std::fs::create_dir(dir.path().join("terraform")).unwrap();
        assert_eq!(
            template_for("infra", dir.path()),
            Some(INFRA_TEMPLATE_WITH_TF)
        );
    }

    #[test]
    fn template_for_infra_without_terraform_dir_returns_no_tf_template() {
        let dir = tmp_project("infra-notf");
        assert_eq!(
            template_for("infra", dir.path()),
            Some(INFRA_TEMPLATE_NO_TF)
        );
    }

    #[test]
    fn template_for_nix_lib_returns_nix_lib_template() {
        let dir = tmp_project("nix-lib");
        assert_eq!(template_for("nix-lib", dir.path()), Some(NIX_LIB_TEMPLATE));
    }

    #[test]
    fn template_for_unknown_kind_returns_none() {
        let dir = tmp_project("unknown");
        assert!(template_for("python", dir.path()).is_none());
        assert!(template_for("", dir.path()).is_none());
    }

    #[test]
    fn nix_lib_template_runs_flake_check() {
        assert!(NIX_LIB_TEMPLATE.contains("flake-check:"));
        assert!(NIX_LIB_TEMPLATE.contains("nix flake check"));
        assert!(NIX_LIB_TEMPLATE.contains("validate: nix-fmt-check flake-check whitespace-check"));
    }

    #[test]
    fn all_templates_run_whitespace_check() {
        for tpl in [
            RUST_TEMPLATE,
            NIX_LIB_TEMPLATE,
            INFRA_TEMPLATE_WITH_TF,
            INFRA_TEMPLATE_NO_TF,
        ] {
            assert!(tpl.contains("whitespace-check:"));
            assert!(tpl.contains("../../tools/shaka/bin/shaka whitespace check"));
            assert!(
                tpl.contains("whitespace-check\n"),
                "validate chain must include whitespace-check"
            );
        }
    }

    #[test]
    fn all_templates_run_nix_fmt_check() {
        for tpl in [
            RUST_TEMPLATE,
            NIX_LIB_TEMPLATE,
            INFRA_TEMPLATE_WITH_TF,
            INFRA_TEMPLATE_NO_TF,
        ] {
            assert!(tpl.contains("nix-fmt-check:"));
            assert!(tpl.contains("nix fmt -- --check"));
            assert!(tpl.contains("nix-fmt-check"));
        }
    }

    #[test]
    fn infra_templates_omit_flake_check() {
        // See #170: infra `nix flake check` pulls a NixOS closure that
        // exceeds GitHub runner disk; `Build Linode image` covers the
        // eval check via full `nix build`.
        for tpl in [INFRA_TEMPLATE_WITH_TF, INFRA_TEMPLATE_NO_TF] {
            assert!(!tpl.contains("flake-check"));
            assert!(!tpl.contains("nix flake check"));
        }
    }

    #[test]
    fn render_prepends_header() {
        let out = render("foo:\n    echo bar\n");
        assert!(out.starts_with("# Generated by shaka."));
        assert!(out.ends_with("foo:\n    echo bar\n"));
    }

    #[test]
    fn rust_template_includes_quality_recipes() {
        assert!(RUST_TEMPLATE.contains("fmt-check"));
        assert!(RUST_TEMPLATE.contains("clippy"));
        assert!(RUST_TEMPLATE.contains(
            "validate: fmt-check lint doc-check deny machete test coverage nix-fmt-check flake-check whitespace-check"
        ));
    }

    #[test]
    fn rust_template_includes_doc_check_recipe() {
        assert!(RUST_TEMPLATE.contains("doc-check:"));
        assert!(RUST_TEMPLATE.contains(r#"RUSTDOCFLAGS="-D warnings""#));
        assert!(RUST_TEMPLATE.contains("cargo doc --no-deps --document-private-items"));
    }

    #[test]
    fn rust_template_includes_deny_recipe() {
        assert!(RUST_TEMPLATE.contains("deny:"));
        assert!(RUST_TEMPLATE.contains("cargo deny check"));
    }

    #[test]
    fn rust_template_includes_machete_recipe() {
        assert!(RUST_TEMPLATE.contains("machete:"));
        assert!(RUST_TEMPLATE.contains("cargo machete"));
        assert!(RUST_TEMPLATE.contains("package.metadata.cargo-machete.ignored"));
    }

    #[test]
    fn rust_template_includes_coverage_recipe() {
        assert!(RUST_TEMPLATE.contains("coverage:"));
        assert!(RUST_TEMPLATE.contains("cargo llvm-cov"));
        assert!(RUST_TEMPLATE.contains("cue export ../../tools/shaka/schema/project.cue"));
        assert!(RUST_TEMPLATE.contains(".coverage.line.fail"));
        assert!(RUST_TEMPLATE.contains(".coverage.branch.fail"));
    }

    #[test]
    fn rust_template_includes_flake_check() {
        assert!(RUST_TEMPLATE.contains("flake-check:"));
        assert!(RUST_TEMPLATE.contains("nix flake check"));
    }

    #[test]
    fn infra_with_tf_template_uses_tofu() {
        assert!(INFRA_TEMPLATE_WITH_TF.contains("tofu validate"));
        assert!(INFRA_TEMPLATE_WITH_TF.contains("tofu plan"));
        assert!(INFRA_TEMPLATE_WITH_TF.contains("tofu apply"));
        assert!(!INFRA_TEMPLATE_WITH_TF.contains("terraform validate"));
        assert!(!INFRA_TEMPLATE_WITH_TF.contains("terraform plan"));
    }

    #[test]
    fn infra_with_tf_template_validate_chain() {
        assert!(INFRA_TEMPLATE_WITH_TF
            .contains("validate: tofu-validate nix-fmt-check whitespace-check\n"));
    }

    #[test]
    fn infra_no_tf_template_omits_tofu() {
        assert!(!INFRA_TEMPLATE_NO_TF.contains("tofu"));
        assert!(!INFRA_TEMPLATE_NO_TF.contains("terraform"));
    }

    #[test]
    fn infra_no_tf_template_validate_chain() {
        assert!(INFRA_TEMPLATE_NO_TF.contains("validate: nix-fmt-check whitespace-check\n"));
    }
}
