use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

use crate::term::{BOLD, DIM, GREEN, RED, RESET, YELLOW};

const SCHEMA: &str = include_str!("../../schema/project-schema.cue");

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka project generate-flakes` to update; CI fails on drift.\n";

#[derive(Deserialize)]
struct ProjectMeta {
    name: String,
    kind: String,
    #[serde(default)]
    cli: Option<CliMeta>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CliMeta {
    binary_name: String,
    #[serde(default)]
    description: Option<String>,
    package: bool,
    #[serde(default)]
    runtime_path_deps: Vec<String>,
    #[serde(default)]
    check_inputs: Vec<String>,
    shell_completions: bool,
    #[serde(default)]
    extra_dev_shell_packages: Vec<String>,
}

pub fn run(check: bool) {
    let schema_path = match write_schema() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("{RED}{BOLD}error:{RESET} could not write schema: {e}");
            std::process::exit(1);
        }
    };

    let projects = crate::project::schema_check::discover(Path::new("."));
    let mut items: Vec<(PathBuf, String)> = Vec::new();
    for project in &projects {
        let meta = match read_meta(&schema_path, project) {
            Ok(m) => m,
            Err(e) => {
                eprintln!(
                    "{RED}{BOLD}error:{RESET} could not read {}: {e}",
                    project.display()
                );
                std::process::exit(1);
            }
        };
        if meta.kind != "rust-cli" {
            // Other kinds keep their hand-authored flake.nix until the
            // generator grows a template for them (#611 covers
            // `rust-cli` only; rust-worker, infra, nix-lib, document
            // follow in separate issues).
            continue;
        }
        let cli = meta.cli.as_ref().unwrap_or_else(|| {
            eprintln!(
                "{RED}{BOLD}error:{RESET} {} is kind rust-cli but has no `cli:` block",
                project.display()
            );
            std::process::exit(1);
        });
        items.push((project.join("flake.nix"), render_flake(&meta.name, cli)));
    }

    if check {
        check_drift(&items);
    } else {
        write_all(&items);
    }
}

/// Compose the flake.nix body. `name` is the project name (used as
/// fallback `description`); `cli` carries the shape knobs read from
/// `project.cue`.
fn render_flake(name: &str, cli: &CliMeta) -> String {
    let description = cli.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(2048);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(INPUTS);
    out.push_str("\n  outputs =\n");
    out.push_str(OUTPUT_HEADER);
    out.push_str("    in\n    {\n");
    if cli.package {
        out.push_str(&render_packages(cli));
        out.push_str(&render_apps(cli));
    }
    out.push_str(&render_devshell(cli));
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

const INPUTS: &str = r#"  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
"#;

const OUTPUT_HEADER: &str = r#"    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.nightly.latest.default.override {
          extensions = [
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
        };
"#;

fn render_packages(cli: &CliMeta) -> String {
    let bin = &cli.binary_name;
    let mut out = String::new();
    out.push_str("      packages = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.rustPlatform.buildRustPackage {\n");
    out.push_str(&format!("            pname = \"{bin}\";\n"));
    out.push_str("            version = \"0.1.0\";\n");
    out.push_str("            src = ./.;\n");
    out.push_str("            cargoLock.lockFile = ./Cargo.lock;\n");

    if !cli.check_inputs.is_empty() {
        out.push_str(&render_pkg_list("nativeCheckInputs", &cli.check_inputs, 12));
    }

    let mut native_build_inputs: Vec<String> = Vec::new();
    if !cli.runtime_path_deps.is_empty() {
        native_build_inputs.push("makeWrapper".to_string());
    }
    if cli.shell_completions {
        native_build_inputs.push("installShellFiles".to_string());
    }
    if !native_build_inputs.is_empty() {
        out.push_str(&render_pkg_list(
            "nativeBuildInputs",
            &native_build_inputs,
            12,
        ));
    }

    if cli.shell_completions {
        out.push_str(&format!(
            "            postInstall = ''\n              installShellCompletion --cmd {bin} \\\n                --bash <($out/bin/{bin} completions bash) \\\n                --fish <($out/bin/{bin} completions fish) \\\n                --zsh  <($out/bin/{bin} completions zsh)\n            '';\n"
        ));
    }

    if !cli.runtime_path_deps.is_empty() {
        out.push_str(&format!(
            "            postFixup = ''\n              wrapProgram $out/bin/{bin} \\\n                --prefix PATH : ${{\n                  pkgs.lib.makeBinPath [\n"
        ));
        for dep in &cli.runtime_path_deps {
            out.push_str(&format!("                    pkgs.{dep}\n"));
        }
        out.push_str("                  ]\n                }\n            '';\n");
    }

    out.push_str("          };\n        }\n      );\n\n");
    out
}

/// `apps.default` is emitted whenever `packages.default` is emitted —
/// it's a one-liner that makes `nix run ./<project>` work, with no
/// downside. The current `tools/claude-hooks` flake omits `apps`; the
/// generator gains it (semantic equivalence covers cosmetic additions
/// that don't change consumer behavior, per #611).
fn render_apps(cli: &CliMeta) -> String {
    let bin = &cli.binary_name;
    format!(
        "      apps = forEachSupportedSystem (\n        {{ system, ... }}:\n        {{\n          default = {{\n            type = \"app\";\n            program = \"${{self.packages.${{system}}.default}}/bin/{bin}\";\n          }};\n        }}\n      );\n\n"
    )
}

fn render_devshell(cli: &CliMeta) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    out.push_str("            packages = [\n");
    out.push_str("              (rustToolchain pkgs)\n");
    for pkg in &cli.extra_dev_shell_packages {
        out.push_str(&format!("              pkgs.{pkg}\n"));
    }
    out.push_str("            ]\n");
    out.push_str("            ++ (workflowPackages pkgs)\n");
    out.push_str(
        "            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;\n",
    );
    out.push_str("          };\n        }\n      );\n");
    out
}

/// Renders a nixpkgs-attr list as `attr = [ pkgs.A pkgs.B ];` or, when
/// it has a single entry, as a single-line `[ pkgs.X ]`. `indent` is
/// the column at which the attribute line starts (used to indent the
/// closing bracket).
fn render_pkg_list(attr: &str, items: &[String], indent: usize) -> String {
    let pad = " ".repeat(indent);
    if items.len() == 1 {
        return format!("{pad}{attr} = [ pkgs.{} ];\n", items[0]);
    }
    let mut out = format!("{pad}{attr} = [\n");
    for item in items {
        out.push_str(&format!("{pad}  pkgs.{item}\n"));
    }
    out.push_str(&format!("{pad}];\n"));
    out
}

fn read_meta(schema_path: &Path, project_dir: &Path) -> Result<ProjectMeta, String> {
    let project_file = project_dir.join("project.cue");
    if !project_file.exists() {
        return Err("missing project.cue".into());
    }

    let output = Command::new("cue")
        .arg("export")
        .arg(schema_path)
        .arg(&project_file)
        .output()
        .map_err(|e| format!("failed to spawn cue: {e}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!("cue export failed: {stderr}"));
    }

    serde_json::from_slice::<ProjectMeta>(&output.stdout)
        .map_err(|e| format!("could not parse cue export output: {e}"))
}

fn write_schema() -> std::io::Result<PathBuf> {
    let path = std::env::temp_dir().join(format!(
        "shaka-generate-flakes-schema-{}.cue",
        std::process::id()
    ));
    let mut f = std::fs::File::create(&path)?;
    f.write_all(SCHEMA.as_bytes())?;
    Ok(path)
}

fn write_all(items: &[(PathBuf, String)]) {
    for (path, content) in items {
        if let Err(e) = std::fs::write(path, content) {
            eprintln!("{RED}{BOLD}error:{RESET} writing {}: {e}", path.display());
            std::process::exit(1);
        }
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-flakes:{RESET} wrote {} files",
        items.len()
    );
}

fn check_drift(items: &[(PathBuf, String)]) {
    let mut drift = Vec::new();
    for (path, expected) in items {
        match std::fs::read_to_string(path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(path.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(path.clone());
            }
        }
    }
    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-flakes --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka project generate-flakes` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        std::process::exit(1);
    }
    println!("{GREEN}{BOLD}generate-flakes --check passed{RESET}");
}

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal_cli() -> CliMeta {
        CliMeta {
            binary_name: "demo".into(),
            description: None,
            package: true,
            runtime_path_deps: vec![],
            check_inputs: vec![],
            shell_completions: false,
            extra_dev_shell_packages: vec![],
        }
    }

    #[test]
    fn rendered_flake_starts_with_generated_header() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn description_defaults_to_project_name() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.contains(r#"description = "demo""#));
    }

    #[test]
    fn description_override_takes_precedence() {
        let cli = CliMeta {
            description: Some("the demo cli".into()),
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains(r#"description = "the demo cli""#));
    }

    #[test]
    fn package_block_omitted_when_package_false() {
        let cli = CliMeta {
            package: false,
            ..minimal_cli()
        };
        let out = render_flake("todoist", &cli);
        // `packages = forEachSupportedSystem` is the top-level
        // packages attribute; `packages = [` also appears inside
        // mkShell, so match on the wider form.
        assert!(!out.contains("packages = forEachSupportedSystem"));
        assert!(!out.contains("apps = forEachSupportedSystem"));
        assert!(out.contains("devShells = forEachSupportedSystem"));
    }

    #[test]
    fn package_implies_apps() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.contains("packages = forEachSupportedSystem"));
        assert!(out.contains("apps = forEachSupportedSystem"));
    }

    #[test]
    fn shell_completions_pulls_in_install_shell_files() {
        let cli = CliMeta {
            shell_completions: true,
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("installShellFiles"));
        assert!(out.contains("installShellCompletion --cmd demo"));
    }

    #[test]
    fn runtime_path_deps_pull_in_make_wrapper_and_post_fixup() {
        let cli = CliMeta {
            runtime_path_deps: vec!["jujutsu".into(), "git".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("makeWrapper"));
        assert!(out.contains("wrapProgram $out/bin/demo"));
        assert!(out.contains("pkgs.jujutsu"));
        assert!(out.contains("pkgs.git"));
    }

    #[test]
    fn check_inputs_render_as_native_check_inputs() {
        let cli = CliMeta {
            check_inputs: vec!["jujutsu".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("nativeCheckInputs = [ pkgs.jujutsu ];"));
    }

    #[test]
    fn extra_dev_shell_packages_render_into_dev_shell_list() {
        let cli = CliMeta {
            extra_dev_shell_packages: vec!["actionlint".into(), "taplo".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("pkgs.actionlint"));
        assert!(out.contains("pkgs.taplo"));
    }
}
