use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::project::schema_check;
use crate::term::{BOLD, DIM, GREEN, RED, RESET, YELLOW};

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka project generate-flakes` to update; CI fails on drift.\n";

/// Install root for a CLI's bundled CUE module closure (see
/// `cli.cueModule`). `wrapProgram` sets `SHAKA_CUE_MODULE_DIR` to this.
const CUE_BUNDLE_DIR: &str = "$out/share/shaka/cue";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProjectMeta {
    name: String,
    kind: String,
    #[serde(default)]
    cli: Option<CliMeta>,
    #[serde(default)]
    document: Option<DocumentMeta>,
    #[serde(default)]
    infra: Option<InfraMeta>,
    #[serde(default)]
    nix_lib: Option<NixLibMeta>,
    #[serde(default)]
    rust_lib: Option<RustLibMeta>,
    #[serde(default)]
    wasm_app: Option<WasmAppMeta>,
    #[serde(default)]
    worker: Option<WorkerMeta>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CliMeta {
    binary_name: String,
    #[serde(default)]
    description: Option<String>,
    package: bool,
    #[serde(default)]
    runtime_path_deps: Vec<String>,
    #[serde(default)]
    check_inputs: Vec<String>,
    shell_completions: bool,
    #[serde(default)]
    extra_dev_shell_packages: Vec<String>,
    #[serde(default)]
    cue_module: Option<CueModule>,
}

/// `cli.cueModule`: directories copied from the flake src into the
/// packaged CUE closure under `$out/share/shaka/cue`, so schema-
/// dependent subcommands resolve from a nix-built binary run outside
/// the monorepo (see `schema_check::cue_module_root`).
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CueModule {
    include: Vec<CueInclude>,
}

#[derive(Deserialize)]
struct CueInclude {
    /// Source directory relative to the flake src (the project dir).
    from: String,
    /// Destination relative to the bundle module root (`.` = root).
    to: String,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct DocumentMeta {
    #[serde(default)]
    description: Option<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct InfraMeta {
    #[serde(default)]
    description: Option<String>,
    /// Map of extra flake input name → spec. Sorted lexicographically
    /// at emit time so the generator's output is stable regardless of
    /// CUE iteration order.
    #[serde(default)]
    extra_inputs: BTreeMap<String, ExtraInput>,
    #[serde(default)]
    dev_shell_packages: Vec<String>,
    /// Raw nix snippet inserted inside the standard `let ..` block,
    /// before `in { ... }`. Used by projects whose extra outputs share
    /// computed values (devbox's `devboxConfig` / `imageConfig`).
    #[serde(default)]
    let_extra: Option<String>,
    /// Raw nix snippet inserted inside `outputs.{...}: let .. in { HERE }`,
    /// after the standard `devShells` block but before `formatter`. See
    /// `feedback_no_exceptions.md` — this is the escape sandbox for
    /// projects whose flake shape doesn't fit the default infra
    /// template (devbox, home), keeping them inside the generator's
    /// drift-checked envelope instead of carving exceptions.
    #[serde(default)]
    extra: Option<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NixLibMeta {
    #[serde(default)]
    description: Option<String>,
    /// Same escape sandbox principle as `infra.extra`, but for nix-lib
    /// it carries the *entire* `let .. in { ... }` body of `outputs`.
    /// Reason: nix-lib defines what other flakes import, so the lib's
    /// shape isn't a fixed template — the let-bindings, the `lib =
    /// { inherit ... }` export, formatter, devShells are all
    /// project-specific. The template provides only the flake header,
    /// description, nixpkgs input, and outputs signature.
    #[serde(default)]
    extra: Option<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RustLibMeta {
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    extra_dev_shell_packages: Vec<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct WasmAppMeta {
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    extra_dev_shell_packages: Vec<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct WorkerMeta {
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    extra_dev_shell_packages: Vec<String>,
    /// External consumers (no kolohelios checkout) need a real `shaka`
    /// on PATH ahead of the `workflowPackages` shim, which can't resolve
    /// `tools/shaka/bin/shaka` outside the monorepo. When set, the flake
    /// gains the `shaka` FlakeHub input and a PATH-prepend in the
    /// `shellHook`. Default-false: in-repo workers let the shim find the
    /// monorepo binary.
    #[serde(default)]
    consumes_shaka: bool,
}

#[derive(Default, Deserialize)]
struct ExtraInput {
    url: String,
    #[serde(default)]
    follows: BTreeMap<String, String>,
}

pub fn run(check: bool) {
    if let Err(e) = schema_check::project_schema_path() {
        eprintln!("{RED}{BOLD}error:{RESET} could not resolve project schema: {e}");
        std::process::exit(1);
    }

    let projects = schema_check::discover(Path::new("."));
    let mut items: Vec<(PathBuf, String)> = Vec::new();
    for project in &projects {
        let meta = match read_meta(project) {
            Ok(m) => m,
            Err(e) => {
                eprintln!(
                    "{RED}{BOLD}error:{RESET} could not read {}: {e}",
                    project.display()
                );
                std::process::exit(1);
            }
        };
        match meta.kind.as_str() {
            "rust-cli" => {
                let cli = meta.cli.as_ref().unwrap_or_else(|| {
                    eprintln!(
                        "{RED}{BOLD}error:{RESET} {} is kind rust-cli but has no `cli:` block",
                        project.display()
                    );
                    std::process::exit(1);
                });
                items.push((project.join("flake.nix"), render_flake(&meta.name, cli)));
            }
            "document" => {
                // `document:` is optional in the schema — fall back to a
                // default-initialized block so a project that doesn't
                // override description still picks up the project name.
                let default = DocumentMeta::default();
                let doc = meta.document.as_ref().unwrap_or(&default);
                items.push((
                    project.join("flake.nix"),
                    render_document_flake(&meta.name, doc),
                ));
            }
            "infra" => {
                // Opt-in: only generate when the project.cue declares
                // an `infra:` block. Projects without one keep their
                // hand-authored flake until they're migrated. This is
                // the migration ramp — once every kind:infra project
                // carries `infra:`, the block can become required.
                let Some(infra) = meta.infra.as_ref() else {
                    continue;
                };
                items.push((
                    project.join("flake.nix"),
                    render_infra_flake(&meta.name, infra),
                ));
            }
            "rust-lib" => {
                // `rustLib:` is optional — fall back to a default block
                // so a lib that doesn't override description or devShell
                // packages still picks up the project name.
                let default = RustLibMeta::default();
                let rl = meta.rust_lib.as_ref().unwrap_or(&default);
                items.push((
                    project.join("flake.nix"),
                    render_rust_lib_flake(&meta.name, rl),
                ));
            }
            "wasm-app" => {
                // `wasmApp:` is optional — fall back to a default block so
                // an app that doesn't override description or devShell
                // packages still picks up the project name.
                let default = WasmAppMeta::default();
                let wa = meta.wasm_app.as_ref().unwrap_or(&default);
                items.push((
                    project.join("flake.nix"),
                    render_wasm_app_flake(&meta.name, wa),
                ));
            }
            "nix-lib" => {
                // Same opt-in pattern as `infra`.
                let Some(nl) = meta.nix_lib.as_ref() else {
                    continue;
                };
                items.push((
                    project.join("flake.nix"),
                    render_nix_lib_flake(&meta.name, nl),
                ));
            }
            "rust-worker" => {
                let worker = meta.worker.as_ref().unwrap_or_else(|| {
                    eprintln!(
                        "{RED}{BOLD}error:{RESET} {} is kind rust-worker but has no `worker:` block",
                        project.display()
                    );
                    std::process::exit(1);
                });
                items.push((
                    project.join("flake.nix"),
                    render_worker_flake(&meta.name, worker),
                ));
            }
            // Other kinds keep their hand-authored flake.nix until the
            // generator grows a template for them.
            _ => continue,
        }
    }

    if check {
        check_drift(&items);
    } else {
        write_all(&items);
    }
}

/// Compose the flake.nix body. `name` is the project name (used as
/// fallback `description`); `cli` carries the shape knobs read from
/// `project.cue`.
fn render_flake(name: &str, cli: &CliMeta) -> String {
    let description = cli.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(2048);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(INPUTS);
    out.push_str("\n  outputs =\n");
    out.push_str(OUTPUT_HEADER);
    out.push_str("    in\n    {\n");
    if cli.package {
        out.push_str(&render_packages(cli));
        out.push_str(&render_apps(cli));
    }
    out.push_str(&render_devshell(cli));
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

/// Compose a rust-lib flake: a shared library crate consumed natively
/// (for tests) and on wasm32-unknown-unknown (the Worker + the WASM
/// editor). devShell-only — a lib produces no binary, so there's no
/// `packages.default` / `apps.default`; the toolchain carries the wasm
/// target so the generated `wasm-check` recipe finds the stdlib. Same
/// kolohelios-nix + nixpkgs + rust-overlay inputs as the rust-cli flake.
fn render_rust_lib_flake(name: &str, rl: &RustLibMeta) -> String {
    let description = rl.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(2048);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(INPUTS);
    out.push_str("\n  outputs =\n");
    out.push_str(RUST_LIB_OUTPUT_HEADER);
    out.push_str("    in\n    {\n");
    out.push_str(&render_rust_lib_devshell(rl));
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

/// `outputs` header for a rust-lib flake: identical to the rust-cli
/// `OUTPUT_HEADER` except the toolchain adds the `wasm32-unknown-unknown`
/// target (so `wasm-check` finds the stdlib) and there's no
/// `rustPlatform` — a lib is never built via `buildRustPackage` here,
/// it's consumed as a path dependency.
const RUST_LIB_OUTPUT_HEADER: &str = r#"    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.stable."1.95.0".minimal.override {
          extensions = [
            "clippy"
            "rustfmt"
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
          targets = [ "wasm32-unknown-unknown" ];
        };
"#;

/// devShell for a rust-lib flake: the wasm-targeted toolchain, any
/// `extraDevShellPackages`, `workflowPackages`, and `cargo-llvm-cov` on
/// Linux (for the `coverage` recipe). Mirrors the rust-cli devShell
/// minus the shell-completion hook.
fn render_rust_lib_devshell(rl: &RustLibMeta) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    out.push_str("            packages = [\n");
    out.push_str("              (rustToolchain pkgs)\n");
    for pkg in &rl.extra_dev_shell_packages {
        out.push_str(&format!("              pkgs.{pkg}\n"));
    }
    out.push_str("            ]\n");
    out.push_str("            ++ (workflowPackages pkgs)\n");
    out.push_str(
        "            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;\n",
    );
    out.push_str("          };\n        }\n      );\n");
    out
}

/// Compose a wasm-app flake: a browser-wasm crate. Same wasm-targeted
/// toolchain and devShell-only shape as a rust-lib (no `packages` — the
/// browser bundle is built by the `wasm-build` recipe, not `nix build`),
/// plus `wasm-bindgen-cli` and `binaryen` (wasm-opt) on the devShell so
/// the `wasm-build` recipe finds them.
fn render_wasm_app_flake(name: &str, wa: &WasmAppMeta) -> String {
    let description = wa.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(2048);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(INPUTS);
    out.push_str("\n  outputs =\n");
    // Reuses the rust-lib header: wasm32-targeted toolchain, no rustPlatform.
    out.push_str(RUST_LIB_OUTPUT_HEADER);
    out.push_str("    in\n    {\n");
    out.push_str(&render_wasm_app_devshell(wa));
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

/// devShell for a wasm-app flake: the wasm-targeted toolchain plus the
/// browser-bundle build tools (`wasm-bindgen-cli` for the JS glue,
/// `binaryen` for `wasm-opt`), any `extraDevShellPackages`,
/// `workflowPackages`, and `cargo-llvm-cov` on Linux.
fn render_wasm_app_devshell(wa: &WasmAppMeta) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    out.push_str("            packages = [\n");
    out.push_str("              (rustToolchain pkgs)\n");
    out.push_str("              pkgs.wasm-bindgen-cli\n");
    out.push_str("              pkgs.binaryen\n");
    for pkg in &wa.extra_dev_shell_packages {
        out.push_str(&format!("              pkgs.{pkg}\n"));
    }
    out.push_str("            ]\n");
    out.push_str("            ++ (workflowPackages pkgs)\n");
    out.push_str(
        "            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;\n",
    );
    out.push_str("          };\n        }\n      );\n");
    out
}

const INPUTS: &str = r#"  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
"#;

const OUTPUT_HEADER: &str = r#"    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.stable."1.95.0".minimal.override {
          extensions = [
            "clippy"
            "rustfmt"
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
        };

      rustPlatform =
        pkgs:
        pkgs.makeRustPlatform {
          cargo = rustToolchain pkgs;
          rustc = rustToolchain pkgs;
        };
"#;

fn render_packages(cli: &CliMeta) -> String {
    let bin = &cli.binary_name;
    let mut out = String::new();
    out.push_str("      packages = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = (rustPlatform pkgs).buildRustPackage {\n");
    out.push_str(&format!("            pname = \"{bin}\";\n"));
    out.push_str("            version = \"0.1.0\";\n");
    out.push_str("            src = ./.;\n");
    out.push_str("            cargoLock.lockFile = ./Cargo.lock;\n");

    if !cli.check_inputs.is_empty() {
        out.push_str(&render_pkg_list("nativeCheckInputs", &cli.check_inputs, 12));
    }

    // jj 0.30+ (nixpkgs 26.05) writes a per-repo "secure config" under
    // `$HOME/.config/jj/repos/`, so `jj config set --repo` aborts when
    // HOME is unwritable. The build sandbox sets HOME=/homeless-shelter,
    // so any project whose tests drive jj needs a writable HOME for the
    // check phase. Scoped to jj-using projects via the `jujutsu` check
    // input rather than emitted unconditionally.
    if cli.check_inputs.iter().any(|i| i == "jujutsu") {
        out.push_str(
            "            preCheck = ''\n              export HOME=\"$(mktemp -d)\"\n            '';\n",
        );
    }

    // `wrapProgram` (from makeWrapper) is needed for a PATH prefix and/or
    // the SHAKA_CUE_MODULE_DIR set, so either knob pulls it in.
    let needs_wrapper = !cli.runtime_path_deps.is_empty() || cli.cue_module.is_some();
    let mut native_build_inputs: Vec<String> = Vec::new();
    if needs_wrapper {
        native_build_inputs.push("makeWrapper".to_string());
    }
    if cli.shell_completions {
        native_build_inputs.push("installShellFiles".to_string());
    }
    if !native_build_inputs.is_empty() {
        out.push_str(&render_pkg_list(
            "nativeBuildInputs",
            &native_build_inputs,
            12,
        ));
    }

    if cli.shell_completions || cli.cue_module.is_some() {
        out.push_str("            postInstall = ''\n");
        if cli.shell_completions {
            out.push_str(&format!(
                "              installShellCompletion --cmd {bin} \\\n                --bash <($out/bin/{bin} completions bash) \\\n                --fish <($out/bin/{bin} completions fish) \\\n                --zsh  <($out/bin/{bin} completions zsh)\n"
            ));
        }
        if let Some(cue) = &cli.cue_module {
            if cli.shell_completions {
                out.push('\n');
            }
            out.push_str(
                "              # Bundle the CUE module closure so schema-dependent\n              # subcommands resolve the schema + registry from a packaged\n              # binary run outside the monorepo (SHAKA_CUE_MODULE_DIR; see\n              # tools/shaka/src/project/schema_check.rs).\n",
            );
            for inc in &cue.include {
                let dest = if inc.to == "." {
                    CUE_BUNDLE_DIR.to_string()
                } else {
                    format!("{CUE_BUNDLE_DIR}/{}", inc.to)
                };
                out.push_str(&format!(
                    "              mkdir -p {dest}\n              cp -r {}/. {dest}/\n",
                    inc.from
                ));
            }
        }
        out.push_str("            '';\n");
    }

    if needs_wrapper {
        out.push_str(&format!(
            "            postFixup = ''\n              wrapProgram $out/bin/{bin}"
        ));
        if !cli.runtime_path_deps.is_empty() {
            out.push_str(" \\\n                --prefix PATH : ${\n                  pkgs.lib.makeBinPath [\n");
            for dep in &cli.runtime_path_deps {
                out.push_str(&format!("                    pkgs.{dep}\n"));
            }
            out.push_str("                  ]\n                }");
        }
        if cli.cue_module.is_some() {
            out.push_str(&format!(
                " \\\n                --set SHAKA_CUE_MODULE_DIR {CUE_BUNDLE_DIR}"
            ));
        }
        out.push_str("\n            '';\n");
    }

    out.push_str("          };\n        }\n      );\n\n");
    out
}

/// `apps.default` is emitted whenever `packages.default` is emitted —
/// it's a one-liner that makes `nix run ./<project>` work, with no
/// downside. The current `tools/claude-hooks` flake omits `apps`; the
/// generator gains it (semantic equivalence covers cosmetic additions
/// that don't change consumer behavior, per #611).
fn render_apps(cli: &CliMeta) -> String {
    let bin = &cli.binary_name;
    format!(
        "      apps = forEachSupportedSystem (\n        {{ system, ... }}:\n        {{\n          default = {{\n            type = \"app\";\n            program = \"${{self.packages.${{system}}.default}}/bin/{bin}\";\n          }};\n        }}\n      );\n\n"
    )
}

fn render_devshell(cli: &CliMeta) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    out.push_str("            packages = [\n");
    out.push_str("              (rustToolchain pkgs)\n");
    for pkg in &cli.extra_dev_shell_packages {
        out.push_str(&format!("              pkgs.{pkg}\n"));
    }
    out.push_str("            ]\n");
    out.push_str("            ++ (workflowPackages pkgs)\n");
    out.push_str(
        "            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;\n",
    );

    if cli.shell_completions {
        let bin = &cli.binary_name;
        out.push_str(&format!(
            "            shellHook = ''\n              if command -v {bin} &>/dev/null; then\n                _completions_dir=\"''${{XDG_CACHE_HOME:-$HOME/.cache}}/kolohelios-completions/{bin}\"\n                mkdir -p \"$_completions_dir\"\n                {bin} completions zsh > \"$_completions_dir/_{bin}\" 2>/dev/null\n                FPATH=\"$_completions_dir:$FPATH\"\n                unset _completions_dir\n              fi\n            '';\n"
        ));
    }

    out.push_str("          };\n        }\n      );\n");
    out
}

/// Compose a rust-worker flake. Shares the rust-cli inputs
/// (kolohelios-nix + nixpkgs + rust-overlay) but the output is
/// devShell-only: workers build to wasm via `worker-build`, not
/// `buildRustPackage`, so there's no `packages`/`apps` and no
/// `rustPlatform`. The toolchain adds the `wasm32-unknown-unknown`
/// target; the devShell carries a fixed base (`wrangler`, a
/// nixpkgs-pinned `worker-build`, plus `pkg-config` and `openssl` for
/// the wasm-bindgen / wasm-opt downloads `worker-build` runs), the
/// `~/.cargo/bin` PATH `shellHook`, and any `extra_dev_shell_packages`.
///
/// When `consumes_shaka` is set the flake also pulls a FlakeHub-built
/// `shaka` into the devShell and PATH-prepends it ahead of the
/// `workflowPackages` shim — see `render_worker_inputs` /
/// `render_worker_devshell` for why external consumers need it.
fn render_worker_flake(name: &str, worker: &WorkerMeta) -> String {
    let description = worker.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(2048);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(&render_worker_inputs(worker.consumes_shaka));
    out.push_str("\n  outputs =\n");
    out.push_str(&render_worker_output_header(worker.consumes_shaka));
    out.push_str("    in\n    {\n");
    out.push_str(&render_worker_devshell(
        &worker.extra_dev_shell_packages,
        worker.consumes_shaka,
    ));
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

/// Inputs for a worker flake. Default is the shared rust `INPUTS`
/// (kolohelios-nix + nixpkgs + rust-overlay). With `consumes_shaka`,
/// splice a `shaka` FlakeHub input in before the closing brace, pinned
/// to follow this flake's `kolohelios-nix` so its nixpkgs/rust-overlay
/// closure dedups against ours in `flake.lock`.
fn render_worker_inputs(consumes_shaka: bool) -> String {
    if !consumes_shaka {
        return INPUTS.to_string();
    }
    let base = INPUTS
        .strip_suffix("  };\n")
        .expect("INPUTS ends with a closing brace line");
    format!(
        "{base}    shaka = {{\n      url = \"https://flakehub.com/f/kolohelios/shaka/*.tar.gz\";\n      inputs.kolohelios-nix.follows = \"kolohelios-nix\";\n    }};\n  }};\n"
    )
}

/// `outputs` header for a worker flake. With `consumes_shaka`, add
/// `shaka` to the destructured inputs so the devShell `shellHook` can
/// reference `shaka.packages.${system}.default`.
fn render_worker_output_header(consumes_shaka: bool) -> String {
    if !consumes_shaka {
        return WORKER_OUTPUT_HEADER.to_string();
    }
    WORKER_OUTPUT_HEADER.replace(
        "      rust-overlay,\n",
        "      rust-overlay,\n      shaka,\n",
    )
}

/// Like `OUTPUT_HEADER` but tailored for workers: the toolchain gains
/// the `wasm32-unknown-unknown` target (so `cargo check --target
/// wasm32-unknown-unknown` and `worker-build` find the stdlib), and
/// `rustPlatform` is omitted since workers never call `buildRustPackage`.
const WORKER_OUTPUT_HEADER: &str = r#"    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.stable."1.95.0".minimal.override {
          extensions = [
            "clippy"
            "rustfmt"
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
          targets = [ "wasm32-unknown-unknown" ];
        };
"#;

/// Devshell block for worker flakes. Fixed base — the worker toolchain,
/// `worker-build`, `pkg-config`, `openssl` — then any
/// `extra_dev_shell_packages`, then `workflowPackages` and the Linux-only
/// `wrangler` and `cargo-llvm-cov`, closing with the `~/.cargo/bin` PATH
/// `shellHook` (appended, not prepended, so a runner's rustup `cargo`
/// doesn't shadow nix's toolchain). `worker-build` is pinned via nixpkgs
/// rather than `cargo install`ed at runtime so its wasm-bindgen minimum
/// can't drift by runner cache (#864).
///
/// `wrangler` is gated to Linux (`lib.optional isLinux`) because its
/// nixpkgs derivation has no darwin binary substitute and source-builds
/// deterministically fail on darwin (EBADF in tsup's DTS step), which
/// would gate the whole shell — `shaka`/`cargo`/`worker-build` never reach
/// PATH. It's only needed at deploy time, and `cf-deploy.yml` runs on
/// `ubuntu-latest` via `nix develop . --command`, so it must stay in the
/// **default** shell on Linux (a separate deploy shell breaks CI verify).
/// See #877.
///
/// With `consumes_shaka`, the devShell function destructures `system`
/// (needed to index `shaka.packages.${system}`) and the `shellHook`
/// PATH-prepends the FlakeHub `shaka` binary ahead of the
/// `workflowPackages` shim, which can't resolve a `shaka` outside the
/// monorepo. The prepend lands before the `~/.cargo/bin` append so the
/// real binary wins.
fn render_worker_devshell(extra_dev_shell_packages: &[String], consumes_shaka: bool) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    if consumes_shaka {
        out.push_str("        { pkgs, system, ... }:\n");
    } else {
        out.push_str("        { pkgs, ... }:\n");
    }
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    out.push_str("            packages = [\n");
    out.push_str("              (rustToolchain pkgs)\n");
    out.push_str("              pkgs.worker-build\n");
    out.push_str("              pkgs.pkg-config\n");
    out.push_str("              pkgs.openssl\n");
    for pkg in extra_dev_shell_packages {
        out.push_str(&format!("              pkgs.{pkg}\n"));
    }
    out.push_str("            ]\n");
    out.push_str("            ++ (workflowPackages pkgs)\n");
    out.push_str(
        "            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.wrangler\n",
    );
    out.push_str(
        "            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;\n",
    );
    out.push_str("\n            shellHook = ''\n");
    if consumes_shaka {
        out.push_str(
            "              export PATH=\"${shaka.packages.${system}.default}/bin:$PATH\"\n",
        );
    }
    out.push_str("              export PATH=\"$PATH:$HOME/.cargo/bin\"\n");
    out.push_str("            '';\n");
    out.push_str("          };\n        }\n      );\n");
    out
}

/// Compose a pandoc-document flake. Devshell carries pandoc + tectonic
/// (the renderer + PDF engine the justfile DOCUMENT_TEMPLATE
/// hardcodes), no rust toolchain, no rust-overlay input. Uses the
/// shared `kolohelios-nix.lib.forEachSupportedSystem` helper directly
/// rather than re-implementing it locally — there's no overlay to
/// thread through, so the wrapper the rust-cli flakes need is
/// unnecessary here.
fn render_document_flake(name: &str, doc: &DocumentMeta) -> String {
    let description = doc.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(DOCUMENT_INPUTS);
    out.push_str("\n  outputs =\n");
    out.push_str(DOCUMENT_OUTPUT_HEADER);
    out.push_str("    in\n    {\n");
    out.push_str(DOCUMENT_DEVSHELL);
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

const DOCUMENT_INPUTS: &str = r#"  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
  };
"#;

const DOCUMENT_OUTPUT_HEADER: &str = r#"    {
      self,
      kolohelios-nix,
      nixpkgs,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) forEachSupportedSystem workflowPackages;
"#;

const DOCUMENT_DEVSHELL: &str = r#"      devShells = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = pkgs.mkShell {
            packages = (workflowPackages pkgs) ++ [
              pkgs.pandoc
              pkgs.tectonic
            ];
          };
        }
      );
"#;

/// Compose an infra flake. Standard shape: kolohelios-nix + nixpkgs
/// inputs (plus any `extra_inputs`), `let .. in` that inherits
/// `forEachSupportedSystem` + `workflowPackages` from the shared lib,
/// devshell composed from `workflowPackages` ++ `dev_shell_packages`.
/// The optional `extra` raw-nix snippet is inserted after devShells
/// (so project-specific outputs like devbox's `nixosConfigurations`
/// or home's `darwinConfigurations` can be tacked on without
/// requiring per-project carve-outs in the generator).
fn render_infra_flake(name: &str, infra: &InfraMeta) -> String {
    let description = infra.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str("  inputs = {\n");
    out.push_str(
        r#"    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";"#,
    );
    out.push('\n');
    out.push_str(r#"    nixpkgs.follows = "kolohelios-nix/nixpkgs";"#);
    out.push('\n');
    for (input_name, spec) in &infra.extra_inputs {
        out.push_str(&render_extra_input(input_name, spec));
    }
    out.push_str("  };\n");
    out.push_str("\n  outputs =\n    {\n      self,\n      kolohelios-nix,\n      nixpkgs,\n");
    for input_name in infra.extra_inputs.keys() {
        out.push_str(&format!("      {input_name},\n"));
    }
    out.push_str("      ...\n    }:\n    let\n");
    out.push_str("      inherit (kolohelios-nix.lib) forEachSupportedSystem workflowPackages;\n");
    if let Some(let_extra) = &infra.let_extra {
        out.push('\n');
        out.push_str(let_extra.trim_end());
        out.push('\n');
    }
    out.push_str("    in\n    {\n");
    out.push_str(&render_infra_devshell(&infra.dev_shell_packages));
    if let Some(extra) = &infra.extra {
        out.push('\n');
        out.push_str(extra.trim_end());
        out.push('\n');
    }
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

/// Render one entry of `inputs = { ... }` for an `extra_inputs` map
/// entry. Single-key (no follows) collapses to `name.url = "...";`;
/// multi-key uses an attrset.
fn render_extra_input(name: &str, spec: &ExtraInput) -> String {
    if spec.follows.is_empty() {
        return format!("    {name}.url = \"{}\";\n", spec.url);
    }
    let mut out = format!("    {name} = {{\n");
    out.push_str(&format!("      url = \"{}\";\n", spec.url));
    for (src, dest) in &spec.follows {
        out.push_str(&format!("      inputs.{src}.follows = \"{dest}\";\n"));
    }
    out.push_str("    };\n");
    out
}

/// Devshell block for infra flakes. `packages` is `(workflowPackages
/// pkgs) ++ [pkgs.X pkgs.Y ...]`. Empty `dev_shell_packages` collapses
/// to just `workflowPackages pkgs` so home's devshell stays minimal.
fn render_infra_devshell(dev_shell_packages: &[String]) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    if dev_shell_packages.is_empty() {
        out.push_str("            packages = workflowPackages pkgs;\n");
    } else {
        out.push_str("            packages =\n");
        out.push_str("              (workflowPackages pkgs)\n");
        out.push_str("              ++ (with pkgs; [\n");
        for pkg in dev_shell_packages {
            out.push_str(&format!("                {pkg}\n"));
        }
        out.push_str("              ]);\n");
    }
    out.push_str("          };\n        }\n      );\n");
    out
}

/// Compose a nix-lib flake. The template provides only the
/// "Do not edit by hand" header, description, `nixpkgs` input, and
/// outputs signature; the entire `let .. in { ... }` body lives in
/// `nl.extra` because nix-lib defines what other flakes import, so its
/// shape isn't a fixed template. Drift checking still applies — every
/// hand-edit shows up as a `--check` failure.
fn render_nix_lib_flake(name: &str, nl: &NixLibMeta) -> String {
    let description = nl.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str("  inputs.nixpkgs.url = \"https://flakehub.com/f/NixOS/nixpkgs/0\";\n");
    out.push_str("\n  outputs =\n");
    out.push_str("    { self, nixpkgs, ... }:\n");
    if let Some(extra) = &nl.extra {
        out.push_str(extra.trim_end());
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

/// Renders a nixpkgs-attr list as `attr = [ pkgs.A pkgs.B ];` or, when
/// it has a single entry, as a single-line `[ pkgs.X ]`. `indent` is
/// the column at which the attribute line starts (used to indent the
/// closing bracket).
fn render_pkg_list(attr: &str, items: &[String], indent: usize) -> String {
    let pad = " ".repeat(indent);
    if items.len() == 1 {
        return format!("{pad}{attr} = [ pkgs.{} ];\n", items[0]);
    }
    let mut out = format!("{pad}{attr} = [\n");
    for item in items {
        out.push_str(&format!("{pad}  pkgs.{item}\n"));
    }
    out.push_str(&format!("{pad}];\n"));
    out
}

fn read_meta(project_dir: &Path) -> Result<ProjectMeta, String> {
    let project_file = project_dir.join("project.cue");
    if !project_file.exists() {
        return Err("missing project.cue".into());
    }

    let output = schema_check::cue_project(&["export"], &project_file)
        .map_err(|e| format!("failed to spawn cue: {e}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!("cue export failed: {stderr}"));
    }

    serde_json::from_slice::<ProjectMeta>(&output.stdout)
        .map_err(|e| format!("could not parse cue export output: {e}"))
}

fn write_all(items: &[(PathBuf, String)]) {
    for (path, content) in items {
        if let Err(e) = std::fs::write(path, content) {
            eprintln!("{RED}{BOLD}error:{RESET} writing {}: {e}", path.display());
            std::process::exit(1);
        }
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-flakes:{RESET} wrote {} files",
        items.len()
    );
}

fn check_drift(items: &[(PathBuf, String)]) {
    let mut drift = Vec::new();
    for (path, expected) in items {
        match std::fs::read_to_string(path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(path.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(path.clone());
            }
        }
    }
    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-flakes --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka project generate-flakes` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        std::process::exit(1);
    }
    println!("{GREEN}{BOLD}generate-flakes --check passed{RESET}");
}

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal_cli() -> CliMeta {
        CliMeta {
            binary_name: "demo".into(),
            description: None,
            package: true,
            runtime_path_deps: vec![],
            check_inputs: vec![],
            shell_completions: false,
            extra_dev_shell_packages: vec![],
            cue_module: None,
        }
    }

    #[test]
    fn rendered_flake_starts_with_generated_header() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn description_defaults_to_project_name() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.contains(r#"description = "demo""#));
    }

    #[test]
    fn description_override_takes_precedence() {
        let cli = CliMeta {
            description: Some("the demo cli".into()),
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains(r#"description = "the demo cli""#));
    }

    #[test]
    fn package_block_omitted_when_package_false() {
        let cli = CliMeta {
            package: false,
            ..minimal_cli()
        };
        let out = render_flake("todoist", &cli);
        // `packages = forEachSupportedSystem` is the top-level
        // packages attribute; `packages = [` also appears inside
        // mkShell, so match on the wider form.
        assert!(!out.contains("packages = forEachSupportedSystem"));
        assert!(!out.contains("apps = forEachSupportedSystem"));
        assert!(out.contains("devShells = forEachSupportedSystem"));
    }

    #[test]
    fn package_implies_apps() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.contains("packages = forEachSupportedSystem"));
        assert!(out.contains("apps = forEachSupportedSystem"));
    }

    #[test]
    fn shell_completions_pulls_in_install_shell_files() {
        let cli = CliMeta {
            shell_completions: true,
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("installShellFiles"));
        assert!(out.contains("installShellCompletion --cmd demo"));
    }

    #[test]
    fn runtime_path_deps_pull_in_make_wrapper_and_post_fixup() {
        let cli = CliMeta {
            runtime_path_deps: vec!["jujutsu".into(), "git".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("makeWrapper"));
        assert!(out.contains("wrapProgram $out/bin/demo"));
        assert!(out.contains("pkgs.jujutsu"));
        assert!(out.contains("pkgs.git"));
    }

    #[test]
    fn cue_module_bundles_closure_and_sets_env() {
        let cli = CliMeta {
            cue_module: Some(CueModule {
                include: vec![
                    CueInclude {
                        from: "cue-bundle".into(),
                        to: ".".into(),
                    },
                    CueInclude {
                        from: "schema".into(),
                        to: "tools/shaka/schema".into(),
                    },
                ],
            }),
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        // makeWrapper + wrapProgram appear even with no runtime path deps.
        assert!(out.contains("makeWrapper"));
        assert!(out.contains("wrapProgram $out/bin/demo"));
        // postInstall copies each include into the bundle root.
        assert!(out.contains("cp -r cue-bundle/. $out/share/shaka/cue/"));
        assert!(out.contains("mkdir -p $out/share/shaka/cue/tools/shaka/schema"));
        assert!(out.contains("cp -r schema/. $out/share/shaka/cue/tools/shaka/schema/"));
        // and the wrap sets the resolver env var.
        assert!(out.contains("--set SHAKA_CUE_MODULE_DIR $out/share/shaka/cue"));
    }

    #[test]
    fn check_inputs_render_as_native_check_inputs() {
        let cli = CliMeta {
            check_inputs: vec!["jujutsu".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("nativeCheckInputs = [ pkgs.jujutsu ];"));
    }

    #[test]
    fn jujutsu_check_input_adds_writable_home_precheck() {
        let cli = CliMeta {
            check_inputs: vec!["jujutsu".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        // jj 0.30+ aborts `config set --repo` without a writable HOME.
        assert!(out.contains("preCheck = ''"));
        assert!(out.contains(r#"export HOME="$(mktemp -d)""#));
    }

    #[test]
    fn no_jujutsu_check_input_omits_precheck() {
        let cli = CliMeta {
            check_inputs: vec!["cue".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(!out.contains("preCheck"));
    }

    #[test]
    fn extra_dev_shell_packages_render_into_dev_shell_list() {
        let cli = CliMeta {
            extra_dev_shell_packages: vec!["actionlint".into(), "taplo".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("pkgs.actionlint"));
        assert!(out.contains("pkgs.taplo"));
    }

    #[test]
    fn worker_flake_starts_with_generated_header() {
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn worker_description_defaults_to_project_name() {
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(out.contains(r#"description = "pollen-alert""#));
    }

    #[test]
    fn worker_description_override_takes_precedence() {
        let worker = WorkerMeta {
            description: Some("kolohelios portfolio worker".into()),
            ..WorkerMeta::default()
        };
        let out = render_worker_flake("kolohelios-portfolio", &worker);
        assert!(out.contains(r#"description = "kolohelios portfolio worker""#));
    }

    #[test]
    fn worker_toolchain_targets_wasm() {
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(out.contains(r#"targets = [ "wasm32-unknown-unknown" ];"#));
    }

    #[test]
    fn worker_omits_packages_apps_and_rust_platform() {
        // Workers build to wasm via worker-build, not buildRustPackage —
        // no packages/apps output, and no rustPlatform let-binding.
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(!out.contains("packages = forEachSupportedSystem"));
        assert!(!out.contains("apps = forEachSupportedSystem"));
        assert!(!out.contains("rustPlatform"));
    }

    #[test]
    fn worker_devshell_carries_fixed_base_and_shell_hook() {
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(out.contains("pkgs.wrangler"));
        assert!(out.contains("pkgs.worker-build"));
        assert!(out.contains("pkgs.pkg-config"));
        assert!(out.contains("pkgs.openssl"));
        assert!(out.contains(r#"export PATH="$PATH:$HOME/.cargo/bin""#));
    }

    #[test]
    fn worker_wrangler_is_linux_gated() {
        // wrangler source-builds (and deterministically fails) on darwin,
        // which would gate the whole shell. It's gated to Linux so darwin
        // shells enter, while cf-deploy.yml (ubuntu) still gets it from the
        // default shell. See #877.
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(out.contains("++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.wrangler"));
        // Not in the unconditional package list.
        assert!(!out.contains("              pkgs.wrangler\n"));
    }

    #[test]
    fn worker_extra_dev_shell_packages_render_into_dev_shell_list() {
        let worker = WorkerMeta {
            extra_dev_shell_packages: vec!["tailwindcss".into(), "cue".into()],
            ..WorkerMeta::default()
        };
        let out = render_worker_flake("kolohelios-portfolio", &worker);
        assert!(out.contains("pkgs.tailwindcss"));
        assert!(out.contains("pkgs.cue"));
    }

    #[test]
    fn worker_flake_carries_formatter() {
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(out.contains("formatter = kolohelios-nix.formatter;"));
    }

    #[test]
    fn worker_without_consumes_shaka_omits_shaka_input_and_path() {
        // Default-false: in-repo workers rely on the workflowPackages
        // shim to resolve the monorepo binary, so nothing shaka-specific
        // is emitted.
        let out = render_worker_flake("pollen-alert", &WorkerMeta::default());
        assert!(!out.contains("flakehub.com/f/kolohelios/shaka"));
        assert!(!out.contains("shaka.packages"));
        assert!(!out.contains("system, ... }:"));
    }

    #[test]
    fn worker_consumes_shaka_adds_flakehub_input() {
        let worker = WorkerMeta {
            consumes_shaka: true,
            ..WorkerMeta::default()
        };
        let out = render_worker_flake("buzzingo", &worker);
        assert!(out.contains(r#"url = "https://flakehub.com/f/kolohelios/shaka/*.tar.gz";"#));
        // Follows our kolohelios-nix so the closure dedups in flake.lock.
        assert!(out.contains(r#"inputs.kolohelios-nix.follows = "kolohelios-nix";"#));
        // The standard base inputs survive the splice.
        assert!(out.contains(r#"nixpkgs.follows = "kolohelios-nix/nixpkgs";"#));
    }

    #[test]
    fn worker_consumes_shaka_adds_input_to_outputs_destructure() {
        let worker = WorkerMeta {
            consumes_shaka: true,
            ..WorkerMeta::default()
        };
        let out = render_worker_flake("buzzingo", &worker);
        // `shaka` must be destructured for the shellHook to reference it,
        // and `system` for the per-system package index.
        assert!(out.contains("      shaka,\n"));
        assert!(out.contains("{ pkgs, system, ... }:"));
    }

    #[test]
    fn worker_consumes_shaka_prepends_shaka_ahead_of_cargo_bin() {
        let worker = WorkerMeta {
            consumes_shaka: true,
            ..WorkerMeta::default()
        };
        let out = render_worker_flake("buzzingo", &worker);
        let shaka_path = out.find(r#"export PATH="${shaka.packages.${system}.default}/bin:$PATH""#);
        let cargo_path = out.find(r#"export PATH="$PATH:$HOME/.cargo/bin""#);
        let shaka_pos = shaka_path.expect("shaka PATH prepend present");
        let cargo_pos = cargo_path.expect("cargo bin PATH append present");
        // The real shaka must win over the shim, so it lands first.
        assert!(shaka_pos < cargo_pos);
    }

    #[test]
    fn document_flake_starts_with_generated_header() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn document_description_defaults_to_project_name() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.contains(r#"description = "resume""#));
    }

    #[test]
    fn document_description_override_takes_precedence() {
        let doc = DocumentMeta {
            description: Some("kolohelios resume".into()),
        };
        let out = render_document_flake("resume", &doc);
        assert!(out.contains(r#"description = "kolohelios resume""#));
    }

    #[test]
    fn document_flake_omits_rust_overlay() {
        // Document devshells don't need a rust toolchain; the
        // overlay input would be dead weight and would surface as a
        // rust-overlay entry in `flake.lock`.
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(!out.contains("rust-overlay"));
        assert!(!out.contains("rustToolchain"));
    }

    #[test]
    fn document_devshell_includes_pandoc_and_tectonic() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.contains("pkgs.pandoc"));
        assert!(out.contains("pkgs.tectonic"));
    }

    #[test]
    fn document_flake_carries_formatter() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.contains("formatter = kolohelios-nix.formatter;"));
    }

    #[test]
    fn infra_flake_starts_with_generated_header() {
        let out = render_infra_flake("cloudflare-dns", &InfraMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn infra_description_defaults_to_project_name() {
        let out = render_infra_flake("cloudflare-dns", &InfraMeta::default());
        assert!(out.contains(r#"description = "cloudflare-dns""#));
    }

    #[test]
    fn infra_description_override_takes_precedence() {
        let infra = InfraMeta {
            description: Some("kolohelios — DNS".into()),
            ..InfraMeta::default()
        };
        let out = render_infra_flake("cloudflare-dns", &infra);
        assert!(out.contains(r#"description = "kolohelios — DNS""#));
    }

    #[test]
    fn infra_dev_shell_packages_appear_with_with_pkgs() {
        let infra = InfraMeta {
            dev_shell_packages: vec!["opentofu".into(), "_1password-cli".into()],
            ..InfraMeta::default()
        };
        let out = render_infra_flake("cf", &infra);
        assert!(out.contains("(workflowPackages pkgs)"));
        assert!(out.contains("(with pkgs; ["));
        assert!(out.contains("opentofu"));
        assert!(out.contains("_1password-cli"));
    }

    #[test]
    fn infra_empty_dev_shell_packages_collapses_to_workflow_packages_only() {
        let out = render_infra_flake("home", &InfraMeta::default());
        assert!(out.contains("packages = workflowPackages pkgs;"));
        assert!(!out.contains("(with pkgs; ["));
    }

    #[test]
    fn infra_extra_inputs_with_follows_render_as_attrset() {
        let mut extra_inputs = BTreeMap::new();
        extra_inputs.insert(
            "home-env".into(),
            ExtraInput {
                url: "https://flakehub.com/f/kolohelios/home/*.tar.gz".into(),
                follows: {
                    let mut m = BTreeMap::new();
                    m.insert("nixpkgs".into(), "nixpkgs".into());
                    m
                },
            },
        );
        let infra = InfraMeta {
            extra_inputs,
            ..InfraMeta::default()
        };
        let out = render_infra_flake("devbox", &infra);
        assert!(out.contains("home-env = {"));
        assert!(out.contains(r#"url = "https://flakehub.com/f/kolohelios/home/*.tar.gz";"#));
        assert!(out.contains(r#"inputs.nixpkgs.follows = "nixpkgs";"#));
        // The input also has to land in the outputs destructure.
        assert!(out.contains("home-env,"));
    }

    #[test]
    fn infra_extra_input_without_follows_collapses_to_one_liner() {
        let mut extra_inputs = BTreeMap::new();
        extra_inputs.insert(
            "claude-hooks".into(),
            ExtraInput {
                url: "https://flakehub.com/f/kolohelios/claude-hooks/*.tar.gz".into(),
                follows: BTreeMap::new(),
            },
        );
        let infra = InfraMeta {
            extra_inputs,
            ..InfraMeta::default()
        };
        let out = render_infra_flake("home", &infra);
        assert!(out.contains(
            r#"claude-hooks.url = "https://flakehub.com/f/kolohelios/claude-hooks/*.tar.gz";"#
        ));
    }

    #[test]
    fn infra_extra_sandbox_lands_after_devshells_and_before_formatter() {
        let infra = InfraMeta {
            extra: Some("      nixosConfigurations.devbox = { hi = 1; };\n".into()),
            ..InfraMeta::default()
        };
        let out = render_infra_flake("devbox", &infra);
        let dev_pos = out
            .find("devShells = forEachSupportedSystem")
            .expect("devShells");
        let extra_pos = out.find("nixosConfigurations.devbox").expect("extra");
        let fmt_pos = out
            .find("formatter = kolohelios-nix.formatter")
            .expect("formatter");
        assert!(dev_pos < extra_pos, "extra should come after devShells");
        assert!(extra_pos < fmt_pos, "extra should come before formatter");
    }

    #[test]
    fn nix_lib_flake_starts_with_generated_header() {
        let out = render_nix_lib_flake("kolohelios-nix", &NixLibMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn nix_lib_flake_uses_nixpkgs_only_input() {
        // nix-lib doesn't import kolohelios-nix (would be circular for
        // the canonical case) — only nixpkgs.
        let out = render_nix_lib_flake("kolohelios-nix", &NixLibMeta::default());
        assert!(out.contains(r#"inputs.nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0";"#));
        assert!(!out.contains("kolohelios-nix.url"));
    }

    #[test]
    fn nix_lib_extra_sandbox_lands_inside_outputs() {
        let nl = NixLibMeta {
            extra: Some("    let supportedSystems = []; in { lib = {}; };\n".into()),
            ..NixLibMeta::default()
        };
        let out = render_nix_lib_flake("kolohelios-nix", &nl);
        let outputs_pos = out.find("outputs =").expect("outputs");
        let extra_pos = out.find("supportedSystems = []").expect("extra");
        assert!(outputs_pos < extra_pos);
    }

    #[test]
    fn shell_completions_emit_devshell_shell_hook() {
        let cli = CliMeta {
            shell_completions: true,
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("shellHook"));
        assert!(out.contains("demo completions zsh"));
        assert!(out.contains("kolohelios-completions/demo"));
        assert!(out.contains("FPATH="));
        // Verify nix escaping: ''${ produces a literal ${ in the shell
        assert!(out.contains("''${XDG_CACHE_HOME:-"));
    }

    #[test]
    fn no_shell_hook_without_shell_completions() {
        let out = render_flake("demo", &minimal_cli());
        assert!(!out.contains("shellHook"));
    }

    #[test]
    fn rust_lib_flake_starts_with_generated_header() {
        let out = render_rust_lib_flake("notes-protocol", &RustLibMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn rust_lib_description_defaults_to_project_name() {
        let out = render_rust_lib_flake("notes-protocol", &RustLibMeta::default());
        assert!(out.contains(r#"description = "notes-protocol""#));
    }

    #[test]
    fn rust_lib_description_override_takes_precedence() {
        let rl = RustLibMeta {
            description: Some("notes-protocol — wire types".into()),
            ..RustLibMeta::default()
        };
        let out = render_rust_lib_flake("notes-protocol", &rl);
        assert!(out.contains(r#"description = "notes-protocol — wire types""#));
    }

    #[test]
    fn rust_lib_flake_carries_wasm_target() {
        // The lib is consumed on wasm32-unknown-unknown, so the toolchain
        // must add the target for the `wasm-check` recipe to find the stdlib.
        let out = render_rust_lib_flake("notes-protocol", &RustLibMeta::default());
        assert!(out.contains(r#"targets = [ "wasm32-unknown-unknown" ];"#));
    }

    #[test]
    fn rust_lib_flake_is_devshell_only() {
        // A lib produces no binary — no packages/apps, no buildRustPackage.
        let out = render_rust_lib_flake("notes-protocol", &RustLibMeta::default());
        assert!(!out.contains("packages = forEachSupportedSystem"));
        assert!(!out.contains("apps = forEachSupportedSystem"));
        assert!(!out.contains("buildRustPackage"));
        assert!(out.contains("devShells = forEachSupportedSystem"));
    }

    #[test]
    fn rust_lib_extra_dev_shell_packages_render_into_dev_shell() {
        let rl = RustLibMeta {
            extra_dev_shell_packages: vec!["wabt".into(), "wasm-tools".into()],
            ..RustLibMeta::default()
        };
        let out = render_rust_lib_flake("notes-protocol", &rl);
        assert!(out.contains("pkgs.wabt"));
        assert!(out.contains("pkgs.wasm-tools"));
    }

    #[test]
    fn rust_lib_flake_carries_formatter() {
        let out = render_rust_lib_flake("notes-protocol", &RustLibMeta::default());
        assert!(out.contains("formatter = kolohelios-nix.formatter;"));
    }

    #[test]
    fn wasm_app_flake_starts_with_generated_header() {
        let out = render_wasm_app_flake("notes-editor", &WasmAppMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn wasm_app_description_defaults_to_project_name() {
        let out = render_wasm_app_flake("notes-editor", &WasmAppMeta::default());
        assert!(out.contains(r#"description = "notes-editor""#));
    }

    #[test]
    fn wasm_app_flake_carries_wasm_target_and_bundle_tools() {
        // wasm32 target for the build, plus wasm-bindgen + binaryen for the
        // `wasm-build` recipe's JS-glue and wasm-opt steps.
        let out = render_wasm_app_flake("notes-editor", &WasmAppMeta::default());
        assert!(out.contains(r#"targets = [ "wasm32-unknown-unknown" ];"#));
        assert!(out.contains("pkgs.wasm-bindgen-cli"));
        assert!(out.contains("pkgs.binaryen"));
    }

    #[test]
    fn wasm_app_flake_is_devshell_only() {
        // The browser bundle is built by `wasm-build`, not `nix build`.
        let out = render_wasm_app_flake("notes-editor", &WasmAppMeta::default());
        assert!(!out.contains("packages = forEachSupportedSystem"));
        assert!(!out.contains("buildRustPackage"));
        assert!(out.contains("devShells = forEachSupportedSystem"));
        assert!(out.contains("formatter = kolohelios-nix.formatter;"));
    }

    #[test]
    fn wasm_app_extra_dev_shell_packages_render_into_dev_shell() {
        let wa = WasmAppMeta {
            extra_dev_shell_packages: vec!["wasm-pack".into()],
            ..WasmAppMeta::default()
        };
        let out = render_wasm_app_flake("notes-editor", &wa);
        assert!(out.contains("pkgs.wasm-pack"));
    }
}
