use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

const GREEN: &str = "\x1b[32m";
const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
const RESET: &str = "\x1b[0m";

const SCHEMA: &str = include_str!("../../schema/project.cue");
const SLOTS: &[&str] = &["apps", "infra", "nix", "packages", "services", "tools"];

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka project generate-justfiles` to update; CI fails on drift.\n\n";

const RUST_TEMPLATE: &str = r#"build:
    cargo build --release

test:
    cargo test

fmt:
    cargo fmt

fmt-check:
    cargo fmt --check

lint:
    cargo clippy --all-targets -- -D warnings

coverage:
    #!/usr/bin/env bash
    set -euo pipefail
    thresholds=$(cue export ../../tools/shaka/schema/project.cue project.cue)
    fail_line=$(jq <<<"$thresholds" '.coverage.line.fail')
    fail_branch=$(jq <<<"$thresholds" '.coverage.branch.fail')
    measured=$(cargo llvm-cov --json --summary-only --branch)
    line=$(jq <<<"$measured" '.data[0].totals.lines.percent')
    branch=$(jq <<<"$measured" '.data[0].totals.branches.percent')
    printf 'coverage: line=%.1f%% branch=%.1f%% (gates: line>=%s%% branch>=%s%%)\n' \
        "$line" "$branch" "$fail_line" "$fail_branch"
    awk -v l="$line" -v b="$branch" -v fl="$fail_line" -v fb="$fail_branch" \
        'BEGIN { exit (l < fl || b < fb) ? 1 : 0 }'

validate: fmt-check lint test coverage
"#;

const NIX_LIB_TEMPLATE: &str = r#"flake-check:
    nix flake check

validate: flake-check
"#;

const INFRA_TEMPLATE: &str = r#"validate:
    cd terraform && tofu init -backend=false -input=false && tofu validate

plan:
    cd terraform && tofu init -input=false && tofu plan

apply:
    cd terraform && tofu apply
"#;

#[derive(Deserialize)]
struct ProjectMeta {
    #[allow(dead_code)]
    name: String,
    kind: String,
}

pub fn run(check: bool) {
    let schema_path = match write_schema() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("{RED}{BOLD}error:{RESET} could not write schema: {e}");
            std::process::exit(1);
        }
    };

    let mut items: Vec<(PathBuf, String)> = Vec::new();

    let projects = discover_projects(Path::new("."));
    for project in &projects {
        match read_meta(&schema_path, project) {
            Ok(meta) => match template_for(&meta.kind) {
                Some(body) => items.push((project.join("justfile"), render(body))),
                None => {
                    eprintln!(
                        "{RED}{BOLD}error:{RESET} {} has unknown kind {:?}",
                        project.display(),
                        meta.kind
                    );
                    std::process::exit(1);
                }
            },
            Err(e) => {
                eprintln!(
                    "{RED}{BOLD}error:{RESET} could not read {}: {e}",
                    project.display()
                );
                std::process::exit(1);
            }
        }
    }

    if check {
        check_drift(&items);
    } else {
        write_all(&items);
    }
}

fn template_for(kind: &str) -> Option<&'static str> {
    match kind {
        "rust" => Some(RUST_TEMPLATE),
        "infra" => Some(INFRA_TEMPLATE),
        "nix-lib" => Some(NIX_LIB_TEMPLATE),
        _ => None,
    }
}

fn render(body: &str) -> String {
    format!("{HEADER}{body}")
}

fn write_all(items: &[(PathBuf, String)]) {
    for (path, content) in items {
        if let Err(e) = std::fs::write(path, content) {
            eprintln!("{RED}{BOLD}error:{RESET} writing {}: {e}", path.display());
            std::process::exit(1);
        }
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-justfiles:{RESET} wrote {} files",
        items.len()
    );
}

fn check_drift(items: &[(PathBuf, String)]) {
    let mut drift = Vec::new();
    for (path, expected) in items {
        match std::fs::read_to_string(path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(path.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(path.clone());
            }
        }
    }
    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-justfiles --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka project generate-justfiles` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        std::process::exit(1);
    }
    println!("{GREEN}{BOLD}generate-justfiles --check passed{RESET}");
}

fn discover_projects(root: &Path) -> Vec<PathBuf> {
    let mut projects = Vec::new();
    for slot in SLOTS {
        let slot_dir = root.join(slot);
        let entries = match std::fs::read_dir(&slot_dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                projects.push(path);
            }
        }
    }
    projects.sort();
    projects
}

fn read_meta(schema_path: &Path, project_dir: &Path) -> Result<ProjectMeta, String> {
    let project_file = project_dir.join("project.cue");
    if !project_file.exists() {
        return Err("missing project.cue".into());
    }

    let output = Command::new("cue")
        .arg("export")
        .arg(schema_path)
        .arg(&project_file)
        .output()
        .map_err(|e| format!("failed to spawn cue: {e}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!("cue export failed: {stderr}"));
    }

    serde_json::from_slice::<ProjectMeta>(&output.stdout)
        .map_err(|e| format!("could not parse cue export output: {e}"))
}

fn write_schema() -> std::io::Result<PathBuf> {
    let path = std::env::temp_dir().join("shaka-generate-schema.cue");
    let mut f = std::fs::File::create(&path)?;
    f.write_all(SCHEMA.as_bytes())?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_for_rust_returns_rust_template() {
        assert_eq!(template_for("rust"), Some(RUST_TEMPLATE));
    }

    #[test]
    fn template_for_infra_returns_infra_template() {
        assert_eq!(template_for("infra"), Some(INFRA_TEMPLATE));
    }

    #[test]
    fn template_for_nix_lib_returns_nix_lib_template() {
        assert_eq!(template_for("nix-lib"), Some(NIX_LIB_TEMPLATE));
    }

    #[test]
    fn template_for_unknown_kind_returns_none() {
        assert!(template_for("python").is_none());
        assert!(template_for("").is_none());
    }

    #[test]
    fn nix_lib_template_runs_flake_check() {
        assert!(NIX_LIB_TEMPLATE.contains("flake-check:"));
        assert!(NIX_LIB_TEMPLATE.contains("nix flake check"));
        assert!(NIX_LIB_TEMPLATE.contains("validate: flake-check"));
    }

    #[test]
    fn render_prepends_header() {
        let out = render("foo:\n    echo bar\n");
        assert!(out.starts_with("# Generated by shaka."));
        assert!(out.ends_with("foo:\n    echo bar\n"));
    }

    #[test]
    fn rust_template_includes_quality_recipes() {
        assert!(RUST_TEMPLATE.contains("fmt-check"));
        assert!(RUST_TEMPLATE.contains("clippy"));
        assert!(RUST_TEMPLATE.contains("validate: fmt-check lint test coverage"));
    }

    #[test]
    fn rust_template_includes_coverage_recipe() {
        assert!(RUST_TEMPLATE.contains("coverage:"));
        assert!(RUST_TEMPLATE.contains("cargo llvm-cov"));
        assert!(RUST_TEMPLATE.contains("cue export ../../tools/shaka/schema/project.cue"));
        assert!(RUST_TEMPLATE.contains(".coverage.line.fail"));
        assert!(RUST_TEMPLATE.contains(".coverage.branch.fail"));
    }

    #[test]
    fn infra_template_uses_tofu() {
        assert!(INFRA_TEMPLATE.contains("tofu validate"));
        assert!(INFRA_TEMPLATE.contains("tofu plan"));
        assert!(INFRA_TEMPLATE.contains("tofu apply"));
        assert!(!INFRA_TEMPLATE.contains("terraform validate"));
        assert!(!INFRA_TEMPLATE.contains("terraform plan"));
    }
}
