use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

use crate::term::{BOLD, DIM, GREEN, RED, RESET, YELLOW};

const SCHEMA: &str = include_str!("../../schema/project-schema.cue");

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka project generate-flakes` to update; CI fails on drift.\n";

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProjectMeta {
    name: String,
    kind: String,
    #[serde(default)]
    cli: Option<CliMeta>,
    #[serde(default)]
    document: Option<DocumentMeta>,
    #[serde(default)]
    infra: Option<InfraMeta>,
    #[serde(default)]
    nix_lib: Option<NixLibMeta>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CliMeta {
    binary_name: String,
    #[serde(default)]
    description: Option<String>,
    package: bool,
    #[serde(default)]
    runtime_path_deps: Vec<String>,
    #[serde(default)]
    check_inputs: Vec<String>,
    shell_completions: bool,
    #[serde(default)]
    extra_dev_shell_packages: Vec<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct DocumentMeta {
    #[serde(default)]
    description: Option<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct InfraMeta {
    #[serde(default)]
    description: Option<String>,
    /// Map of extra flake input name → spec. Sorted lexicographically
    /// at emit time so the generator's output is stable regardless of
    /// CUE iteration order.
    #[serde(default)]
    extra_inputs: BTreeMap<String, ExtraInput>,
    #[serde(default)]
    dev_shell_packages: Vec<String>,
    /// Raw nix snippet inserted inside the standard `let ..` block,
    /// before `in { ... }`. Used by projects whose extra outputs share
    /// computed values (devbox's `devboxConfig` / `imageConfig`).
    #[serde(default)]
    let_extra: Option<String>,
    /// Raw nix snippet inserted inside `outputs.{...}: let .. in { HERE }`,
    /// after the standard `devShells` block but before `formatter`. See
    /// `feedback_no_exceptions.md` — this is the escape sandbox for
    /// projects whose flake shape doesn't fit the default infra
    /// template (devbox, home), keeping them inside the generator's
    /// drift-checked envelope instead of carving exceptions.
    #[serde(default)]
    extra: Option<String>,
}

#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NixLibMeta {
    #[serde(default)]
    description: Option<String>,
    /// Same escape sandbox principle as `infra.extra`, but for nix-lib
    /// it carries the *entire* `let .. in { ... }` body of `outputs`.
    /// Reason: nix-lib defines what other flakes import, so the lib's
    /// shape isn't a fixed template — the let-bindings, the `lib =
    /// { inherit ... }` export, formatter, devShells are all
    /// project-specific. The template provides only the flake header,
    /// description, nixpkgs input, and outputs signature.
    #[serde(default)]
    extra: Option<String>,
}

#[derive(Default, Deserialize)]
struct ExtraInput {
    url: String,
    #[serde(default)]
    follows: BTreeMap<String, String>,
}

pub fn run(check: bool) {
    let schema_path = match write_schema() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("{RED}{BOLD}error:{RESET} could not write schema: {e}");
            std::process::exit(1);
        }
    };

    let projects = crate::project::schema_check::discover(Path::new("."));
    let mut items: Vec<(PathBuf, String)> = Vec::new();
    for project in &projects {
        let meta = match read_meta(&schema_path, project) {
            Ok(m) => m,
            Err(e) => {
                eprintln!(
                    "{RED}{BOLD}error:{RESET} could not read {}: {e}",
                    project.display()
                );
                std::process::exit(1);
            }
        };
        match meta.kind.as_str() {
            "rust-cli" => {
                let cli = meta.cli.as_ref().unwrap_or_else(|| {
                    eprintln!(
                        "{RED}{BOLD}error:{RESET} {} is kind rust-cli but has no `cli:` block",
                        project.display()
                    );
                    std::process::exit(1);
                });
                items.push((project.join("flake.nix"), render_flake(&meta.name, cli)));
            }
            "document" => {
                // `document:` is optional in the schema — fall back to a
                // default-initialized block so a project that doesn't
                // override description still picks up the project name.
                let default = DocumentMeta::default();
                let doc = meta.document.as_ref().unwrap_or(&default);
                items.push((
                    project.join("flake.nix"),
                    render_document_flake(&meta.name, doc),
                ));
            }
            "infra" => {
                // Opt-in: only generate when the project.cue declares
                // an `infra:` block. Projects without one keep their
                // hand-authored flake until they're migrated. This is
                // the migration ramp — once every kind:infra project
                // carries `infra:`, the block can become required.
                let Some(infra) = meta.infra.as_ref() else {
                    continue;
                };
                items.push((
                    project.join("flake.nix"),
                    render_infra_flake(&meta.name, infra),
                ));
            }
            "nix-lib" => {
                // Same opt-in pattern as `infra`.
                let Some(nl) = meta.nix_lib.as_ref() else {
                    continue;
                };
                items.push((
                    project.join("flake.nix"),
                    render_nix_lib_flake(&meta.name, nl),
                ));
            }
            // Other kinds keep their hand-authored flake.nix until the
            // generator grows a template for them: rust-worker follows
            // in a separate issue.
            _ => continue,
        }
    }

    if check {
        check_drift(&items);
    } else {
        write_all(&items);
    }
}

/// Compose the flake.nix body. `name` is the project name (used as
/// fallback `description`); `cli` carries the shape knobs read from
/// `project.cue`.
fn render_flake(name: &str, cli: &CliMeta) -> String {
    let description = cli.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(2048);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(INPUTS);
    out.push_str("\n  outputs =\n");
    out.push_str(OUTPUT_HEADER);
    out.push_str("    in\n    {\n");
    if cli.package {
        out.push_str(&render_packages(cli));
        out.push_str(&render_apps(cli));
    }
    out.push_str(&render_devshell(cli));
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

const INPUTS: &str = r#"  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
"#;

const OUTPUT_HEADER: &str = r#"    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.nightly.latest.default.override {
          extensions = [
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
        };
"#;

fn render_packages(cli: &CliMeta) -> String {
    let bin = &cli.binary_name;
    let mut out = String::new();
    out.push_str("      packages = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.rustPlatform.buildRustPackage {\n");
    out.push_str(&format!("            pname = \"{bin}\";\n"));
    out.push_str("            version = \"0.1.0\";\n");
    out.push_str("            src = ./.;\n");
    out.push_str("            cargoLock.lockFile = ./Cargo.lock;\n");

    if !cli.check_inputs.is_empty() {
        out.push_str(&render_pkg_list("nativeCheckInputs", &cli.check_inputs, 12));
    }

    let mut native_build_inputs: Vec<String> = Vec::new();
    if !cli.runtime_path_deps.is_empty() {
        native_build_inputs.push("makeWrapper".to_string());
    }
    if cli.shell_completions {
        native_build_inputs.push("installShellFiles".to_string());
    }
    if !native_build_inputs.is_empty() {
        out.push_str(&render_pkg_list(
            "nativeBuildInputs",
            &native_build_inputs,
            12,
        ));
    }

    if cli.shell_completions {
        out.push_str(&format!(
            "            postInstall = ''\n              installShellCompletion --cmd {bin} \\\n                --bash <($out/bin/{bin} completions bash) \\\n                --fish <($out/bin/{bin} completions fish) \\\n                --zsh  <($out/bin/{bin} completions zsh)\n            '';\n"
        ));
    }

    if !cli.runtime_path_deps.is_empty() {
        out.push_str(&format!(
            "            postFixup = ''\n              wrapProgram $out/bin/{bin} \\\n                --prefix PATH : ${{\n                  pkgs.lib.makeBinPath [\n"
        ));
        for dep in &cli.runtime_path_deps {
            out.push_str(&format!("                    pkgs.{dep}\n"));
        }
        out.push_str("                  ]\n                }\n            '';\n");
    }

    out.push_str("          };\n        }\n      );\n\n");
    out
}

/// `apps.default` is emitted whenever `packages.default` is emitted —
/// it's a one-liner that makes `nix run ./<project>` work, with no
/// downside. The current `tools/claude-hooks` flake omits `apps`; the
/// generator gains it (semantic equivalence covers cosmetic additions
/// that don't change consumer behavior, per #611).
fn render_apps(cli: &CliMeta) -> String {
    let bin = &cli.binary_name;
    format!(
        "      apps = forEachSupportedSystem (\n        {{ system, ... }}:\n        {{\n          default = {{\n            type = \"app\";\n            program = \"${{self.packages.${{system}}.default}}/bin/{bin}\";\n          }};\n        }}\n      );\n\n"
    )
}

fn render_devshell(cli: &CliMeta) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    out.push_str("            packages = [\n");
    out.push_str("              (rustToolchain pkgs)\n");
    for pkg in &cli.extra_dev_shell_packages {
        out.push_str(&format!("              pkgs.{pkg}\n"));
    }
    out.push_str("            ]\n");
    out.push_str("            ++ (workflowPackages pkgs)\n");
    out.push_str(
        "            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;\n",
    );
    out.push_str("          };\n        }\n      );\n");
    out
}

/// Compose a pandoc-document flake. Devshell carries pandoc + tectonic
/// (the renderer + PDF engine the justfile DOCUMENT_TEMPLATE
/// hardcodes), no rust toolchain, no rust-overlay input. Uses the
/// shared `kolohelios-nix.lib.forEachSupportedSystem` helper directly
/// rather than re-implementing it locally — there's no overlay to
/// thread through, so the wrapper the rust-cli flakes need is
/// unnecessary here.
fn render_document_flake(name: &str, doc: &DocumentMeta) -> String {
    let description = doc.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str(DOCUMENT_INPUTS);
    out.push_str("\n  outputs =\n");
    out.push_str(DOCUMENT_OUTPUT_HEADER);
    out.push_str("    in\n    {\n");
    out.push_str(DOCUMENT_DEVSHELL);
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

const DOCUMENT_INPUTS: &str = r#"  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
  };
"#;

const DOCUMENT_OUTPUT_HEADER: &str = r#"    {
      self,
      kolohelios-nix,
      nixpkgs,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) forEachSupportedSystem workflowPackages;
"#;

const DOCUMENT_DEVSHELL: &str = r#"      devShells = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = pkgs.mkShell {
            packages = (workflowPackages pkgs) ++ [
              pkgs.pandoc
              pkgs.tectonic
            ];
          };
        }
      );
"#;

/// Compose an infra flake. Standard shape: kolohelios-nix + nixpkgs
/// inputs (plus any `extra_inputs`), `let .. in` that inherits
/// `forEachSupportedSystem` + `workflowPackages` from the shared lib,
/// devshell composed from `workflowPackages` ++ `dev_shell_packages`.
/// The optional `extra` raw-nix snippet is inserted after devShells
/// (so project-specific outputs like devbox's `nixosConfigurations`
/// or home's `darwinConfigurations` can be tacked on without
/// requiring per-project carve-outs in the generator).
fn render_infra_flake(name: &str, infra: &InfraMeta) -> String {
    let description = infra.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str("  inputs = {\n");
    out.push_str(
        r#"    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";"#,
    );
    out.push('\n');
    out.push_str(r#"    nixpkgs.follows = "kolohelios-nix/nixpkgs";"#);
    out.push('\n');
    for (input_name, spec) in &infra.extra_inputs {
        out.push_str(&render_extra_input(input_name, spec));
    }
    out.push_str("  };\n");
    out.push_str("\n  outputs =\n    {\n      self,\n      kolohelios-nix,\n      nixpkgs,\n");
    for input_name in infra.extra_inputs.keys() {
        out.push_str(&format!("      {input_name},\n"));
    }
    out.push_str("      ...\n    }:\n    let\n");
    out.push_str("      inherit (kolohelios-nix.lib) forEachSupportedSystem workflowPackages;\n");
    if let Some(let_extra) = &infra.let_extra {
        out.push('\n');
        out.push_str(let_extra.trim_end());
        out.push('\n');
    }
    out.push_str("    in\n    {\n");
    out.push_str(&render_infra_devshell(&infra.dev_shell_packages));
    if let Some(extra) = &infra.extra {
        out.push('\n');
        out.push_str(extra.trim_end());
        out.push('\n');
    }
    out.push_str("\n      formatter = kolohelios-nix.formatter;\n    };\n");
    out.push_str("}\n");
    out
}

/// Render one entry of `inputs = { ... }` for an `extra_inputs` map
/// entry. Single-key (no follows) collapses to `name.url = "...";`;
/// multi-key uses an attrset.
fn render_extra_input(name: &str, spec: &ExtraInput) -> String {
    if spec.follows.is_empty() {
        return format!("    {name}.url = \"{}\";\n", spec.url);
    }
    let mut out = format!("    {name} = {{\n");
    out.push_str(&format!("      url = \"{}\";\n", spec.url));
    for (src, dest) in &spec.follows {
        out.push_str(&format!("      inputs.{src}.follows = \"{dest}\";\n"));
    }
    out.push_str("    };\n");
    out
}

/// Devshell block for infra flakes. `packages` is `(workflowPackages
/// pkgs) ++ [pkgs.X pkgs.Y ...]`. Empty `dev_shell_packages` collapses
/// to just `workflowPackages pkgs` so home's devshell stays minimal.
fn render_infra_devshell(dev_shell_packages: &[String]) -> String {
    let mut out = String::new();
    out.push_str("      devShells = forEachSupportedSystem (\n");
    out.push_str("        { pkgs, ... }:\n");
    out.push_str("        {\n");
    out.push_str("          default = pkgs.mkShell {\n");
    if dev_shell_packages.is_empty() {
        out.push_str("            packages = workflowPackages pkgs;\n");
    } else {
        out.push_str("            packages =\n");
        out.push_str("              (workflowPackages pkgs)\n");
        out.push_str("              ++ (with pkgs; [\n");
        for pkg in dev_shell_packages {
            out.push_str(&format!("                {pkg}\n"));
        }
        out.push_str("              ]);\n");
    }
    out.push_str("          };\n        }\n      );\n");
    out
}

/// Compose a nix-lib flake. The template provides only the
/// "Do not edit by hand" header, description, `nixpkgs` input, and
/// outputs signature; the entire `let .. in { ... }` body lives in
/// `nl.extra` because nix-lib defines what other flakes import, so its
/// shape isn't a fixed template. Drift checking still applies — every
/// hand-edit shows up as a `--check` failure.
fn render_nix_lib_flake(name: &str, nl: &NixLibMeta) -> String {
    let description = nl.description.as_deref().unwrap_or(name);
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str(&format!("{{\n  description = \"{description}\";\n\n"));
    out.push_str("  inputs.nixpkgs.url = \"https://flakehub.com/f/NixOS/nixpkgs/0\";\n");
    out.push_str("\n  outputs =\n");
    out.push_str("    { self, nixpkgs, ... }:\n");
    if let Some(extra) = &nl.extra {
        out.push_str(extra.trim_end());
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

/// Renders a nixpkgs-attr list as `attr = [ pkgs.A pkgs.B ];` or, when
/// it has a single entry, as a single-line `[ pkgs.X ]`. `indent` is
/// the column at which the attribute line starts (used to indent the
/// closing bracket).
fn render_pkg_list(attr: &str, items: &[String], indent: usize) -> String {
    let pad = " ".repeat(indent);
    if items.len() == 1 {
        return format!("{pad}{attr} = [ pkgs.{} ];\n", items[0]);
    }
    let mut out = format!("{pad}{attr} = [\n");
    for item in items {
        out.push_str(&format!("{pad}  pkgs.{item}\n"));
    }
    out.push_str(&format!("{pad}];\n"));
    out
}

fn read_meta(schema_path: &Path, project_dir: &Path) -> Result<ProjectMeta, String> {
    let project_file = project_dir.join("project.cue");
    if !project_file.exists() {
        return Err("missing project.cue".into());
    }

    let output = Command::new("cue")
        .arg("export")
        .arg(schema_path)
        .arg(&project_file)
        .output()
        .map_err(|e| format!("failed to spawn cue: {e}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!("cue export failed: {stderr}"));
    }

    serde_json::from_slice::<ProjectMeta>(&output.stdout)
        .map_err(|e| format!("could not parse cue export output: {e}"))
}

fn write_schema() -> std::io::Result<PathBuf> {
    let path = std::env::temp_dir().join(format!(
        "shaka-generate-flakes-schema-{}.cue",
        std::process::id()
    ));
    let mut f = std::fs::File::create(&path)?;
    f.write_all(SCHEMA.as_bytes())?;
    Ok(path)
}

fn write_all(items: &[(PathBuf, String)]) {
    for (path, content) in items {
        if let Err(e) = std::fs::write(path, content) {
            eprintln!("{RED}{BOLD}error:{RESET} writing {}: {e}", path.display());
            std::process::exit(1);
        }
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-flakes:{RESET} wrote {} files",
        items.len()
    );
}

fn check_drift(items: &[(PathBuf, String)]) {
    let mut drift = Vec::new();
    for (path, expected) in items {
        match std::fs::read_to_string(path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(path.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(path.clone());
            }
        }
    }
    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-flakes --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka project generate-flakes` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        std::process::exit(1);
    }
    println!("{GREEN}{BOLD}generate-flakes --check passed{RESET}");
}

#[cfg(test)]
mod tests {
    use super::*;

    fn minimal_cli() -> CliMeta {
        CliMeta {
            binary_name: "demo".into(),
            description: None,
            package: true,
            runtime_path_deps: vec![],
            check_inputs: vec![],
            shell_completions: false,
            extra_dev_shell_packages: vec![],
        }
    }

    #[test]
    fn rendered_flake_starts_with_generated_header() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn description_defaults_to_project_name() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.contains(r#"description = "demo""#));
    }

    #[test]
    fn description_override_takes_precedence() {
        let cli = CliMeta {
            description: Some("the demo cli".into()),
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains(r#"description = "the demo cli""#));
    }

    #[test]
    fn package_block_omitted_when_package_false() {
        let cli = CliMeta {
            package: false,
            ..minimal_cli()
        };
        let out = render_flake("todoist", &cli);
        // `packages = forEachSupportedSystem` is the top-level
        // packages attribute; `packages = [` also appears inside
        // mkShell, so match on the wider form.
        assert!(!out.contains("packages = forEachSupportedSystem"));
        assert!(!out.contains("apps = forEachSupportedSystem"));
        assert!(out.contains("devShells = forEachSupportedSystem"));
    }

    #[test]
    fn package_implies_apps() {
        let out = render_flake("demo", &minimal_cli());
        assert!(out.contains("packages = forEachSupportedSystem"));
        assert!(out.contains("apps = forEachSupportedSystem"));
    }

    #[test]
    fn shell_completions_pulls_in_install_shell_files() {
        let cli = CliMeta {
            shell_completions: true,
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("installShellFiles"));
        assert!(out.contains("installShellCompletion --cmd demo"));
    }

    #[test]
    fn runtime_path_deps_pull_in_make_wrapper_and_post_fixup() {
        let cli = CliMeta {
            runtime_path_deps: vec!["jujutsu".into(), "git".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("makeWrapper"));
        assert!(out.contains("wrapProgram $out/bin/demo"));
        assert!(out.contains("pkgs.jujutsu"));
        assert!(out.contains("pkgs.git"));
    }

    #[test]
    fn check_inputs_render_as_native_check_inputs() {
        let cli = CliMeta {
            check_inputs: vec!["jujutsu".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("nativeCheckInputs = [ pkgs.jujutsu ];"));
    }

    #[test]
    fn extra_dev_shell_packages_render_into_dev_shell_list() {
        let cli = CliMeta {
            extra_dev_shell_packages: vec!["actionlint".into(), "taplo".into()],
            ..minimal_cli()
        };
        let out = render_flake("demo", &cli);
        assert!(out.contains("pkgs.actionlint"));
        assert!(out.contains("pkgs.taplo"));
    }

    #[test]
    fn document_flake_starts_with_generated_header() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn document_description_defaults_to_project_name() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.contains(r#"description = "resume""#));
    }

    #[test]
    fn document_description_override_takes_precedence() {
        let doc = DocumentMeta {
            description: Some("kolohelios resume".into()),
        };
        let out = render_document_flake("resume", &doc);
        assert!(out.contains(r#"description = "kolohelios resume""#));
    }

    #[test]
    fn document_flake_omits_rust_overlay() {
        // Document devshells don't need a rust toolchain; the
        // overlay input would be dead weight and would surface as a
        // rust-overlay entry in `flake.lock`.
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(!out.contains("rust-overlay"));
        assert!(!out.contains("rustToolchain"));
    }

    #[test]
    fn document_devshell_includes_pandoc_and_tectonic() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.contains("pkgs.pandoc"));
        assert!(out.contains("pkgs.tectonic"));
    }

    #[test]
    fn document_flake_carries_formatter() {
        let out = render_document_flake("resume", &DocumentMeta::default());
        assert!(out.contains("formatter = kolohelios-nix.formatter;"));
    }

    #[test]
    fn infra_flake_starts_with_generated_header() {
        let out = render_infra_flake("cloudflare-dns", &InfraMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn infra_description_defaults_to_project_name() {
        let out = render_infra_flake("cloudflare-dns", &InfraMeta::default());
        assert!(out.contains(r#"description = "cloudflare-dns""#));
    }

    #[test]
    fn infra_description_override_takes_precedence() {
        let infra = InfraMeta {
            description: Some("kolohelios — DNS".into()),
            ..InfraMeta::default()
        };
        let out = render_infra_flake("cloudflare-dns", &infra);
        assert!(out.contains(r#"description = "kolohelios — DNS""#));
    }

    #[test]
    fn infra_dev_shell_packages_appear_with_with_pkgs() {
        let infra = InfraMeta {
            dev_shell_packages: vec!["opentofu".into(), "_1password-cli".into()],
            ..InfraMeta::default()
        };
        let out = render_infra_flake("cf", &infra);
        assert!(out.contains("(workflowPackages pkgs)"));
        assert!(out.contains("(with pkgs; ["));
        assert!(out.contains("opentofu"));
        assert!(out.contains("_1password-cli"));
    }

    #[test]
    fn infra_empty_dev_shell_packages_collapses_to_workflow_packages_only() {
        let out = render_infra_flake("home", &InfraMeta::default());
        assert!(out.contains("packages = workflowPackages pkgs;"));
        assert!(!out.contains("(with pkgs; ["));
    }

    #[test]
    fn infra_extra_inputs_with_follows_render_as_attrset() {
        let mut extra_inputs = BTreeMap::new();
        extra_inputs.insert(
            "home-env".into(),
            ExtraInput {
                url: "https://flakehub.com/f/kolohelios/home/*.tar.gz".into(),
                follows: {
                    let mut m = BTreeMap::new();
                    m.insert("nixpkgs".into(), "nixpkgs".into());
                    m
                },
            },
        );
        let infra = InfraMeta {
            extra_inputs,
            ..InfraMeta::default()
        };
        let out = render_infra_flake("devbox", &infra);
        assert!(out.contains("home-env = {"));
        assert!(out.contains(r#"url = "https://flakehub.com/f/kolohelios/home/*.tar.gz";"#));
        assert!(out.contains(r#"inputs.nixpkgs.follows = "nixpkgs";"#));
        // The input also has to land in the outputs destructure.
        assert!(out.contains("home-env,"));
    }

    #[test]
    fn infra_extra_input_without_follows_collapses_to_one_liner() {
        let mut extra_inputs = BTreeMap::new();
        extra_inputs.insert(
            "claude-hooks".into(),
            ExtraInput {
                url: "https://flakehub.com/f/kolohelios/claude-hooks/*.tar.gz".into(),
                follows: BTreeMap::new(),
            },
        );
        let infra = InfraMeta {
            extra_inputs,
            ..InfraMeta::default()
        };
        let out = render_infra_flake("home", &infra);
        assert!(out.contains(
            r#"claude-hooks.url = "https://flakehub.com/f/kolohelios/claude-hooks/*.tar.gz";"#
        ));
    }

    #[test]
    fn infra_extra_sandbox_lands_after_devshells_and_before_formatter() {
        let infra = InfraMeta {
            extra: Some("      nixosConfigurations.devbox = { hi = 1; };\n".into()),
            ..InfraMeta::default()
        };
        let out = render_infra_flake("devbox", &infra);
        let dev_pos = out
            .find("devShells = forEachSupportedSystem")
            .expect("devShells");
        let extra_pos = out.find("nixosConfigurations.devbox").expect("extra");
        let fmt_pos = out
            .find("formatter = kolohelios-nix.formatter")
            .expect("formatter");
        assert!(dev_pos < extra_pos, "extra should come after devShells");
        assert!(extra_pos < fmt_pos, "extra should come before formatter");
    }

    #[test]
    fn nix_lib_flake_starts_with_generated_header() {
        let out = render_nix_lib_flake("kolohelios-nix", &NixLibMeta::default());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand."));
    }

    #[test]
    fn nix_lib_flake_uses_nixpkgs_only_input() {
        // nix-lib doesn't import kolohelios-nix (would be circular for
        // the canonical case) — only nixpkgs.
        let out = render_nix_lib_flake("kolohelios-nix", &NixLibMeta::default());
        assert!(out.contains(r#"inputs.nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0";"#));
        assert!(!out.contains("kolohelios-nix.url"));
    }

    #[test]
    fn nix_lib_extra_sandbox_lands_inside_outputs() {
        let nl = NixLibMeta {
            extra: Some("    let supportedSystems = []; in { lib = {}; };\n".into()),
            ..NixLibMeta::default()
        };
        let out = render_nix_lib_flake("kolohelios-nix", &nl);
        let outputs_pos = out.find("outputs =").expect("outputs");
        let extra_pos = out.find("supportedSystems = []").expect("extra");
        assert!(outputs_pos < extra_pos);
    }
}
