# Generated by shaka. Do not edit by hand.
# Run `shaka generate` to update; CI fails on drift.

# Run every CI check locally
validate:
    shaka preflight

# Run preflight collecting all failures
validate-all:
    shaka preflight --keep-going
