# Generated by shaka. Do not edit by hand.
# Run `shaka project generate-flakes` to update; CI fails on drift.
{
  description = "kolohelios — cross-platform home environment";

  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
    claude-hooks = {
      url = "https://flakehub.com/f/kolohelios/claude-hooks/*.tar.gz";
      inputs.kolohelios-nix.follows = "kolohelios-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager/release-25.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-darwin = {
      url = "github:LnL7/nix-darwin/nix-darwin-25.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      kolohelios-nix,
      nixpkgs,
      claude-hooks,
      home-manager,
      nix-darwin,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) forEachSupportedSystem workflowPackages;
    in
    {
      devShells = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = pkgs.mkShell {
            packages = workflowPackages pkgs;
          };
        }
      );

      darwinConfigurations.Jons-MacBook-Pro = nix-darwin.lib.darwinSystem {
        system = "aarch64-darwin";
        specialArgs = { inherit claude-hooks; };
        modules = [
          home-manager.darwinModules.home-manager
          ./modules/darwin.nix
        ];
      };

      # NixOS module — imported by `infra/devbox` to apply this user's
      # home-manager profile to the `jon` account on the devbox.
      # `_module.args.claude-hooks` is the NixOS equivalent of the
      # `specialArgs` plumbing above so `infra/devbox` doesn't have
      # to know about it.
      nixosModules.home = {
        imports = [
          home-manager.nixosModules.home-manager
          ./modules/linux.nix
        ];
        _module.args = { inherit claude-hooks; };
      };

      formatter = kolohelios-nix.formatter;
    };
}
