//! Render an IR `Module` into HCL via the `hcl-edit` AST. The raw output
//! has no indentation or blank lines; callers post-process with
//! `tofu fmt` to canonicalize.

use std::path::Path;
use std::process::{Command, Stdio};

use hcl_edit::expr::{
    Array, Expression, FuncArgs, FuncCall, FuncName, Object, ObjectKey, ObjectValue, Traversal,
    TraversalOperator,
};
use hcl_edit::repr::Decorate;
use hcl_edit::structure::{Attribute, Block, Body};
use hcl_edit::Ident;

use super::ir::{DataSource, Expr, Module, NestedBlock, Provider, Resource, Variable};

pub const HEADER: &str = "\
# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.
";

/// Render `module` to a single HCL document with the default header
/// (the `shaka terraform emit` one). The returned string is unformatted
/// — callers post-process with `tofu fmt` to canonicalize.
pub fn render(module: &Module) -> String {
    render_with_header(module, HEADER)
}

/// Render `module` to a single HCL document with a caller-provided
/// header. Use this for callers that emit on behalf of a different
/// shaka subcommand (for example, `shaka deploy generate-tf`) so the
/// emitted files carry the right "DO NOT EDIT" pointer back to the
/// command that produced them.
///
/// The header should end with a single `\n`; an additional blank line
/// is inserted between header and body. For an empty body, only the
/// header is emitted (no trailing blank line).
pub fn render_with_header(module: &Module, header: &str) -> String {
    let body = build_body(module);
    let body_str = format!("{body}");
    if body_str.is_empty() {
        header.to_string()
    } else {
        format!("{header}\n{body_str}")
    }
}

/// Run `tofu fmt` over `s` (via a temp file) and return the canonical
/// output. Useful for callers that already have raw HCL in memory and
/// don't want to spawn the formatter manually each time.
pub fn format_string(s: &str) -> Result<String, String> {
    let tmp = tempfile::Builder::new()
        .prefix("shaka-tf-fmt-")
        .suffix(".tf")
        .tempfile()
        .map_err(|e| format!("could not create tempfile: {e}"))?;
    std::fs::write(tmp.path(), s.as_bytes())
        .map_err(|e| format!("could not write {}: {e}", tmp.path().display()))?;
    tofu_fmt(tmp.path())?;
    std::fs::read_to_string(tmp.path())
        .map_err(|e| format!("could not read {}: {e}", tmp.path().display()))
}

/// Spawn `tofu fmt <path>` (which rewrites the file in place).
/// Public so callers that emit-then-fmt-in-place don't have to duplicate
/// the spawn dance and its error handling.
///
/// `tofu fmt` echoes the formatted file path to stdout on every
/// invocation, which is noise for every caller in this codebase — the
/// emit-side wrapper already announces what it wrote, and the
/// check-side caller is operating on a tempfile the user never sees.
/// stdout is suppressed unconditionally; stderr stays inherited so
/// genuine errors still surface.
pub fn tofu_fmt(path: &Path) -> Result<(), String> {
    let status = Command::new("tofu")
        .arg("fmt")
        .arg(path)
        .stdout(Stdio::null())
        .status();
    match status {
        Ok(s) if s.success() => Ok(()),
        Ok(s) => Err(format!(
            "tofu fmt {} exited with status {s}",
            path.display()
        )),
        Err(e) => Err(format!(
            "could not spawn tofu (is it on PATH? infra devshells provide it): {e}"
        )),
    }
}

fn build_body(module: &Module) -> Body {
    let mut body = Body::new();

    if let Some(tf) = &module.terraform {
        let mut block = Block::new(Ident::new("terraform"));
        if let Some(ver) = &tf.required_version {
            block
                .body
                .push(Attribute::new(Ident::new("required_version"), ver.as_str()));
        }
        if !tf.required_providers.is_empty() {
            let mut req = Block::new(Ident::new("required_providers"));
            for rp in &tf.required_providers {
                let mut obj = Object::new();
                obj.insert(
                    ObjectKey::from(Ident::new("source")),
                    ObjectValue::new(Expression::from(rp.source.clone())),
                );
                obj.insert(
                    ObjectKey::from(Ident::new("version")),
                    ObjectValue::new(Expression::from(rp.version.clone())),
                );
                req.body.push(Attribute::new(
                    Ident::new(&rp.local_name),
                    Expression::from(obj),
                ));
            }
            block.body.push(req);
        }
        body.push(block);
    }

    for provider in &module.providers {
        body.push(build_provider(provider));
    }
    for variable in &module.variables {
        body.push(build_variable(variable));
    }
    for data_source in &module.data_sources {
        body.push(build_data_source(data_source));
    }
    for resource in &module.resources {
        body.push(build_resource(resource));
    }
    for output in &module.outputs {
        let mut block = Block::new(Ident::new("output"));
        block.labels.push(output.name.as_str().into());
        if let Some(d) = &output.description {
            block
                .body
                .push(Attribute::new(Ident::new("description"), d.as_str()));
        }
        block.body.push(Attribute::new(
            Ident::new("value"),
            build_expr(&output.value),
        ));
        if output.sensitive {
            block
                .body
                .push(Attribute::new(Ident::new("sensitive"), true));
        }
        body.push(block);
    }

    body
}

fn build_provider(p: &Provider) -> Block {
    let mut block = Block::new(Ident::new("provider"));
    block.labels.push(p.name.as_str().into());
    for (k, v) in &p.attributes {
        block
            .body
            .push(Attribute::new(Ident::new(k), build_expr(v)));
    }
    block
}

fn build_variable(v: &Variable) -> Block {
    let mut block = Block::new(Ident::new("variable"));
    block.labels.push(v.name.as_str().into());
    if let Some(d) = &v.description {
        block
            .body
            .push(Attribute::new(Ident::new("description"), d.as_str()));
    }
    // `type` is an HCL expression (e.g. `string`, `list(string)`), not a
    // string literal.
    block
        .body
        .push(Attribute::new(Ident::new("type"), build_type_expr(&v.ty)));
    if let Some(def) = &v.default {
        block
            .body
            .push(Attribute::new(Ident::new("default"), build_expr(def)));
    }
    if v.sensitive {
        block
            .body
            .push(Attribute::new(Ident::new("sensitive"), true));
    }
    block
}

fn build_data_source(d: &DataSource) -> Block {
    let mut block = Block::new(Ident::new("data"));
    block.labels.push(d.ty.as_str().into());
    block.labels.push(d.name.as_str().into());
    for (k, v) in &d.attributes {
        block
            .body
            .push(Attribute::new(Ident::new(k), build_expr(v)));
    }
    for nb in &d.blocks {
        block.body.push(build_nested(nb));
    }
    block
}

fn build_resource(r: &Resource) -> Block {
    let mut block = Block::new(Ident::new("resource"));
    block.labels.push(r.ty.as_str().into());
    block.labels.push(r.name.as_str().into());
    for (k, v) in &r.attributes {
        block
            .body
            .push(Attribute::new(Ident::new(k), build_expr(v)));
    }
    for nb in &r.blocks {
        block.body.push(build_nested(nb));
    }
    block
}

fn build_nested(nb: &NestedBlock) -> Block {
    let mut block = Block::new(Ident::new(&nb.ty));
    for (k, v) in &nb.attributes {
        block
            .body
            .push(Attribute::new(Ident::new(k), build_expr(v)));
    }
    for inner in &nb.blocks {
        block.body.push(build_nested(inner));
    }
    block
}

fn build_expr(e: &Expr) -> Expression {
    match e {
        Expr::Bool(b) => Expression::from(*b),
        Expr::Number(n) => {
            if let Some(i) = n.as_i64() {
                Expression::from(i)
            } else if let Some(f) = n.as_f64() {
                Expression::from(f)
            } else {
                Expression::from(n.to_string())
            }
        }
        Expr::String(s) => Expression::from(s.clone()),
        Expr::Ref(traversal_str) => build_traversal(traversal_str),
        Expr::List(items) => {
            let mut arr = Array::new();
            // Heuristic: if any element is an object literal, the list
            // is "complex" and we want a multi-line layout so tofu fmt
            // doesn't collapse the whole structure into one long line.
            // Simple lists (`tags = ["a", "b"]`) stay inline.
            let multiline = items.iter().any(|e| matches!(e, Expr::Object(_)));
            for item in items {
                let mut elem = build_expr(item);
                if multiline {
                    elem.decor_mut().set_prefix("\n");
                }
                arr.push(elem);
            }
            if multiline {
                arr.set_trailing("\n");
                arr.set_trailing_comma(true);
            }
            Expression::from(arr)
        }
        Expr::Object(pairs) => {
            let mut obj = Object::new();
            // Same heuristic as lists: if any value is itself an object
            // (i.e. there's structure to lay out), break across lines.
            // Flat objects like `{ source = "...", version = "..." }`
            // stay inline.
            let multiline = pairs.iter().any(|(_, v)| matches!(v, Expr::Object(_)));
            for (k, v) in pairs {
                let mut key = ObjectKey::from(Ident::new(k));
                if multiline {
                    key.decor_mut().set_prefix("\n");
                }
                obj.insert(key, ObjectValue::new(build_expr(v)));
            }
            if multiline {
                obj.set_trailing("\n");
            }
            Expression::from(obj)
        }
    }
}

fn build_traversal(s: &str) -> Expression {
    let mut parts = s.split('.');
    let head = parts.next().expect("traversal is non-empty");
    let mut t = Traversal::new(Expression::from(Ident::new(head)), Vec::new());
    for p in parts {
        t.operators
            .push(TraversalOperator::GetAttr(Ident::new(p).into()).into());
    }
    Expression::from(t)
}

/// Variable type expressions like `string`, `number`, `bool`,
/// `list(string)`, `map(any)`. We emit identifier expressions as
/// Traversals and `<name>(...)` as FuncCalls. Anything more complex is
/// out of scope for now.
fn build_type_expr(ty: &str) -> Expression {
    let trimmed = ty.trim();
    if let Some(open) = trimmed.find('(') {
        if trimmed.ends_with(')') {
            let name = trimmed[..open].trim();
            let inner = trimmed[open + 1..trimmed.len() - 1].trim();
            if is_ident(name) {
                let mut args = FuncArgs::new();
                args.push(build_type_expr(inner));
                let call = FuncCall::new(FuncName::from(Ident::new(name)), args);
                return Expression::from(call);
            }
        }
    }
    if is_ident(trimmed) {
        return build_traversal(trimmed);
    }
    // Fallback: emit as a string literal so the file at least round-trips
    // through tofu fmt. The schema regex should prevent this in practice.
    Expression::from(trimmed.to_string())
}

fn is_ident(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::terraform::ir::{
        NestedBlock, Output, RequiredProvider, Resource, TerraformBlock, Variable,
    };

    #[test]
    fn render_empty_module_emits_header_only() {
        let s = render(&Module::default());
        assert!(s.starts_with(HEADER));
        // Body after the header is empty (just whitespace).
        let rest = s[HEADER.len()..].trim();
        assert!(rest.is_empty(), "expected empty body, got: {rest:?}");
    }

    #[test]
    fn render_terraform_block_with_required_providers() {
        let m = Module {
            terraform: Some(TerraformBlock {
                required_version: Some(">= 1.0".into()),
                required_providers: vec![RequiredProvider {
                    local_name: "linode".into(),
                    source: "linode/linode".into(),
                    version: "~> 2.0".into(),
                }],
            }),
            ..Default::default()
        };
        let s = render(&m);
        assert!(s.contains("terraform"), "missing terraform block: {s}");
        assert!(s.contains("required_version = \">= 1.0\""), "version: {s}");
        assert!(s.contains("linode/linode"), "source: {s}");
        assert!(s.contains("~> 2.0"), "version: {s}");
    }

    #[test]
    fn render_resource_with_ref_and_list() {
        let m = Module {
            resources: vec![Resource {
                ty: "linode_instance".into(),
                name: "devbox".into(),
                attributes: vec![
                    ("label".into(), Expr::String("devbox".into())),
                    ("region".into(), Expr::Ref("var.region".into())),
                    (
                        "tags".into(),
                        Expr::List(vec![
                            Expr::String("devbox".into()),
                            Expr::String("nixos".into()),
                        ]),
                    ),
                ],
                blocks: vec![],
            }],
            ..Default::default()
        };
        let s = render(&m);
        assert!(s.contains("resource \"linode_instance\" \"devbox\""));
        // Traversal must be bare, not quoted.
        assert!(
            s.contains("region = var.region"),
            "expected bare traversal, got: {s}"
        );
        assert!(!s.contains("\"var.region\""), "ref must not be quoted: {s}");
        assert!(s.contains("tags = [\"devbox\", \"nixos\"]"));
    }

    #[test]
    fn render_resource_with_nested_block() {
        let m = Module {
            resources: vec![Resource {
                ty: "linode_volume".into(),
                name: "persist".into(),
                attributes: vec![],
                blocks: vec![NestedBlock {
                    ty: "lifecycle".into(),
                    attributes: vec![("prevent_destroy".into(), Expr::Bool(true))],
                    blocks: vec![],
                }],
            }],
            ..Default::default()
        };
        let s = render(&m);
        assert!(s.contains("lifecycle"));
        assert!(s.contains("prevent_destroy = true"));
    }

    #[test]
    fn render_variable_with_string_type() {
        let m = Module {
            variables: vec![Variable {
                name: "region".into(),
                description: Some("Linode region".into()),
                ty: "string".into(),
                default: Some(Expr::String("us-ord".into())),
                sensitive: false,
            }],
            ..Default::default()
        };
        let s = render(&m);
        assert!(s.contains("variable \"region\""));
        assert!(s.contains("description = \"Linode region\""));
        // Type must be bare identifier, not quoted string.
        assert!(s.contains("type = string"), "expected bare type, got: {s}");
        assert!(!s.contains("type = \"string\""));
        assert!(s.contains("default = \"us-ord\""));
    }

    #[test]
    fn render_variable_with_list_of_string_type() {
        let m = Module {
            variables: vec![Variable {
                name: "authorized_keys".into(),
                description: Some("SSH keys".into()),
                ty: "list(string)".into(),
                default: Some(Expr::List(vec![])),
                sensitive: false,
            }],
            ..Default::default()
        };
        let s = render(&m);
        assert!(
            s.contains("type = list(string)"),
            "expected function call type, got: {s}"
        );
    }

    #[test]
    fn render_variable_with_sensitive_emits_true() {
        let m = Module {
            variables: vec![Variable {
                name: "tok".into(),
                description: None,
                ty: "string".into(),
                default: None,
                sensitive: true,
            }],
            ..Default::default()
        };
        let s = render(&m);
        assert!(s.contains("sensitive = true"));
    }

    #[test]
    fn render_data_source_uses_data_keyword() {
        let m = Module {
            data_sources: vec![crate::terraform::ir::DataSource {
                ty: "cloudflare_zone".into(),
                name: "kolohelios_com".into(),
                attributes: vec![(
                    "filter".into(),
                    Expr::Object(vec![("name".into(), Expr::String("kolohelios.com".into()))]),
                )],
                blocks: vec![],
            }],
            ..Default::default()
        };
        let s = render(&m);
        assert!(
            s.contains("data \"cloudflare_zone\" \"kolohelios_com\""),
            "missing data block: {s}"
        );
        // Must NOT use the `resource` keyword.
        assert!(!s.contains("resource \"cloudflare_zone\""), "got: {s}");
    }

    #[test]
    fn render_with_header_uses_provided_header() {
        let m = Module::default();
        let s = render_with_header(&m, "# custom header\n");
        assert!(s.starts_with("# custom header\n"), "got: {s}");
        // Must NOT include the default header.
        assert!(!s.contains("shaka terraform emit"), "got: {s}");
    }

    #[test]
    fn render_with_header_emits_body_for_non_empty_module() {
        let m = Module {
            data_sources: vec![crate::terraform::ir::DataSource {
                ty: "x".into(),
                name: "y".into(),
                attributes: vec![],
                blocks: vec![],
            }],
            ..Default::default()
        };
        let s = render_with_header(&m, "# custom\n");
        assert!(s.starts_with("# custom\n\n"), "got: {s}");
        assert!(s.contains("data \"x\" \"y\""), "got: {s}");
    }

    #[test]
    fn render_output_with_sensitive_and_value() {
        let m = Module {
            outputs: vec![Output {
                name: "secret".into(),
                description: Some("a token".into()),
                value: Expr::Ref("var.tok".into()),
                sensitive: true,
            }],
            ..Default::default()
        };
        let s = render(&m);
        assert!(s.contains("output \"secret\""));
        assert!(s.contains("value = var.tok"));
        assert!(s.contains("sensitive = true"));
    }

    #[test]
    fn build_traversal_renders_multi_segment_as_dotted() {
        let e = build_traversal("linode_instance.devbox.id");
        let s = format!("{e}");
        assert_eq!(s, "linode_instance.devbox.id");
    }

    #[test]
    fn build_type_expr_handles_nested_list_of_map() {
        // Sanity-check the recursion handles list(map(string)).
        let e = build_type_expr("list(map(string))");
        let s = format!("{e}");
        assert_eq!(s, "list(map(string))");
    }
}
