[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name    = "aof"
publish = false
version = "0.1.0"

[lib]
name = "aof"
path = "src/lib.rs"

[[bin]]
name = "aof"
path = "src/main.rs"

[dependencies]
base64        = "0.22"
clap          = { version = "4", features = ["derive"] }
clap_complete = "4"
image         = { version = "0.25", default-features = false, features = ["png"] }
resvg         = "0.45"
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"
snafu         = "0.9"

[lints.clippy]
mod_module_files = "deny"
