# Generated by shaka. Do not edit by hand.
# Run `shaka project generate-flakes` to update; CI fails on drift.
{
  description = "aof";

  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.stable."1.95.0".minimal.override {
          extensions = [
            "clippy"
            "rustfmt"
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
        };

      rustPlatform =
        pkgs:
        pkgs.makeRustPlatform {
          cargo = rustToolchain pkgs;
          rustc = rustToolchain pkgs;
        };
    in
    {
      packages = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = (rustPlatform pkgs).buildRustPackage {
            pname = "aof";
            version = "0.1.0";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
            nativeBuildInputs = [
              pkgs.makeWrapper
              pkgs.installShellFiles
            ];
            postInstall = ''
              installShellCompletion --cmd aof \
                --bash <($out/bin/aof completions bash) \
                --fish <($out/bin/aof completions fish) \
                --zsh  <($out/bin/aof completions zsh)
            '';
            postFixup = ''
              wrapProgram $out/bin/aof \
                --prefix PATH : ${
                  pkgs.lib.makeBinPath [
                    pkgs.cue
                    pkgs.d2
                  ]
                }
            '';
          };
        }
      );

      apps = forEachSupportedSystem (
        { system, ... }:
        {
          default = {
            type = "app";
            program = "${self.packages.${system}.default}/bin/aof";
          };
        }
      );

      devShells = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = pkgs.mkShell {
            packages = [
              (rustToolchain pkgs)
              pkgs.d2
            ]
            ++ (workflowPackages pkgs)
            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;
            shellHook = ''
              if command -v aof &>/dev/null; then
                _completions_dir="''${XDG_CACHE_HOME:-$HOME/.cache}/kolohelios-completions/aof"
                mkdir -p "$_completions_dir"
                aof completions zsh > "$_completions_dir/_aof" 2>/dev/null
                FPATH="$_completions_dir:$FPATH"
                unset _completions_dir
              fi
            '';
          };
        }
      );

      formatter = kolohelios-nix.formatter;
    };
}
