package project

#Project & {
	name: "kolohelios-portfolio"
	kind: "rust-worker"
	worker: {
		// tailwindcss compiles the site's CSS; cue exports
		// data/work-history.cue to JSON the templates iterate over —
		// both invoked from wrangler.toml's [build] step.
		extraDevShellPackages: ["tailwindcss", "cue"]
	}

	// Source of truth for apps/kolohelios-portfolio/wrangler.toml, which
	// `shaka deploy generate-wrangler` emits and `shaka preflight`
	// drift-checks. Never hand-edit the generated wrangler.toml — change
	// this block and regenerate.
	wrangler: {
		main:               "build/worker/shim.mjs"
		compatibility_date: "2026-05-01"

		// Workers Static Assets: CF serves files from `./dist/` at the edge,
		// bypassing the Worker for matched paths. Cache rules (managed by
		// `infra/cloudflare-deploy`) apply to these responses, so the
		// catch-all HTML rule from #190 engages. `dist/` is generated by
		// `cargo run --features build-site --bin build-site` from
		// `templates/`, `data/`, and `styles/`; the result is committed and
		// CI's `build-check` re-runs the pipeline to fail on drift. Unmatched
		// paths fall through to the Worker (`main`): `/api/subscribe` proxies
		// the contact/newsletter forms to Kit, everything else 404s.
		//
		// `worker-build` produces the shim + wasm module upstream of
		// `wrangler deploy` — no `[build]` block. See #403/#423: running
		// `worker-build` inside a wrangler-spawned subprocess lets
		// `wasm-pack`'s target probe resolve the wrong rustc; pulling the
		// build out keeps `$PATH` under our control.
		assets: {
			directory: "./dist"
		}

		// Non-secret runtime config the worker reads via `env.var(...)`. Kit
		// form ids (safe to commit — embedded in public Kit forms), one per
		// submission `kind`; see README "Kit setup".
		vars: {
			KIT_FORM_ID_CONTACT:    "9525720"
			KIT_FORM_ID_NEWSLETTER: "9525721"
		}

		// `KIT_API_KEY` is a secret, set out-of-band via
		// `wrangler secret put KIT_API_KEY` — never committed.
		secrets: ["KIT_API_KEY"]

		// Cloudflare native rate limiting. `handle_subscribe` calls this
		// binding per client IP; over the limit returns 429 before any Kit
		// call. `namespace_id` is an arbitrary unique id; `period` must be 10
		// or 60.
		unsafe_bindings: [
			{
				name:         "SUBSCRIBE_RATE_LIMITER"
				type:         "ratelimit"
				namespace_id: "1001"
				simple: {
					limit:  5
					period: 60
				}
			},
		]
	}
	serving: [
		{
			via: "cloudflare-worker"
			hostnames: ["kolohelios.com"]
		},
	]
	deploy: {
		target:       "cloudflare-worker"
		customDomain: "kolohelios.com"
		zone:         "kolohelios.com"
		cache: {
			bypassPaths: ["/api/"]
		}
	}
	ci: {
		deploy: {
			reusableWorkflow:    "./.github/workflows/cf-deploy.yml"
			previewScriptPrefix: "kolohelios-portfolio"
		}
	}
}
