//! Generator for `infra/cloudflare-deploy/terraform/generated/*.tf`.
//!
//! Walks every project, reads any `deploy:` block from its
//! `project.cue`, and emits one `_zones.tf` (aggregating data sources
//! for each unique zone referenced) plus one `<project>.tf` per app
//! with a deploy block. Files carry a "do not edit by hand" header so
//! the source of truth — the `project.cue` deploy block — is the only
//! input a maintainer ever changes.
//!
//! `--check` mode compares the on-disk contents against what would be
//! written, including detecting orphaned generated files; it exits
//! non-zero on any drift. Wired into `shaka preflight` so committed TF
//! and committed CUE cannot drift apart.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

use crate::project::schema_check::{discover, write_schema as project_schema_path};
use crate::term::{BOLD, DIM, GREEN, RED, RESET, YELLOW};
use crate::terraform::emit;
use crate::terraform::ir::{DataSource, Expr, Module, Resource, Variable};

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka deploy generate-tf` to update; CI fails on drift.\n# The source of truth is each project's `deploy:` block in project.cue.\n";

const OUTPUT_DIR: &str = "infra/cloudflare-deploy/terraform/generated";

/// Subset of a project's CUE export — just what the generator needs.
/// `deploy` is optional; projects without one are skipped silently.
#[derive(Deserialize)]
struct ProjectExport {
    name: String,
    #[serde(default)]
    deploy: Option<Deploy>,
}

/// Schema-side `#Deploy`. The `target` discriminator is closed by the
/// schema, so any value reaching this struct has already been validated
/// against the supported set.
#[derive(Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "target", rename_all = "kebab-case")]
enum Deploy {
    CloudflareWorker {
        #[serde(rename = "customDomain")]
        custom_domain: String,
        zone: String,
        #[serde(default)]
        cache: Option<CacheRules>,
    },
}

/// Schema-side `#CacheRules`. The generator turns this into a
/// `cloudflare_ruleset` resource alongside the custom-domain
/// attachment. Rule shape (TTLs, static-asset extensions, mutating-
/// method bypass) is opinionated and lives in the generator constants
/// below; only knobs that diverge between consumers belong in the
/// schema.
#[derive(Deserialize, Debug, Clone, PartialEq, Eq)]
struct CacheRules {
    #[serde(rename = "bypassPaths")]
    bypass_paths: Vec<String>,
}

/// File extensions the generator treats as long-cache static assets.
/// Fingerprinted URLs are assumed; each match gets 1-year edge +
/// browser TTLs.
const STATIC_ASSET_EXTENSIONS: &[&str] = &[
    "js", "css", "wasm", "woff2", "png", "jpg", "jpeg", "svg", "webp", "avif",
];

/// 1 hour. Edge TTL for HTML / catch-all responses.
const HTML_EDGE_TTL_SECONDS: u32 = 3_600;

/// 1 year. Edge + browser TTL for fingerprinted static assets.
const STATIC_ASSET_TTL_SECONDS: u32 = 31_536_000;

pub fn run(check: bool) {
    let root = Path::new(".");
    match run_at(root, check) {
        Ok(()) => {}
        Err(e) => {
            eprintln!("{RED}{BOLD}error:{RESET} {e}");
            std::process::exit(1);
        }
    }
}

fn run_at(root: &Path, check: bool) -> Result<(), String> {
    let schema_path =
        project_schema_path().map_err(|e| format!("could not resolve schema: {e}"))?;
    let deploys = collect_deploys(root, &schema_path)?;
    let outputs = render_all(&deploys)?;

    if check {
        check_drift(root, &outputs)
    } else {
        write_all(root, &outputs)
    }
}

/// Walk every project, read its CUE export, and return only those
/// projects that declare a `deploy:` block, sorted by project name.
fn collect_deploys(root: &Path, schema_path: &Path) -> Result<Vec<(String, Deploy)>, String> {
    let mut out = Vec::new();
    for project_dir in discover(root) {
        let project_file = project_dir.join("project.cue");
        if !project_file.exists() {
            continue;
        }
        let export = export_project(schema_path, &project_file)?;
        if let Some(deploy) = export.deploy {
            out.push((export.name, deploy));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

/// (relative path, content) pairs. Always includes `variables.tf` plus
/// `_zones.tf` when any deploy exists; one `<project>.tf` per app with
/// a deploy block. `variables.tf` declares the parent variables the
/// generated resources read (passed through by the `module "generated"`
/// block in the consuming project's `main.tf`).
fn render_all(deploys: &[(String, Deploy)]) -> Result<Vec<(PathBuf, String)>, String> {
    let mut out = Vec::new();
    if deploys.is_empty() {
        return Ok(out);
    }

    out.push((PathBuf::from("variables.tf"), render_variables()?));
    out.push((PathBuf::from("_zones.tf"), render_zones(deploys)?));
    for (name, deploy) in deploys {
        out.push((
            PathBuf::from(format!("{name}.tf")),
            render_project(name, deploy)?,
        ));
    }
    Ok(out)
}

fn render_variables() -> Result<String, String> {
    let module = Module {
        variables: vec![Variable {
            name: "cloudflare_account_id".into(),
            description: Some(
                "Cloudflare account ID; passed through from the parent module.".into(),
            ),
            ty: "string".into(),
            default: None,
            sensitive: false,
        }],
        ..Default::default()
    };
    emit::format_string(&emit::render_with_header(&module, HEADER))
}

fn render_zones(deploys: &[(String, Deploy)]) -> Result<String, String> {
    let mut zones: BTreeMap<String, String> = BTreeMap::new();
    for (_, deploy) in deploys {
        match deploy {
            Deploy::CloudflareWorker { zone, .. } => {
                zones.insert(tf_ident(zone), zone.clone());
            }
        }
    }
    let module = Module {
        data_sources: zones
            .into_iter()
            .map(|(ident, name)| DataSource {
                ty: "cloudflare_zone".into(),
                name: ident,
                attributes: vec![(
                    "filter".into(),
                    Expr::Object(vec![("name".into(), Expr::String(name))]),
                )],
                blocks: vec![],
            })
            .collect(),
        ..Default::default()
    };
    emit::format_string(&emit::render_with_header(&module, HEADER))
}

fn render_project(name: &str, deploy: &Deploy) -> Result<String, String> {
    let mut module = Module::default();
    match deploy {
        Deploy::CloudflareWorker {
            custom_domain,
            zone,
            cache,
        } => {
            let resource_ident = tf_ident(name);
            let zone_ident = tf_ident(zone);
            module.resources.push(Resource {
                ty: "cloudflare_workers_custom_domain".into(),
                name: resource_ident.clone(),
                attributes: vec![
                    (
                        "account_id".into(),
                        Expr::Ref("var.cloudflare_account_id".into()),
                    ),
                    (
                        "zone_id".into(),
                        Expr::Ref(format!("data.cloudflare_zone.{zone_ident}.zone_id")),
                    ),
                    ("hostname".into(), Expr::String(custom_domain.clone())),
                    ("service".into(), Expr::String(name.into())),
                ],
                blocks: vec![],
            });
            if let Some(rules) = cache {
                module.resources.push(build_cache_ruleset(
                    name,
                    &resource_ident,
                    &zone_ident,
                    rules,
                ));
            }
        }
    }
    emit::format_string(&emit::render_with_header(&module, HEADER))
}

/// Build a zone-level `cloudflare_ruleset` for the
/// `http_request_cache_settings` phase. Three rules, evaluated in
/// order: bypass (mutating methods + configured paths), static-asset
/// long cache, catch-all HTML 1h edge.
///
/// Cloudflare's expression syntax lives inside HCL string literals;
/// the IR emitter handles quote escaping when serializing.
fn build_cache_ruleset(
    project_name: &str,
    project_ident: &str,
    zone_ident: &str,
    rules: &CacheRules,
) -> Resource {
    let static_expr = STATIC_ASSET_EXTENSIONS
        .iter()
        .map(|ext| format!(r#"ends_with(lower(http.request.uri.path), ".{ext}")"#))
        .collect::<Vec<_>>()
        .join(" or ");
    let static_expr = format!("({static_expr})");

    let mut bypass_terms =
        vec![r#"http.request.method in {"POST" "PUT" "DELETE" "PATCH"}"#.to_string()];
    for path in &rules.bypass_paths {
        bypass_terms.push(format!(r#"starts_with(http.request.uri.path, "{path}")"#));
    }
    let bypass_expr = format!("({})", bypass_terms.join(" or "));

    Resource {
        ty: "cloudflare_ruleset".into(),
        name: format!("{project_ident}_cache"),
        attributes: vec![
            (
                "zone_id".into(),
                Expr::Ref(format!("data.cloudflare_zone.{zone_ident}.zone_id")),
            ),
            (
                "name".into(),
                Expr::String(format!("{project_name} cache rules")),
            ),
            (
                "description".into(),
                Expr::String(format!(
                    "Cache rules generated by shaka deploy generate-tf for {project_name}"
                )),
            ),
            ("kind".into(), Expr::String("zone".into())),
            (
                "phase".into(),
                Expr::String("http_request_cache_settings".into()),
            ),
            (
                "rules".into(),
                Expr::List(vec![
                    Expr::Object(vec![
                        (
                            "description".into(),
                            Expr::String(
                                "Bypass cache for mutating methods and configured paths".into(),
                            ),
                        ),
                        ("expression".into(), Expr::String(bypass_expr)),
                        ("action".into(), Expr::String("set_cache_settings".into())),
                        (
                            "action_parameters".into(),
                            Expr::Object(vec![("cache".into(), Expr::Bool(false))]),
                        ),
                    ]),
                    Expr::Object(vec![
                        (
                            "description".into(),
                            Expr::String("Cache fingerprinted static assets long".into()),
                        ),
                        ("expression".into(), Expr::String(static_expr)),
                        ("action".into(), Expr::String("set_cache_settings".into())),
                        (
                            "action_parameters".into(),
                            Expr::Object(vec![
                                ("cache".into(), Expr::Bool(true)),
                                (
                                    "edge_ttl".into(),
                                    Expr::Object(vec![
                                        ("mode".into(), Expr::String("override_origin".into())),
                                        ("default".into(), number(STATIC_ASSET_TTL_SECONDS)),
                                    ]),
                                ),
                                (
                                    "browser_ttl".into(),
                                    Expr::Object(vec![
                                        ("mode".into(), Expr::String("override_origin".into())),
                                        ("default".into(), number(STATIC_ASSET_TTL_SECONDS)),
                                    ]),
                                ),
                            ]),
                        ),
                    ]),
                    Expr::Object(vec![
                        (
                            "description".into(),
                            Expr::String(format!(
                                "Cache HTML (catch-all) at the edge for {HTML_EDGE_TTL_SECONDS}s"
                            )),
                        ),
                        ("expression".into(), Expr::String("true".into())),
                        ("action".into(), Expr::String("set_cache_settings".into())),
                        (
                            "action_parameters".into(),
                            Expr::Object(vec![
                                ("cache".into(), Expr::Bool(true)),
                                (
                                    "edge_ttl".into(),
                                    Expr::Object(vec![
                                        ("mode".into(), Expr::String("override_origin".into())),
                                        ("default".into(), number(HTML_EDGE_TTL_SECONDS)),
                                    ]),
                                ),
                            ]),
                        ),
                    ]),
                ]),
            ),
        ],
        blocks: vec![],
    }
}

fn number(n: u32) -> Expr {
    Expr::Number(serde_json::Number::from(n))
}

/// Map a domain or project name to a Terraform-safe identifier.
/// Dots and hyphens both become underscores.
fn tf_ident(s: &str) -> String {
    s.replace(['.', '-'], "_")
}

fn write_all(root: &Path, outputs: &[(PathBuf, String)]) -> Result<(), String> {
    let dir = root.join(OUTPUT_DIR);
    std::fs::create_dir_all(&dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;

    let expected: std::collections::HashSet<_> = outputs.iter().map(|(p, _)| p.clone()).collect();
    remove_orphans(&dir, &expected)?;

    if outputs.is_empty() {
        println!("{YELLOW}{BOLD}generate-tf:{RESET} no deploy blocks found; nothing to emit");
        return Ok(());
    }

    for (rel, content) in outputs {
        let path = dir.join(rel);
        std::fs::write(&path, content).map_err(|e| format!("writing {}: {e}", path.display()))?;
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-tf:{RESET} wrote {} file(s) under {}",
        outputs.len(),
        dir.display()
    );
    Ok(())
}

fn check_drift(root: &Path, outputs: &[(PathBuf, String)]) -> Result<(), String> {
    let dir = root.join(OUTPUT_DIR);
    let mut drift: Vec<PathBuf> = Vec::new();

    let expected: std::collections::HashSet<_> = outputs.iter().map(|(p, _)| p.clone()).collect();
    if dir.is_dir() {
        for entry in std::fs::read_dir(&dir)
            .map_err(|e| format!("reading {}: {e}", dir.display()))?
            .flatten()
        {
            let path = entry.path();
            let Some(name) = path.file_name() else {
                continue;
            };
            if name == ".gitkeep" {
                continue;
            }
            let rel = PathBuf::from(name);
            if !expected.contains(&rel) {
                println!("  {RED}{BOLD}ORPHAN{RESET}  {}", path.display());
                drift.push(rel);
            }
        }
    }

    for (rel, expected) in outputs {
        let path = dir.join(rel);
        match std::fs::read_to_string(&path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(rel.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(rel.clone());
            }
        }
    }

    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-tf --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka deploy generate-tf` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        return Err("drift".into());
    }
    println!("{GREEN}{BOLD}generate-tf --check passed{RESET}");
    Ok(())
}

fn remove_orphans(dir: &Path, expected: &std::collections::HashSet<PathBuf>) -> Result<(), String> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir)
        .map_err(|e| format!("reading {}: {e}", dir.display()))?
        .flatten()
    {
        let path = entry.path();
        let Some(name) = path.file_name() else {
            continue;
        };
        if name == ".gitkeep" {
            continue;
        }
        let rel = PathBuf::from(name);
        if !expected.contains(&rel) {
            std::fs::remove_file(&path)
                .map_err(|e| format!("removing orphan {}: {e}", path.display()))?;
            println!(
                "  {YELLOW}{BOLD}removed{RESET}  {} (orphan)",
                path.display()
            );
        }
    }
    Ok(())
}

fn export_project(schema_path: &Path, project_file: &Path) -> Result<ProjectExport, String> {
    let output = Command::new("cue")
        .arg("export")
        .arg(schema_path)
        .arg(project_file)
        .output()
        .map_err(|e| format!("failed to spawn cue: {e}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!(
            "cue export failed for {}: {stderr}",
            project_file.display()
        ));
    }
    serde_json::from_slice::<ProjectExport>(&output.stdout).map_err(|e| {
        format!(
            "could not parse cue export of {}: {e}",
            project_file.display()
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tf_ident_replaces_dots_and_hyphens() {
        assert_eq!(tf_ident("kolohelios.com"), "kolohelios_com");
        assert_eq!(tf_ident("kolohelios-portfolio"), "kolohelios_portfolio");
        assert_eq!(tf_ident("a.b-c.d"), "a_b_c_d");
    }

    #[test]
    fn render_all_is_empty_when_no_deploys() {
        assert!(render_all(&[]).unwrap().is_empty());
    }

    fn worker(custom_domain: &str, zone: &str) -> Deploy {
        Deploy::CloudflareWorker {
            custom_domain: custom_domain.into(),
            zone: zone.into(),
            cache: None,
        }
    }

    fn worker_with_cache(custom_domain: &str, zone: &str, bypass_paths: &[&str]) -> Deploy {
        Deploy::CloudflareWorker {
            custom_domain: custom_domain.into(),
            zone: zone.into(),
            cache: Some(CacheRules {
                bypass_paths: bypass_paths.iter().map(|s| (*s).into()).collect(),
            }),
        }
    }

    #[test]
    fn render_all_emits_variables_zones_plus_one_file_per_project() {
        let deploys = vec![(
            "kolohelios-portfolio".into(),
            worker("kolohelios.com", "kolohelios.com"),
        )];
        let out = render_all(&deploys).unwrap();
        let names: Vec<_> = out.iter().map(|(p, _)| p.display().to_string()).collect();
        assert_eq!(
            names,
            vec!["variables.tf", "_zones.tf", "kolohelios-portfolio.tf"]
        );
    }

    #[test]
    fn render_zones_dedups_by_zone_name() {
        let deploys = vec![
            ("app-a".into(), worker("a.example.com", "example.com")),
            ("app-b".into(), worker("b.example.com", "example.com")),
        ];
        let zones = render_zones(&deploys).unwrap();
        assert_eq!(zones.matches("data \"cloudflare_zone\"").count(), 1);
    }

    #[test]
    fn render_zones_one_per_unique_zone() {
        let deploys = vec![
            ("app-a".into(), worker("a.example.com", "example.com")),
            ("app-b".into(), worker("kolohelios.com", "kolohelios.com")),
        ];
        let zones = render_zones(&deploys).unwrap();
        assert_eq!(zones.matches("data \"cloudflare_zone\"").count(), 2);
    }

    #[test]
    fn render_project_omits_ruleset_when_cache_absent() {
        let tf = render_project(
            "kolohelios-portfolio",
            &worker("kolohelios.com", "kolohelios.com"),
        )
        .unwrap();
        assert!(tf.contains("cloudflare_workers_custom_domain"));
        assert!(!tf.contains("cloudflare_ruleset"));
    }

    #[test]
    fn render_project_emits_ruleset_when_cache_present() {
        let tf = render_project(
            "kolohelios-portfolio",
            &worker_with_cache("kolohelios.com", "kolohelios.com", &["/api/"]),
        )
        .unwrap();
        assert!(tf.contains("cloudflare_workers_custom_domain"));
        assert!(tf.contains(r#"resource "cloudflare_ruleset" "kolohelios_portfolio_cache""#));
        // tofu fmt may align attributes inside the resource; the
        // assertion just checks the literal substring is present.
        assert!(tf.contains("\"http_request_cache_settings\""));
    }

    #[test]
    fn cache_ruleset_bypass_expression_escapes_inner_quotes() {
        let tf = render_project(
            "p",
            &worker_with_cache("p.example.com", "example.com", &["/api/"]),
        )
        .unwrap();
        // CF method-set syntax embedded in an HCL string literal must
        // escape its inner quotes; otherwise the .tf is unparsable.
        // hcl-edit handles the escaping when serializing the string.
        assert!(tf.contains(r#"\"POST\" \"PUT\" \"DELETE\" \"PATCH\""#));
        assert!(tf.contains(r#"starts_with(http.request.uri.path, \"/api/\")"#));
    }

    #[test]
    fn cache_ruleset_bypass_drops_path_clause_when_list_empty() {
        let tf =
            render_project("p", &worker_with_cache("p.example.com", "example.com", &[])).unwrap();
        // Mutating-method bypass is unconditional; path clause only
        // shows up when bypass_paths is non-empty.
        assert!(tf.contains(r#"\"POST\" \"PUT\" \"DELETE\" \"PATCH\""#));
        assert!(!tf.contains("starts_with(http.request.uri.path"));
    }

    #[test]
    fn cache_ruleset_static_assets_include_wasm_and_woff2() {
        let tf =
            render_project("p", &worker_with_cache("p.example.com", "example.com", &[])).unwrap();
        assert!(tf.contains(r#"ends_with(lower(http.request.uri.path), \".wasm\")"#));
        assert!(tf.contains(r#"ends_with(lower(http.request.uri.path), \".woff2\")"#));
    }
}
