//! Generator for each worker project's `wrangler.toml`.
//!
//! Walks every project, reads any `wrangler:` block (the `#Wrangler`
//! schema) from its `project.cue`, and writes a `wrangler.toml` next
//! to it. The file carries a "do not edit by hand" header so the
//! source of truth — the `project.cue` `wrangler:` block — is the only
//! input a maintainer ever changes.
//!
//! `wrangler:` is distinct from the `worker:` devShell block that
//! `generate-flakes` consumes: this block is everything wrangler itself
//! needs to build and run the worker (`main`, `compatibility_date`,
//! build/assets/cron/vars/secrets).
//!
//! Two things differ from `generate-tf`. Output is co-located with
//! each project (`<slot>/<name>/wrangler.toml`) rather than in a
//! central directory. And only projects that *declare* a `wrangler:`
//! block are managed: a project without one is left untouched, so a
//! hand-maintained `wrangler.toml` (the state before a project adopts
//! the `wrangler:` block) is never clobbered or flagged as an orphan.
//!
//! `--check` mode compares the on-disk contents against what would be
//! written and exits non-zero on drift. Wired into `shaka preflight`
//! so committed wrangler config and committed CUE cannot drift apart.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::project::schema_check::{cue_project, discover, project_schema_path};
use crate::term::{BOLD, DIM, GREEN, RED, RESET, YELLOW};

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka deploy generate-wrangler` to update; CI fails on drift.\n# The source of truth is each project's `wrangler:` block in project.cue.\n";

const WRANGLER_FILE: &str = "wrangler.toml";

/// Subset of a project's CUE export — just what the generator needs.
/// `wrangler` is optional; projects without one are skipped silently.
#[derive(Deserialize)]
struct ProjectExport {
    name: String,
    #[serde(default)]
    wrangler: Option<Wrangler>,
}

/// Schema-side `#Wrangler`. Every field past `main`/`compatibility_date`
/// is optional, matching the two real shapes in the repo: pollen-alert
/// (build + cron + vars + secrets) and the portfolio (assets only).
#[derive(Deserialize, Debug, Clone, PartialEq, Eq)]
struct Wrangler {
    main: String,
    compatibility_date: String,
    #[serde(default)]
    build: Option<Build>,
    #[serde(default)]
    assets: Option<Assets>,
    #[serde(default)]
    cron: Option<Vec<String>>,
    #[serde(default)]
    vars: Option<BTreeMap<String, String>>,
    #[serde(default)]
    secrets: Option<Vec<String>>,
}

#[derive(Deserialize, Debug, Clone, PartialEq, Eq)]
struct Build {
    command: String,
}

#[derive(Deserialize, Debug, Clone, PartialEq, Eq)]
struct Assets {
    directory: String,
}

pub fn run(check: bool) {
    let root = Path::new(".");
    match run_at(root, check) {
        Ok(()) => {}
        Err(e) => {
            eprintln!("{RED}{BOLD}error:{RESET} {e}");
            std::process::exit(1);
        }
    }
}

fn run_at(root: &Path, check: bool) -> Result<(), String> {
    project_schema_path().map_err(|e| format!("could not resolve schema: {e}"))?;
    let wranglers = collect_wranglers(root)?;
    let outputs = render_all(&wranglers);

    if check {
        check_drift(&outputs)
    } else {
        write_all(&outputs)
    }
}

/// Walk every project, read its CUE export, and return only those that
/// declare a `wrangler:` block, paired with the directory holding their
/// `project.cue`, sorted by that path.
fn collect_wranglers(root: &Path) -> Result<Vec<(PathBuf, String, Wrangler)>, String> {
    let mut out = Vec::new();
    for project_dir in discover(root) {
        let project_file = project_dir.join("project.cue");
        if !project_file.exists() {
            continue;
        }
        let export = export_project(&project_file)?;
        if let Some(wrangler) = export.wrangler {
            out.push((project_dir, export.name, wrangler));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

/// (wrangler.toml path, content) pairs — one per project with a
/// `wrangler:` block, written next to that project's `project.cue`.
fn render_all(wranglers: &[(PathBuf, String, Wrangler)]) -> Vec<(PathBuf, String)> {
    wranglers
        .iter()
        .map(|(dir, name, wrangler)| (dir.join(WRANGLER_FILE), render_wrangler(name, wrangler)))
        .collect()
}

/// Render one `wrangler.toml`. Deterministic: fixed table order, vars
/// keyed by a `BTreeMap` so they emit sorted, secret names rendered as
/// a trailing comment (declared, never valued — wrangler reads them
/// from `wrangler secret put`, not this file).
fn render_wrangler(name: &str, wrangler: &Wrangler) -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');
    s.push_str(&format!("name = {}\n", toml_str(name)));
    s.push_str(&format!("main = {}\n", toml_str(&wrangler.main)));
    s.push_str(&format!(
        "compatibility_date = {}\n",
        toml_str(&wrangler.compatibility_date)
    ));

    if let Some(build) = &wrangler.build {
        s.push_str("\n[build]\n");
        s.push_str(&format!("command = {}\n", toml_str(&build.command)));
    }

    if let Some(cron) = wrangler.cron.as_ref().filter(|c| !c.is_empty()) {
        s.push_str("\n[triggers]\n");
        let items: Vec<String> = cron.iter().map(|c| toml_str(c)).collect();
        s.push_str(&format!("crons = [{}]\n", items.join(", ")));
    }

    if let Some(assets) = &wrangler.assets {
        s.push_str("\n[assets]\n");
        s.push_str(&format!("directory = {}\n", toml_str(&assets.directory)));
    }

    if let Some(vars) = wrangler.vars.as_ref().filter(|v| !v.is_empty()) {
        s.push_str("\n[vars]\n");
        for (key, value) in vars {
            s.push_str(&format!("{key} = {}\n", toml_str(value)));
        }
    }

    if let Some(secrets) = wrangler.secrets.as_ref().filter(|s| !s.is_empty()) {
        s.push_str("\n# Secrets (set out-of-band via `wrangler secret put <NAME>`):\n");
        for secret in secrets {
            s.push_str(&format!("#   {secret}\n"));
        }
    }

    s
}

/// Serialize a string as a TOML basic string, escaping the characters
/// the spec requires inside double quotes.
fn toml_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn write_all(outputs: &[(PathBuf, String)]) -> Result<(), String> {
    if outputs.is_empty() {
        println!(
            "{YELLOW}{BOLD}generate-wrangler:{RESET} no wrangler blocks found; nothing to emit"
        );
        return Ok(());
    }

    for (path, content) in outputs {
        std::fs::write(path, content).map_err(|e| format!("writing {}: {e}", path.display()))?;
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-wrangler:{RESET} wrote {} file(s)",
        outputs.len()
    );
    Ok(())
}

fn check_drift(outputs: &[(PathBuf, String)]) -> Result<(), String> {
    let mut drift: Vec<PathBuf> = Vec::new();

    for (path, expected) in outputs {
        match std::fs::read_to_string(path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(path.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(path.clone());
            }
        }
    }

    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-wrangler --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka deploy generate-wrangler` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        return Err("drift".into());
    }

    if outputs.is_empty() {
        println!("{GREEN}{BOLD}generate-wrangler --check passed{RESET} (no wrangler blocks)");
    } else {
        println!("{GREEN}{BOLD}generate-wrangler --check passed{RESET}");
    }
    Ok(())
}

fn export_project(project_file: &Path) -> Result<ProjectExport, String> {
    let output =
        cue_project(&["export"], project_file).map_err(|e| format!("failed to spawn cue: {e}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!(
            "cue export failed for {}: {stderr}",
            project_file.display()
        ));
    }
    serde_json::from_slice::<ProjectExport>(&output.stdout).map_err(|e| {
        format!(
            "could not parse cue export of {}: {e}",
            project_file.display()
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn wrangler_full() -> Wrangler {
        let mut vars = BTreeMap::new();
        // Insert out of order to prove the BTreeMap sorts the output.
        vars.insert("TZ".into(), "America/Los_Angeles".into());
        vars.insert("DRY_RUN".into(), "true".into());
        vars.insert("LAT".into(), "47.625".into());
        Wrangler {
            main: "build/worker/shim.mjs".into(),
            compatibility_date: "2026-05-14".into(),
            build: Some(Build {
                command: "worker-build --release".into(),
            }),
            assets: None,
            cron: Some(vec!["0 2 * * *".into()]),
            vars: Some(vars),
            secrets: Some(vec![
                "PUSHOVER_APP_TOKEN".into(),
                "PUSHOVER_USER_KEY".into(),
            ]),
        }
    }

    fn wrangler_assets() -> Wrangler {
        Wrangler {
            main: "build/worker/shim.mjs".into(),
            compatibility_date: "2026-05-01".into(),
            build: None,
            assets: Some(Assets {
                directory: "./dist".into(),
            }),
            cron: None,
            vars: None,
            secrets: None,
        }
    }

    #[test]
    fn render_all_is_empty_when_no_wranglers() {
        assert!(render_all(&[]).is_empty());
    }

    #[test]
    fn render_carries_the_do_not_edit_header() {
        let out = render_wrangler("pollen-alert", &wrangler_full());
        assert!(out.starts_with("# Generated by shaka. Do not edit by hand.\n"));
    }

    #[test]
    fn render_full_wrangler_emits_every_table_in_order() {
        let out = render_wrangler("pollen-alert", &wrangler_full());
        let expected = "\
# Generated by shaka. Do not edit by hand.
# Run `shaka deploy generate-wrangler` to update; CI fails on drift.
# The source of truth is each project's `wrangler:` block in project.cue.

name = \"pollen-alert\"
main = \"build/worker/shim.mjs\"
compatibility_date = \"2026-05-14\"

[build]
command = \"worker-build --release\"

[triggers]
crons = [\"0 2 * * *\"]

[vars]
DRY_RUN = \"true\"
LAT = \"47.625\"
TZ = \"America/Los_Angeles\"

# Secrets (set out-of-band via `wrangler secret put <NAME>`):
#   PUSHOVER_APP_TOKEN
#   PUSHOVER_USER_KEY
";
        assert_eq!(out, expected);
    }

    #[test]
    fn render_assets_wrangler_omits_build_triggers_vars_secrets() {
        let out = render_wrangler("kolohelios-portfolio", &wrangler_assets());
        let expected = "\
# Generated by shaka. Do not edit by hand.
# Run `shaka deploy generate-wrangler` to update; CI fails on drift.
# The source of truth is each project's `wrangler:` block in project.cue.

name = \"kolohelios-portfolio\"
main = \"build/worker/shim.mjs\"
compatibility_date = \"2026-05-01\"

[assets]
directory = \"./dist\"
";
        assert_eq!(out, expected);
        assert!(!out.contains("[build]"));
        assert!(!out.contains("[triggers]"));
        assert!(!out.contains("[vars]"));
        assert!(!out.contains("Secrets"));
    }

    #[test]
    fn empty_cron_and_vars_lists_emit_no_table() {
        let mut w = wrangler_assets();
        w.cron = Some(vec![]);
        w.vars = Some(BTreeMap::new());
        let out = render_wrangler("x", &w);
        assert!(!out.contains("[triggers]"));
        assert!(!out.contains("[vars]"));
    }

    #[test]
    fn toml_str_escapes_quotes_and_backslashes() {
        assert_eq!(toml_str(r#"a"b\c"#), r#""a\"b\\c""#);
        assert_eq!(toml_str("tab\there"), r#""tab\there""#);
    }
}
