//! Generator for `infra/cloudflare-deploy/terraform/generated/*.tf`.
//!
//! Walks every project, reads any `deploy:` block from its
//! `project.cue`, and emits one `_zones.tf` (aggregating data sources
//! for each unique zone referenced) plus one `<project>.tf` per app
//! with a deploy block. Files carry a "do not edit by hand" header so
//! the source of truth — the `project.cue` deploy block — is the only
//! input a maintainer ever changes.
//!
//! `--check` mode compares the on-disk contents against what would be
//! written, including detecting orphaned generated files; it exits
//! non-zero on any drift. Wired into `shaka preflight` so committed TF
//! and committed CUE cannot drift apart.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

use crate::project::schema_check::{discover, write_schema as project_schema_path};
use crate::term::{BOLD, DIM, GREEN, RED, RESET, YELLOW};

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka deploy generate-tf` to update; CI fails on drift.\n# The source of truth is each project's `deploy:` block in project.cue.\n\n";

const OUTPUT_DIR: &str = "infra/cloudflare-deploy/terraform/generated";

/// Subset of a project's CUE export — just what the generator needs.
/// `deploy` is optional; projects without one are skipped silently.
#[derive(Deserialize)]
struct ProjectExport {
    name: String,
    #[serde(default)]
    deploy: Option<Deploy>,
}

/// Schema-side `#Deploy`. The `target` discriminator is closed by the
/// schema, so any value reaching this struct has already been validated
/// against the supported set.
#[derive(Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "target", rename_all = "kebab-case")]
enum Deploy {
    CloudflareWorker {
        #[serde(rename = "customDomain")]
        custom_domain: String,
        zone: String,
    },
}

pub fn run(check: bool) {
    let root = Path::new(".");
    match run_at(root, check) {
        Ok(()) => {}
        Err(e) => {
            eprintln!("{RED}{BOLD}error:{RESET} {e}");
            std::process::exit(1);
        }
    }
}

fn run_at(root: &Path, check: bool) -> Result<(), String> {
    let schema_path =
        project_schema_path().map_err(|e| format!("could not resolve schema: {e}"))?;
    let deploys = collect_deploys(root, &schema_path)?;
    let outputs = render_all(&deploys);

    if check {
        check_drift(root, &outputs)
    } else {
        write_all(root, &outputs)
    }
}

/// Walk every project, read its CUE export, and return only those
/// projects that declare a `deploy:` block, sorted by project name.
fn collect_deploys(root: &Path, schema_path: &Path) -> Result<Vec<(String, Deploy)>, String> {
    let mut out = Vec::new();
    for project_dir in discover(root) {
        let project_file = project_dir.join("project.cue");
        if !project_file.exists() {
            continue;
        }
        let export = export_project(schema_path, &project_file)?;
        if let Some(deploy) = export.deploy {
            out.push((export.name, deploy));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

/// (relative path, content) pairs. Always includes `variables.tf` plus
/// `_zones.tf` when any deploy exists; one `<project>.tf` per app with
/// a deploy block. `variables.tf` declares the parent variables the
/// generated resources read (passed through by the `module "generated"`
/// block in the consuming project's `main.tf`).
fn render_all(deploys: &[(String, Deploy)]) -> Vec<(PathBuf, String)> {
    let mut out = Vec::new();
    if deploys.is_empty() {
        return out;
    }

    out.push((PathBuf::from("variables.tf"), render_variables()));
    out.push((PathBuf::from("_zones.tf"), render_zones(deploys)));
    for (name, deploy) in deploys {
        out.push((
            PathBuf::from(format!("{name}.tf")),
            render_project(name, deploy),
        ));
    }
    out
}

fn render_variables() -> String {
    let mut body = String::from(HEADER);
    body.push_str(
        "variable \"cloudflare_account_id\" {\n\
         \x20\x20description = \"Cloudflare account ID; passed through from the parent module.\"\n\
         \x20\x20type        = string\n\
         }\n",
    );
    body
}

fn render_zones(deploys: &[(String, Deploy)]) -> String {
    let mut zones: BTreeMap<String, String> = BTreeMap::new();
    for (_, deploy) in deploys {
        match deploy {
            Deploy::CloudflareWorker { zone, .. } => {
                zones.insert(tf_ident(zone), zone.clone());
            }
        }
    }
    let mut body = String::from(HEADER);
    for (ident, name) in &zones {
        body.push_str(&format!(
            "data \"cloudflare_zone\" \"{ident}\" {{\n  filter = {{\n    name = \"{name}\"\n  }}\n}}\n\n"
        ));
    }
    body.trim_end().to_string() + "\n"
}

fn render_project(name: &str, deploy: &Deploy) -> String {
    let mut body = String::from(HEADER);
    match deploy {
        Deploy::CloudflareWorker {
            custom_domain,
            zone,
        } => {
            let resource_ident = tf_ident(name);
            let zone_ident = tf_ident(zone);
            body.push_str(&format!(
                "resource \"cloudflare_workers_custom_domain\" \"{resource_ident}\" {{\n\
                 \x20\x20account_id = var.cloudflare_account_id\n\
                 \x20\x20zone_id    = data.cloudflare_zone.{zone_ident}.zone_id\n\
                 \x20\x20hostname   = \"{custom_domain}\"\n\
                 \x20\x20service    = \"{name}\"\n\
                 }}\n"
            ));
        }
    }
    body
}

/// Map a domain or project name to a Terraform-safe identifier.
/// Dots and hyphens both become underscores.
fn tf_ident(s: &str) -> String {
    s.replace(['.', '-'], "_")
}

fn write_all(root: &Path, outputs: &[(PathBuf, String)]) -> Result<(), String> {
    let dir = root.join(OUTPUT_DIR);
    std::fs::create_dir_all(&dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;

    let expected: std::collections::HashSet<_> = outputs.iter().map(|(p, _)| p.clone()).collect();
    remove_orphans(&dir, &expected)?;

    if outputs.is_empty() {
        println!("{YELLOW}{BOLD}generate-tf:{RESET} no deploy blocks found; nothing to emit");
        return Ok(());
    }

    for (rel, content) in outputs {
        let path = dir.join(rel);
        std::fs::write(&path, content).map_err(|e| format!("writing {}: {e}", path.display()))?;
        println!("  {GREEN}{BOLD}wrote{RESET}    {}", path.display());
    }
    println!(
        "\n{GREEN}{BOLD}generate-tf:{RESET} wrote {} file(s) under {}",
        outputs.len(),
        dir.display()
    );
    Ok(())
}

fn check_drift(root: &Path, outputs: &[(PathBuf, String)]) -> Result<(), String> {
    let dir = root.join(OUTPUT_DIR);
    let mut drift: Vec<PathBuf> = Vec::new();

    let expected: std::collections::HashSet<_> = outputs.iter().map(|(p, _)| p.clone()).collect();
    if dir.is_dir() {
        for entry in std::fs::read_dir(&dir)
            .map_err(|e| format!("reading {}: {e}", dir.display()))?
            .flatten()
        {
            let path = entry.path();
            let Some(name) = path.file_name() else {
                continue;
            };
            if name == ".gitkeep" {
                continue;
            }
            let rel = PathBuf::from(name);
            if !expected.contains(&rel) {
                println!("  {RED}{BOLD}ORPHAN{RESET}  {}", path.display());
                drift.push(rel);
            }
        }
    }

    for (rel, expected) in outputs {
        let path = dir.join(rel);
        match std::fs::read_to_string(&path) {
            Ok(actual) if actual == *expected => {
                println!("  {GREEN}{BOLD}ok{RESET}       {}", path.display());
            }
            Ok(_) => {
                println!("  {RED}{BOLD}DRIFT{RESET}    {}", path.display());
                drift.push(rel.clone());
            }
            Err(_) => {
                println!("  {RED}{BOLD}MISSING{RESET}  {}", path.display());
                drift.push(rel.clone());
            }
        }
    }

    println!();
    if !drift.is_empty() {
        eprintln!(
            "{RED}{BOLD}generate-tf --check failed{RESET}: {} file(s) drifted",
            drift.len()
        );
        eprintln!("{YELLOW}Run `shaka deploy generate-tf` and commit the result.{RESET}");
        eprintln!(
            "{DIM}drifted: {}{RESET}",
            drift
                .iter()
                .map(|p| p.display().to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
        return Err("drift".into());
    }
    println!("{GREEN}{BOLD}generate-tf --check passed{RESET}");
    Ok(())
}

fn remove_orphans(dir: &Path, expected: &std::collections::HashSet<PathBuf>) -> Result<(), String> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir)
        .map_err(|e| format!("reading {}: {e}", dir.display()))?
        .flatten()
    {
        let path = entry.path();
        let Some(name) = path.file_name() else {
            continue;
        };
        if name == ".gitkeep" {
            continue;
        }
        let rel = PathBuf::from(name);
        if !expected.contains(&rel) {
            std::fs::remove_file(&path)
                .map_err(|e| format!("removing orphan {}: {e}", path.display()))?;
            println!(
                "  {YELLOW}{BOLD}removed{RESET}  {} (orphan)",
                path.display()
            );
        }
    }
    Ok(())
}

fn export_project(schema_path: &Path, project_file: &Path) -> Result<ProjectExport, String> {
    let output = Command::new("cue")
        .arg("export")
        .arg(schema_path)
        .arg(project_file)
        .output()
        .map_err(|e| format!("failed to spawn cue: {e}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
        return Err(format!(
            "cue export failed for {}: {stderr}",
            project_file.display()
        ));
    }
    serde_json::from_slice::<ProjectExport>(&output.stdout).map_err(|e| {
        format!(
            "could not parse cue export of {}: {e}",
            project_file.display()
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tf_ident_replaces_dots_and_hyphens() {
        assert_eq!(tf_ident("kolohelios.com"), "kolohelios_com");
        assert_eq!(tf_ident("kolohelios-portfolio"), "kolohelios_portfolio");
        assert_eq!(tf_ident("a.b-c.d"), "a_b_c_d");
    }

    #[test]
    fn render_all_is_empty_when_no_deploys() {
        assert!(render_all(&[]).is_empty());
    }

    #[test]
    fn render_all_emits_variables_zones_plus_one_file_per_project() {
        let deploys = vec![(
            "kolohelios-portfolio".into(),
            Deploy::CloudflareWorker {
                custom_domain: "kolohelios.com".into(),
                zone: "kolohelios.com".into(),
            },
        )];
        let out = render_all(&deploys);
        let names: Vec<_> = out.iter().map(|(p, _)| p.display().to_string()).collect();
        assert_eq!(
            names,
            vec!["variables.tf", "_zones.tf", "kolohelios-portfolio.tf"]
        );
    }

    #[test]
    fn render_zones_dedups_by_zone_name() {
        let deploys = vec![
            (
                "app-a".into(),
                Deploy::CloudflareWorker {
                    custom_domain: "a.example.com".into(),
                    zone: "example.com".into(),
                },
            ),
            (
                "app-b".into(),
                Deploy::CloudflareWorker {
                    custom_domain: "b.example.com".into(),
                    zone: "example.com".into(),
                },
            ),
        ];
        let zones = render_zones(&deploys);
        assert_eq!(zones.matches("data \"cloudflare_zone\"").count(), 1);
    }

    #[test]
    fn render_zones_one_per_unique_zone() {
        let deploys = vec![
            (
                "app-a".into(),
                Deploy::CloudflareWorker {
                    custom_domain: "a.example.com".into(),
                    zone: "example.com".into(),
                },
            ),
            (
                "app-b".into(),
                Deploy::CloudflareWorker {
                    custom_domain: "kolohelios.com".into(),
                    zone: "kolohelios.com".into(),
                },
            ),
        ];
        let zones = render_zones(&deploys);
        assert_eq!(zones.matches("data \"cloudflare_zone\"").count(), 2);
    }
}
