# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.

resource "linode_volume" "persist" {
  label     = "devbox-persist"
  linode_id = linode_instance.devbox.id
  region    = var.region
  size      = var.volume_size
  lifecycle {
    prevent_destroy = true
  }
}
