terraform {
  required_version = ">= 1.0"

  required_providers {
    betteruptime = {
      source  = "BetterStackHQ/better-uptime"
      version = "~> 0.9"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# BETTERUPTIME_API_TOKEN is read from the environment automatically.
# Source it via 1Password: see README.md.
provider "betteruptime" {}

# ── HTTP(S) reachability ───────────────────────────────────────
# `status` checks for a 2XX from the apex over HTTPS — the
# outside-in counterpart to `shaka domain check`'s config-drift
# detection. Email alert on incident; check interval matches the
# Better Stack free-tier default (see var.check_frequency).
resource "betteruptime_monitor" "apex_http" {
  monitor_type    = "status"
  url             = var.apex_url
  check_frequency = var.check_frequency
  email           = true
}

# ── DNS resolution ─────────────────────────────────────────────
# Separate from the HTTP check so NS/zone drift surfaces from a
# different angle: a `dns` monitor asks the resolver in `url` to
# resolve the domain in `request_body`. If the zone or NS
# delegation breaks, this fires even when a cached HTTP edge might
# still answer.
resource "betteruptime_monitor" "apex_dns" {
  monitor_type    = "dns"
  url             = var.dns_resolver
  request_body    = var.apex_domain
  check_frequency = var.check_frequency
  email           = true
}
