# Generated by `shaka object-store tfstate emit`. Do not edit by hand.
# Re-run emit to regenerate. The bucket and key derive from this
# module's project.cue declaration.

terraform {
  backend "s3" {
    bucket = "kolohelios"
    key    = "tfstate/devbox/terraform.tfstate"
    region = "us-sea-1"

    endpoints = {
      s3 = "https://us-sea-1.linodeobjects.com"
    }

    skip_credentials_validation = true
    skip_region_validation      = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
    use_path_style              = true
  }
}
