# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.

terraform {
  required_version = ">= 1.0"
  required_providers {
    linode = { source = "linode/linode", version = "~> 2.0", }
  }
}
provider "linode" {
  token = var.linode_token
}
variable "linode_token" {
  description = "Linode API personal access token"
  type        = string
  sensitive   = true
}
variable "region" {
  description = "Linode region"
  type        = string
  default     = "us-ord"
}
variable "instance_type" {
  description = "Linode instance plan"
  type        = string
  default     = "g6-standard-2"
}
variable "image_id" {
  description = "Linode image ID (from uploaded NixOS image, e.g. private/12345678)"
  type        = string
}
variable "authorized_keys" {
  description = "SSH public keys to inject into the instance"
  type        = list(string)
  default     = []
}
variable "volume_size" {
  description = "Size of the persistent block storage volume in GB"
  type        = number
  default     = 20
}
variable "root_pass" {
  description = "Root password for the Linode instance (required by API, but SSH key auth is used)"
  type        = string
  sensitive   = true
}
resource "linode_instance" "devbox" {
  authorized_keys = var.authorized_keys
  booted          = true
  image           = var.image_id
  label           = "devbox"
  region          = var.region
  root_pass       = var.root_pass
  tags            = ["devbox", "nixos"]
  type            = var.instance_type
}
resource "linode_volume" "persist" {
  label     = "devbox-persist"
  linode_id = linode_instance.devbox.id
  region    = var.region
  size      = var.volume_size
  lifecycle {
    prevent_destroy = true
  }
}
output "devbox_ip" {
  description = "Public IPv4 address of the devbox"
  value       = linode_instance.devbox.ipv4
}
output "devbox_id" {
  description = "Linode instance ID"
  value       = linode_instance.devbox.id
}
output "volume_filesystem_path" {
  description = "Device path of the attached block storage volume"
  value       = linode_volume.persist.filesystem_path
}
