# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.

terraform {
  required_version = ">= 1.0"
  required_providers {
    linode = { source = "linode/linode", version = "~> 2.0", }
  }
}
provider "linode" {
  token = var.linode_token
}
variable "linode_token" {
  description = "Linode API personal access token"
  type        = string
  sensitive   = true
}
variable "region" {
  description = "Linode region"
  type        = string
  default     = "us-ord"
}
variable "authorized_keys" {
  description = "SSH public keys to inject into the instance"
  type        = list(string)
  default     = []
}
resource "linode_instance" "devbox" {
  authorized_keys = var.authorized_keys
  booted          = true
  label           = "devbox"
  region          = var.region
  tags            = ["devbox", "nixos"]
}
output "instance_id" {
  value = linode_instance.devbox.id
}
