terraform {
  required_version = ">= 1.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# CLOUDFLARE_API_TOKEN is read from the environment automatically. The
# token used here is the Pages-management token provisioned by
# `infra/cloudflare-tokens` and resolved from 1Password — see README.md.
provider "cloudflare" {}

# ── kolohelios-portfolio ───────────────────────────────────────────────
#
# Direct Upload Pages project — content is pushed via `wrangler pages
# deploy site --project-name=kolohelios-portfolio`. No git integration:
# this slice is one HTML file living in `site/`, deployed manually as a
# placeholder until slice #3 (#189) replaces the static origin with the
# Rust + Axum app. The default subdomain
# `kolohelios-portfolio.pages.dev` is the CNAME target the apex record
# in `infra/cloudflare-dns` points at; both must stay in sync.
#
# `production_branch` is required by the resource schema. For
# direct-upload projects it only labels which deployments are
# "production"; the value isn't tied to a real git ref.
resource "cloudflare_pages_project" "kolohelios_portfolio" {
  account_id        = var.cloudflare_account_id
  name              = "kolohelios-portfolio"
  production_branch = "main"
}
