# Hand-written substrate — NOT generated by shaka (no "generated" header, lives
# at the root module, not in generated/, so `shaka deploy generate-tf --check`
# leaves it alone).
#
# Interim provisioning of the external buzzingo repo's D1 user store
# (kolohelios/buzzingo#78). `shaka deploy generate-tf` (#951/#957) can emit this
# resource from a `deploy.d1` block, but only for projects in *this* tree;
# buzzingo is a separate repo with no project.cue here, and cross-repo deploy
# registration isn't built yet. Until it is (see #970 "Out of scope"), the
# resource is hand-authored here. The shape matches the generator's output so the
# migration to the generated path is a no-op rename.
#
# After `tofu apply`, read the id and paste it into buzzingo's wrangler.toml
# `[[d1_databases]].database_id` (a buzzingo-side PR re-adds the held-out
# binding, buzzingo#208/#209):
#
#   tofu -chdir=terraform output -raw buzzingo_d1_database_id

resource "cloudflare_d1_database" "buzzingo_d1" {
  account_id = var.cloudflare_account_id
  name       = "buzzingo-users"
}

output "buzzingo_d1_database_id" {
  description = "D1 database id for buzzingo's `DB` binding; paste into buzzingo's wrangler.toml [[d1_databases]] database_id."
  value       = cloudflare_d1_database.buzzingo_d1.id
}
