terraform {
  required_version = ">= 1.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# CLOUDFLARE_API_TOKEN is read from the environment automatically.
# Source it via 1Password: see README.md.
provider "cloudflare" {}

# Resources, data sources, and outputs live under `generated/` —
# emitted by `shaka deploy generate-tf` from each consuming project's
# `deploy:` block. `_zones.tf` aggregates zone data sources;
# `<project>.tf` holds per-app attachments; `variables.tf` declares the
# parent variables the resources read. OpenTofu only auto-loads `.tf`
# files in the directory it's invoked from, so the subdirectory is
# pulled in as a module here. Providers auto-inherit from this root.
module "generated" {
  source = "./generated"

  cloudflare_account_id = var.cloudflare_account_id
}
