# Generated by shaka. Do not edit by hand.
# Run `shaka deploy generate-tf` to update; CI fails on drift.
# The source of truth is each project's `deploy:` block in project.cue.

data "cloudflare_zone" "kolohelios_com" {
  filter = { name = "kolohelios.com", }
}
