# Generated by shaka. Do not edit by hand.
# Run `shaka deploy generate-tf` to update; CI fails on drift.
# The source of truth is each project's `deploy:` block in project.cue.

resource "cloudflare_workers_custom_domain" "store_web" {
  account_id = var.cloudflare_account_id
  zone_id    = data.cloudflare_zone.kolohelios_com.zone_id
  hostname   = "store.kolohelios.com"
  service    = "store-web"
}
resource "cloudflare_d1_database" "store_web_d1" {
  account_id = var.cloudflare_account_id
  name       = "store-users"
}
output "store_web_d1_database_id" {
  description = "D1 database id for the `DB` binding; paste into the consumer's wrangler.toml [[d1_databases]] database_id."
  value       = cloudflare_d1_database.store_web_d1.id
}
