//! Shared helpers for integration tests that spawn shaka against a
//! temp dir.
//!
//! Not every test binary that `mod common;`-includes this file uses
//! every helper, which trips clippy under `-D warnings`. The
//! `#[allow(dead_code)]` attribute below covers all helpers — any
//! genuine drift (a removed helper still referenced) shows up as a
//! compile error at the call site.

#![allow(dead_code)]
// `tests/common/mod.rs` is the canonical Rust idiom for shared
// integration-test helpers: naming it `mod.rs` keeps Cargo from
// compiling it as its own test binary. The repo-wide
// `clippy::mod_module_files` lint must be silenced here.
#![allow(clippy::mod_module_files)]
//!
//! The project schema imports
//! `kolohelios.com/infra/cloudflare-dns/domains:domain` to constrain
//! hostname fields against the registry. CUE resolves that import by
//! walking up from `cue`'s cwd to find `cue.mod/module.cue`, so any
//! test that runs shaka in a temp dir has to plant a `cue.mod` plus a
//! registry there — otherwise `cue vet` fails with "imports are
//! unavailable." Tests opt into this via [`write_test_module`] (stub
//! registry, accepts any hostname — fine for fixtures that don't use
//! `serving:` / `deploy:`) or [`write_test_module_with_registry`]
//! (concrete zone list — the constraint actually fires).

use std::path::Path;

/// Drop a minimal CUE module + domain registry into `root` so that
/// the project schema's `import "kolohelios.com/...domains:domain"`
/// resolves when `cue` is invoked with `current_dir(root)`.
///
/// The registry stubs `#KnownHostnames: _` so any hostname passes —
/// fine for fixtures that don't exercise the constraint. Tests that
/// *do* exercise it want [`write_test_module_with_registry`] instead.
/// An infra-side stub project is also planted so shaka's `audit` /
/// `schema-check` passes over `tmp/infra/cloudflare-dns/` don't trip
/// on a missing project.cue or audit-rule violations.
pub fn write_test_module(root: &Path) {
    std::fs::create_dir_all(root.join("cue.mod")).unwrap();
    std::fs::write(
        root.join("cue.mod/module.cue"),
        "module: \"kolohelios.com\"\nlanguage: version: \"v0.15.1\"\n",
    )
    .unwrap();

    let registry_dir = root.join("infra/cloudflare-dns/domains");
    std::fs::create_dir_all(&registry_dir).unwrap();
    std::fs::write(
        registry_dir.join("registry.cue"),
        "package domain\n\
        \n\
        // Tests stub the constraint out — fixtures that need a real\n\
        // registry override `registry.cue` after calling write_test_module.\n\
        #KnownHostnames: _\n",
    )
    .unwrap();

    let cf_dns = root.join("infra/cloudflare-dns");
    std::fs::write(
        cf_dns.join("project.cue"),
        "package project\n\
        \n\
        #Project & {\n\
        \tname: \"cloudflare-dns\"\n\
        \tkind: \"infra\"\n\
        }\n",
    )
    .unwrap();
    std::fs::write(cf_dns.join("README.md"), "stub\n").unwrap();
    std::fs::write(cf_dns.join(".gitignore"), "\n").unwrap();
    std::fs::write(
        cf_dns.join("justfile"),
        "# Generated by shaka. Do not edit by hand.\n\
        # Run `shaka project generate-justfiles` to update; CI fails on drift.\n\
        \n\
        validate:\n\
        \techo ok\n",
    )
    .unwrap();
    std::fs::write(
        cf_dns.join("flake.nix"),
        "{\n\
        \tinputs.kolohelios-nix.url = \"https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz\";\n\
        \toutputs = _: {};\n\
        }\n",
    )
    .unwrap();
}

/// Like [`write_test_module`] but the registry actually enumerates
/// `zones` (with the same regex-disjunction shape as the real
/// `aggregate.cue`) so the project schema's hostname constraint
/// fires. Use for tests where a `serving:` / `deploy:` fixture must
/// be accepted (hostname matches the regex) or rejected (doesn't).
pub fn write_test_module_with_registry(root: &Path, zones: &[&str]) {
    write_test_module(root);
    let registry_dir = root.join("infra/cloudflare-dns/domains");
    let mut entries = String::new();
    for z in zones {
        entries.push_str(&format!("domains: \"{z}\": {{}}\n"));
    }
    let content = format!(
        "package domain\n\
        \n\
        import \"strings\"\n\
        \n\
        domains: [string]: {{}}\n\
        \n\
        {entries}\n\
        #KnownHostnames: or([\n\
        \tfor k, _ in domains {{\n\
        \t\t=~\"(^|\\\\.)\\(strings.Replace(k, \".\", \"\\\\.\", -1))$\"\n\
        \t}},\n\
        ])\n"
    );
    std::fs::write(registry_dir.join("registry.cue"), content).unwrap();
}
