//! Shared helpers for integration tests that spawn shaka against a
//! temp dir.
//!
//! The project schema imports
//! `kolohelios.com/infra/cloudflare-dns/domains:domain` to constrain
//! hostname fields against the registry. CUE resolves that import by
//! walking up from `cue`'s cwd to find `cue.mod/module.cue`, so any
//! test that runs shaka in a temp dir has to plant a `cue.mod` plus a
//! registry there — otherwise `cue vet` fails with "imports are
//! unavailable." Tests opt into this via [`write_test_module`].

use std::path::Path;

/// Drop a minimal CUE module + domain registry into `root` so that
/// the project schema's `import "kolohelios.com/...domains:domain"`
/// resolves when `cue` is invoked with `current_dir(root)`.
///
/// Most tests don't reference `#KnownHostnames` (no `serving:` /
/// `deploy:` blocks in their project.cue fixtures), so the registry
/// can stub the definition out — CUE's lazy evaluation keeps the stub
/// from blowing up. An infra-side stub project is also planted so
/// shaka's `audit` / `schema-check` passes over
/// `tmp/infra/cloudflare-dns/` don't trip on a missing project.cue
/// or audit-rule violations.
pub fn write_test_module(root: &Path) {
    std::fs::create_dir_all(root.join("cue.mod")).unwrap();
    std::fs::write(
        root.join("cue.mod/module.cue"),
        "module: \"kolohelios.com\"\nlanguage: version: \"v0.15.1\"\n",
    )
    .unwrap();

    let registry_dir = root.join("infra/cloudflare-dns/domains");
    std::fs::create_dir_all(&registry_dir).unwrap();
    std::fs::write(
        registry_dir.join("registry.cue"),
        "package domain\n\
        \n\
        // Tests stub the constraint out — fixtures that need a real\n\
        // registry override `registry.cue` after calling write_test_module.\n\
        #KnownHostnames: _\n",
    )
    .unwrap();

    let cf_dns = root.join("infra/cloudflare-dns");
    std::fs::write(
        cf_dns.join("project.cue"),
        "package project\n\
        \n\
        #Project & {\n\
        \tname: \"cloudflare-dns\"\n\
        \tkind: \"infra\"\n\
        }\n",
    )
    .unwrap();
    std::fs::write(cf_dns.join("README.md"), "stub\n").unwrap();
    std::fs::write(cf_dns.join(".gitignore"), "\n").unwrap();
    std::fs::write(
        cf_dns.join("justfile"),
        "# Generated by shaka. Do not edit by hand.\n\
        # Run `shaka project generate-justfiles` to update; CI fails on drift.\n\
        \n\
        validate:\n\
        \techo ok\n",
    )
    .unwrap();
    std::fs::write(
        cf_dns.join("flake.nix"),
        "{\n\
        \tinputs.kolohelios-nix.url = \"https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz\";\n\
        \toutputs = _: {};\n\
        }\n",
    )
    .unwrap();
}
