# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.

data "cloudflare_zone" "kolohelios_com" {
  filter = { name = "kolohelios.com", }
}
resource "cloudflare_workers_custom_domain" "kolohelios_portfolio" {
  account_id = var.cloudflare_account_id
  hostname   = "kolohelios.com"
  service    = "kolohelios-portfolio"
  zone_id    = data.cloudflare_zone.kolohelios_com.zone_id
}
