# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.

output "ns_sorted" {
  value = sort(cloudflare_zone.k.name_servers)
}
output "coalesced" {
  value = coalesce(var.label, "")
}
output "first_key" {
  value = var.authorized_keys[0]
}
output "region" {
  value = var.use_primary ? var.primary : var.secondary
}
output "all_ipv4" {
  value = linode_instance.devbox.*.ipv4
}
