# Generated by shaka. Do not edit by hand.
# Run `shaka project generate-flakes` to update; CI fails on drift.
{
  description = "todoist";

  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.stable."1.95.0".minimal.override {
          extensions = [
            "clippy"
            "rustfmt"
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
        };

      rustPlatform =
        pkgs:
        pkgs.makeRustPlatform {
          cargo = rustToolchain pkgs;
          rustc = rustToolchain pkgs;
        };
    in
    {
      devShells = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = pkgs.mkShell {
            packages = [
              (rustToolchain pkgs)
            ]
            ++ (workflowPackages pkgs)
            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;
            shellHook = ''
              if command -v todoist &>/dev/null; then
                _completions_dir="''${XDG_CACHE_HOME:-$HOME/.cache}/kolohelios-completions/todoist"
                mkdir -p "$_completions_dir"
                todoist completions zsh > "$_completions_dir/_todoist" 2>/dev/null
                FPATH="$_completions_dir:$FPATH"
                unset _completions_dir
              fi
            '';
          };
        }
      );

      formatter = kolohelios-nix.formatter;
    };
}
