terraform {
  required_version = ">= 1.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
    onepassword = {
      source  = "1Password/onepassword"
      version = "~> 2.0"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# CLOUDFLARE_API_TOKEN is read from the environment automatically. The
# token used here is the bootstrap meta-token (User:API Tokens:Edit) —
# see README.md.
provider "cloudflare" {}

# OP_SERVICE_ACCOUNT_TOKEN is read from the environment automatically.
# The service account is scoped to the Kolohelios Monorepo vault — see
# README.md.
provider "onepassword" {}

# ── Permission-group lookups ──────────────────────────────────────────
#
# Permission groups are looked up by API name and resolved to opaque CF
# group IDs at plan time — this lets the per-token CUE registry under
# `tokens/` declare permissions in human-readable form without
# hardcoding IDs in TF.
#
# Account ID is passed literally via `var.cloudflare_account_id` rather
# than looked up via `data "cloudflare_accounts"` (which the
# `cloudflare-dns` project uses), because the bootstrap meta-token has
# only `User:API Tokens:Edit` scope and can't list accounts. The
# account ID is stable and not secret.
data "cloudflare_api_token_permission_groups_list" "dns_write" {
  name = "DNS Write"
}

data "cloudflare_api_token_permission_groups_list" "zone_write" {
  name = "Zone Write"
}

data "cloudflare_api_token_permission_groups_list" "account_settings_read" {
  name = "Account Settings Read"
}

data "cloudflare_api_token_permission_groups_list" "pages_write" {
  name = "Pages Write"
}

locals {
  account_id = var.cloudflare_account_id
}

# ── dns-management ────────────────────────────────────────────────────
#
# Mirrors `tokens/dns-management.cue`. CUE → TF sync is manual until
# #292 lands; resource name (`dns_management`) must match the CUE `name`
# field with `-` rewritten to `_`.
resource "cloudflare_api_token" "dns_management" {
  name = "DNS Management (TF-managed)"

  policies = [
    {
      effect = "allow"
      permission_groups = [
        { id = data.cloudflare_api_token_permission_groups_list.dns_write.result[0].id },
        { id = data.cloudflare_api_token_permission_groups_list.zone_write.result[0].id },
      ]
      resources = jsonencode({
        # All current and future zones in the account.
        "com.cloudflare.api.account.zone.*" = "*"
      })
    },
    {
      effect = "allow"
      permission_groups = [
        { id = data.cloudflare_api_token_permission_groups_list.account_settings_read.result[0].id },
      ]
      resources = jsonencode({
        "com.cloudflare.api.account.${local.account_id}" = "*"
      })
    },
  ]

  expires_on = "2026-08-07T00:00:00Z"
}

# 1Password item the consumer references. Category `password` is the
# only first-class option in the TF provider that exposes a `password`
# field — `api_credential` (the dashboard category) is not exposed.
# Reference path: `op://<vault>/Cloudflare DNS Management Token/password`.
resource "onepassword_item" "dns_management" {
  vault    = var.onepassword_vault_id
  title    = "Cloudflare DNS Management Token"
  category = "password"
  password = cloudflare_api_token.dns_management.value
  tags     = ["cloudflare", "tf-managed", "dns"]
}

# ── pages-management ──────────────────────────────────────────────────
#
# Mirrors `tokens/pages-management.cue`. Consumed by
# `infra/cloudflare-portfolio` for both the `tofu apply` that creates
# the Pages project and the `wrangler pages deploy` step that uploads
# `site/`. Account-scoped only — Pages has no zone-level resources.
resource "cloudflare_api_token" "pages_management" {
  name = "Pages Management (TF-managed)"

  policies = [
    {
      effect = "allow"
      permission_groups = [
        { id = data.cloudflare_api_token_permission_groups_list.pages_write.result[0].id },
      ]
      resources = jsonencode({
        "com.cloudflare.api.account.${local.account_id}" = "*"
      })
    },
  ]

  expires_on = "2026-08-07T00:00:00Z"
}

# Reference path: `op://<vault>/Cloudflare Pages Management Token/password`.
resource "onepassword_item" "pages_management" {
  vault    = var.onepassword_vault_id
  title    = "Cloudflare Pages Management Token"
  category = "password"
  password = cloudflare_api_token.pages_management.value
  tags     = ["cloudflare", "tf-managed", "pages"]
}
