terraform {
  required_version = ">= 1.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
    onepassword = {
      source  = "1Password/onepassword"
      version = "~> 2.0"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# CLOUDFLARE_API_TOKEN is read from the environment automatically. The
# token used here is the bootstrap meta-token (User:API Tokens:Edit) —
# see README.md.
provider "cloudflare" {}

# OP_SERVICE_ACCOUNT_TOKEN is read from the environment automatically.
# The service account is scoped to the Kolohelios Monorepo vault — see
# README.md.
provider "onepassword" {}
