terraform {
  required_version = ">= 1.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
    onepassword = {
      source  = "1Password/onepassword"
      version = "~> 2.0"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# CLOUDFLARE_API_TOKEN is read from the environment automatically. The
# token used here is the bootstrap meta-token (User:API Tokens:Edit) —
# see README.md.
provider "cloudflare" {}

# OP_SERVICE_ACCOUNT_TOKEN is read from the environment automatically.
# The service account is scoped to the Kolohelios Monorepo vault — see
# README.md.
provider "onepassword" {}

# ── Permission-group lookups ──────────────────────────────────────────
#
# Permission groups are looked up by API name and resolved to opaque CF
# group IDs at plan time — this lets the per-token CUE registry under
# `tokens/` declare permissions in human-readable form without
# hardcoding IDs in TF.
#
# Account ID is passed literally via `var.cloudflare_account_id` rather
# than looked up via `data "cloudflare_accounts"` (which the
# `cloudflare-dns` project uses), because the bootstrap meta-token has
# only `User:API Tokens:Edit` scope and can't list accounts. The
# account ID is stable and not secret.
data "cloudflare_api_token_permission_groups_list" "dns_write" {
  name = "DNS Write"
}

data "cloudflare_api_token_permission_groups_list" "zone_write" {
  name = "Zone Write"
}

data "cloudflare_api_token_permission_groups_list" "account_settings_read" {
  name = "Account Settings Read"
}

data "cloudflare_api_token_permission_groups_list" "workers_scripts_write" {
  name = "Workers Scripts Write"
}

data "cloudflare_api_token_permission_groups_list" "cache_settings_write" {
  name = "Cache Settings Write"
}

locals {
  account_id = var.cloudflare_account_id
}

# ── dns-management ────────────────────────────────────────────────────
#
# Mirrors `tokens/dns-management.cue`. CUE → TF sync is manual until
# #292 lands; resource name (`dns_management`) must match the CUE `name`
# field with `-` rewritten to `_`.
resource "cloudflare_api_token" "dns_management" {
  name = "DNS Management (TF-managed)"

  policies = [
    {
      effect = "allow"
      permission_groups = [
        { id = data.cloudflare_api_token_permission_groups_list.dns_write.result[0].id },
        { id = data.cloudflare_api_token_permission_groups_list.zone_write.result[0].id },
      ]
      resources = jsonencode({
        # All current and future zones in the account.
        "com.cloudflare.api.account.zone.*" = "*"
      })
    },
    {
      effect = "allow"
      permission_groups = [
        { id = data.cloudflare_api_token_permission_groups_list.account_settings_read.result[0].id },
      ]
      resources = jsonencode({
        "com.cloudflare.api.account.${local.account_id}" = "*"
      })
    },
  ]

  expires_on = "2026-08-07T00:00:00Z"
}

# 1Password item the consumer references. Category `password` is the
# only first-class option in the TF provider that exposes a `password`
# field — `api_credential` (the dashboard category) is not exposed.
# Reference path: `op://<vault>/Cloudflare DNS Management Token/password`.
resource "onepassword_item" "dns_management" {
  vault    = var.onepassword_vault_id
  title    = "Cloudflare DNS Management Token"
  category = "password"
  password = cloudflare_api_token.dns_management.value
  tags     = ["cloudflare", "tf-managed", "dns"]
}

# ── deploy ────────────────────────────────────────────────────────────
#
# Mirrors `tokens/deploy.cue`. Consumed by `infra/cloudflare-deploy`
# (TF custom-domain attach + per-project cache rulesets) and by
# `wrangler deploy` from `rust-worker` apps (code uploads). The three
# flows share one token because all three converge on the same zones;
# if their rotation cadences diverge, split. Zone-scoped DNS comes
# along because `cloudflare_workers_custom_domain` installs a
# CF-managed routing record alongside the attach. Zone-scoped
# Cache Settings gates the `/zones/{id}/rulesets` API used by the
# `http_request_cache_settings` ruleset (covers all cache settings
# on the zone, not just rules — smallest CF-exposed scope).
resource "cloudflare_api_token" "deploy" {
  name = "Deploy (TF-managed)"

  policies = [
    {
      effect = "allow"
      permission_groups = [
        { id = data.cloudflare_api_token_permission_groups_list.workers_scripts_write.result[0].id },
      ]
      resources = jsonencode({
        "com.cloudflare.api.account.${local.account_id}" = "*"
      })
    },
    {
      effect = "allow"
      permission_groups = [
        { id = data.cloudflare_api_token_permission_groups_list.dns_write.result[0].id },
        { id = data.cloudflare_api_token_permission_groups_list.cache_settings_write.result[0].id },
      ]
      resources = jsonencode({
        # All current and future zones in the account.
        "com.cloudflare.api.account.zone.*" = "*"
      })
    },
  ]

  expires_on = "2026-08-11T00:00:00Z"
}

# Reference path: `op://<vault>/Cloudflare Deploy Token/password`.
resource "onepassword_item" "deploy" {
  vault    = var.onepassword_vault_id
  title    = "Cloudflare Deploy Token"
  category = "password"
  password = cloudflare_api_token.deploy.value
  tags     = ["cloudflare", "tf-managed", "deploy"]
}
