//! Every file under `.github/workflows/` must be either generated by
//! `shaka ci generate-workflows` (and byte-identity-checked by the
//! companion `--check`) or in this hand-authored allowlist. Catches
//! the "someone added a workflow that bypasses generation" case the
//! drift check can't see.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::project::schema_check;
use crate::term::{BOLD, DIM, GREEN, RED, RESET};

/// Workflows the generator does not own. Update this list when
/// adding a new repo-event-driven workflow (cron, push:main automation)
/// or a reusable `workflow_call` template; when migrating a previously
/// hand-authored workflow to be generated, remove it from here.
///
/// Entries in this list still get `actionlint`'d via the existing
/// preflight check — same correctness gate as generated files. The
/// distinction is only "who edits the YAML."
const HAND_AUTHORED: &[&str] = &[
    // Reusable workflow_call templates
    "tf-apply.yml",
    "cf-deploy.yml",
    // Repo-event-driven
    "auto-rebase-prs.yaml",
    "bump-kolohelios-nix.yaml",
    "bump-nixpkgs.yaml",
    // Cross-repo: bumps the external buzzingo repo's `shaka` flake input via
    // `bump-locks --repo` (buzzingo has no in-monorepo project.cue to generate
    // from). Schedule + manual-dispatch driven.
    "bump-buzzingo-shaka.yaml",
    "codeql.yml",
    // Repo-wide backstop: deletes any preview Worker whose PR has
    // closed. Runs on `push: main` + a daily cron + manual dispatch
    // (#719). Project-agnostic — not derivable from any single
    // project's `ci:` block, unlike the per-PR `<name>-cleanup.yml`
    // siblings, which `shaka ci generate-workflows` now owns.
    "sweep-preview-workers.yaml",
    // Hand-authored darwin build of infra/home — runs on macos-latest
    // to populate the FlakeHub Cache so cold-bootstrap on a fresh
    // aarch64-darwin host pulls cached artifacts instead of compiling
    // direnv (which OOMs on its fish-test phase). #279. Once the CI
    // generator grows a per-platform `build` field, this migrates to
    // generated and leaves the allowlist.
    "home-build-darwin.yaml",
];

#[derive(Deserialize)]
struct ProjectMeta {
    name: String,
    #[serde(default)]
    ci: Option<Ci>,
}

#[derive(Deserialize)]
struct Ci {
    #[serde(default)]
    apply: Option<serde_json::Value>,
    #[serde(default)]
    build: Option<serde_json::Value>,
    #[serde(default)]
    deploy: Option<serde_json::Value>,
}

pub fn run() {
    match audit() {
        Ok(()) => {}
        Err(unaccounted) => {
            eprintln!(
                "{RED}{BOLD}ci audit-workflows failed{RESET}: {} unaccounted workflow file(s)",
                unaccounted.len()
            );
            for path in &unaccounted {
                eprintln!("  {DIM}- {}{RESET}", path.display());
            }
            eprintln!();
            eprintln!("Each workflow under `.github/workflows/` must be either generated by");
            eprintln!("`shaka ci generate-workflows` (matching a project's `ci:` block), in the");
            eprintln!("built-in allowlist (`tools/shaka/src/ci/audit_workflows.rs`), or listed in");
            eprintln!("`.shaka/repo.cue`'s `handAuthoredWorkflows`.");
            std::process::exit(1);
        }
    }
}

fn audit() -> Result<(), Vec<PathBuf>> {
    let workflows_dir = Path::new(".github/workflows");
    let entries = match std::fs::read_dir(workflows_dir) {
        Ok(e) => e,
        Err(_) => {
            // No workflows dir = nothing to audit. Pass silently.
            println!(
                "{GREEN}{BOLD}ci audit-workflows passed{RESET} (no .github/workflows/ directory)"
            );
            return Ok(());
        }
    };

    let mut files: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .and_then(|x| x.to_str())
                .map(|ext| ext == "yml" || ext == "yaml")
                .unwrap_or(false)
        })
        .collect();
    files.sort();

    let generated = generated_filenames();
    // An external consumer's own hand-authored workflows (e.g. a `just validate`
    // gate) — declared in `.shaka/repo.cue` so they needn't be hardcoded in
    // shaka's source. Tolerant of a missing/unreadable policy: an empty
    // allowlist just means such a file (if any) is reported, never silently
    // passed.
    let repo_allowlist = crate::repo::policy::load(Path::new("."))
        .map(|p| p.hand_authored_workflows)
        .unwrap_or_default();

    let mut unaccounted = Vec::new();
    for path in &files {
        let filename = path
            .file_name()
            .and_then(|n| n.to_str())
            .expect("workflow file has a filename");
        if accounted_for(filename, &generated, &repo_allowlist) {
            continue;
        }
        unaccounted.push(path.clone());
    }

    if unaccounted.is_empty() {
        println!(
            "{GREEN}{BOLD}ci audit-workflows passed{RESET} ({} workflow(s) accounted for)",
            files.len()
        );
        Ok(())
    } else {
        Err(unaccounted)
    }
}

/// A workflow is accounted for if it's emitted by the generator for the current
/// project set, in shaka's built-in [`HAND_AUTHORED`] allowlist, or in the
/// repo's `.shaka/repo.cue` `handAuthoredWorkflows`.
fn accounted_for(filename: &str, generated: &[String], repo_allowlist: &[String]) -> bool {
    HAND_AUTHORED.contains(&filename)
        || generated.iter().any(|g| g == filename)
        || repo_allowlist.iter().any(|w| w == filename)
}

/// Filenames the generator would emit for the current project set.
/// Sourced from each project.cue's `ci:` block; extend as new
/// generated-workflow kinds land (e.g. `ci.deploy` → `<name>-deploy.yml`).
fn generated_filenames() -> Vec<String> {
    if schema_check::project_schema_path().is_err() {
        return Vec::new();
    }
    let mut out = Vec::new();
    let mut any_build = false;
    for project_dir in schema_check::discover(Path::new(".")) {
        if let Ok(meta) = read_meta(&project_dir) {
            if let Some(ci) = meta.ci {
                if ci.apply.is_some() {
                    out.push(format!("{}-apply.yml", meta.name));
                }
                if ci.build.is_some() {
                    any_build = true;
                }
                if ci.deploy.is_some() {
                    // A `ci.deploy` block emits two siblings: the
                    // deploy workflow and the preview-Worker cleanup.
                    out.push(format!("{}-deploy.yml", meta.name));
                    out.push(format!("{}-cleanup.yml", meta.name));
                }
            }
        }
    }
    // `main.yaml` is generated as a single file aggregating every
    // project with `ci.build`. Account for it when any project
    // declares the block.
    if any_build {
        out.push("main.yaml".to_string());
    }
    out
}

fn read_meta(project_dir: &Path) -> Result<ProjectMeta, ()> {
    let project_file = project_dir.join("project.cue");
    if !project_file.exists() {
        return Err(());
    }
    let output = schema_check::cue_project(&["export"], &project_file).map_err(|_| ())?;
    if !output.status.success() {
        return Err(());
    }
    serde_json::from_slice::<ProjectMeta>(&output.stdout).map_err(|_| ())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accounts_for_builtin_generated_and_repo_allowlist() {
        let generated = vec!["foo-deploy.yml".to_string()];
        let repo = vec!["buzzingo-validate.yml".to_string()];
        assert!(accounted_for("cf-deploy.yml", &generated, &repo)); // built-in const
        assert!(accounted_for("foo-deploy.yml", &generated, &repo)); // generated
        assert!(accounted_for("buzzingo-validate.yml", &generated, &repo)); // per-repo
        assert!(!accounted_for("stray.yml", &generated, &repo)); // none of the above
    }

    #[test]
    fn empty_repo_allowlist_still_honors_builtin() {
        assert!(accounted_for("cf-deploy.yml", &[], &[]));
        assert!(!accounted_for("buzzingo-validate.yml", &[], &[]));
    }
}
