//! Every file under `.github/workflows/` must be either generated by
//! `shaka ci generate-workflows` (and byte-identity-checked by the
//! companion `--check`) or in this hand-authored allowlist. Catches
//! the "someone added a workflow that bypasses generation" case the
//! drift check can't see.

use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Deserialize;

use crate::project::schema_check;
use crate::term::{BOLD, DIM, GREEN, RED, RESET};

/// Workflows the generator does not own. Update this list when
/// adding a new repo-event-driven workflow (cron, push:main automation)
/// or a reusable `workflow_call` template; when migrating a previously
/// hand-authored workflow to be generated, remove it from here.
///
/// Entries in this list still get `actionlint`'d via the existing
/// preflight check — same correctness gate as generated files. The
/// distinction is only "who edits the YAML."
const HAND_AUTHORED: &[&str] = &[
    // Reusable workflow_call templates
    "tf-apply.yml",
    "cf-deploy.yml",
    // Hand-authored sibling of the generated
    // `kolohelios-portfolio-deploy.yml`: runs on `pull_request: closed`
    // to delete the ephemeral preview Worker. Different trigger and
    // project-specific wrangler invocation; not derivable from
    // `ci.deploy` metadata.
    "kolohelios-portfolio-cleanup.yml",
    // Repo-event-driven
    "auto-rebase-prs.yaml",
    "bump-kolohelios-nix.yaml",
    "codeql.yml",
    // Hand-authored darwin build of infra/home — runs on macos-latest
    // to populate the FlakeHub Cache so cold-bootstrap on a fresh
    // aarch64-darwin host pulls cached artifacts instead of compiling
    // direnv (which OOMs on its fish-test phase). #279. Once the CI
    // generator grows a per-platform `build` field, this migrates to
    // generated and leaves the allowlist.
    "home-build-darwin.yaml",
];

#[derive(Deserialize)]
struct ProjectMeta {
    name: String,
    #[serde(default)]
    ci: Option<Ci>,
}

#[derive(Deserialize)]
struct Ci {
    #[serde(default)]
    apply: Option<serde_json::Value>,
    #[serde(default)]
    build: Option<serde_json::Value>,
    #[serde(default)]
    deploy: Option<serde_json::Value>,
}

pub fn run() {
    match audit() {
        Ok(()) => {}
        Err(unaccounted) => {
            eprintln!(
                "{RED}{BOLD}ci audit-workflows failed{RESET}: {} unaccounted workflow file(s)",
                unaccounted.len()
            );
            for path in &unaccounted {
                eprintln!("  {DIM}- {}{RESET}", path.display());
            }
            eprintln!();
            eprintln!("Each workflow under `.github/workflows/` must be either generated by");
            eprintln!("`shaka ci generate-workflows` (matching a project's `ci:` block) or in the");
            eprintln!("hand-authored allowlist in `tools/shaka/src/ci/audit_workflows.rs`.");
            std::process::exit(1);
        }
    }
}

fn audit() -> Result<(), Vec<PathBuf>> {
    let workflows_dir = Path::new(".github/workflows");
    let entries = match std::fs::read_dir(workflows_dir) {
        Ok(e) => e,
        Err(_) => {
            // No workflows dir = nothing to audit. Pass silently.
            println!(
                "{GREEN}{BOLD}ci audit-workflows passed{RESET} (no .github/workflows/ directory)"
            );
            return Ok(());
        }
    };

    let mut files: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .and_then(|x| x.to_str())
                .map(|ext| ext == "yml" || ext == "yaml")
                .unwrap_or(false)
        })
        .collect();
    files.sort();

    let generated = generated_filenames();

    let mut unaccounted = Vec::new();
    for path in &files {
        let filename = path
            .file_name()
            .and_then(|n| n.to_str())
            .expect("workflow file has a filename");
        if HAND_AUTHORED.contains(&filename) || generated.iter().any(|g| g == filename) {
            continue;
        }
        unaccounted.push(path.clone());
    }

    if unaccounted.is_empty() {
        println!(
            "{GREEN}{BOLD}ci audit-workflows passed{RESET} ({} workflow(s) accounted for)",
            files.len()
        );
        Ok(())
    } else {
        Err(unaccounted)
    }
}

/// Filenames the generator would emit for the current project set.
/// Sourced from each project.cue's `ci:` block; extend as new
/// generated-workflow kinds land (e.g. `ci.deploy` → `<name>-deploy.yml`).
fn generated_filenames() -> Vec<String> {
    let schema_path = match schema_check::write_schema() {
        Ok(p) => p,
        Err(_) => return Vec::new(),
    };
    let mut out = Vec::new();
    let mut any_build = false;
    for project_dir in schema_check::discover(Path::new(".")) {
        if let Ok(meta) = read_meta(&schema_path, &project_dir) {
            if let Some(ci) = meta.ci {
                if ci.apply.is_some() {
                    out.push(format!("{}-apply.yml", meta.name));
                }
                if ci.build.is_some() {
                    any_build = true;
                }
                if ci.deploy.is_some() {
                    out.push(format!("{}-deploy.yml", meta.name));
                }
            }
        }
    }
    // `main.yaml` is generated as a single file aggregating every
    // project with `ci.build`. Account for it when any project
    // declares the block.
    if any_build {
        out.push("main.yaml".to_string());
    }
    out
}

fn read_meta(schema_path: &Path, project_dir: &Path) -> Result<ProjectMeta, ()> {
    let project_file = project_dir.join("project.cue");
    if !project_file.exists() {
        return Err(());
    }
    let output = Command::new("cue")
        .arg("export")
        .arg(schema_path)
        .arg(&project_file)
        .output()
        .map_err(|_| ())?;
    if !output.status.success() {
        return Err(());
    }
    serde_json::from_slice::<ProjectMeta>(&output.stdout).map_err(|_| ())
}
