use std::collections::BTreeMap;

use serde::Serialize;

#[derive(Serialize, Debug)]
pub struct Workflow {
    pub name: String,
    pub on: On,
    pub permissions: Permissions,
    pub concurrency: Concurrency,
    pub jobs: BTreeMap<String, Job>,
}

#[derive(Serialize, Debug)]
pub struct On {
    pub push: PushTrigger,
    pub workflow_dispatch: Empty,
}

#[derive(Serialize, Debug)]
pub struct PushTrigger {
    pub branches: Vec<String>,
    pub paths: Vec<String>,
}

#[derive(Debug)]
pub struct Empty;

impl Serialize for Empty {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_none()
    }
}

#[derive(Serialize, Debug)]
pub struct Permissions {
    #[serde(rename = "id-token", skip_serializing_if = "Option::is_none")]
    pub id_token: Option<PermissionLevel>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contents: Option<PermissionLevel>,
}

#[derive(Serialize, Debug, Clone, Copy)]
#[serde(rename_all = "lowercase")]
pub enum PermissionLevel {
    Read,
    Write,
}

#[derive(Serialize, Debug)]
pub struct Concurrency {
    pub group: String,
    #[serde(rename = "cancel-in-progress")]
    pub cancel_in_progress: bool,
}

#[derive(Serialize, Debug)]
#[serde(untagged)]
pub enum Job {
    ReusableCall(ReusableCall),
}

#[derive(Serialize, Debug)]
pub struct ReusableCall {
    pub uses: String,
    pub with: BTreeMap<String, String>,
    pub secrets: BTreeMap<String, String>,
}

const HEADER: &str = "# Generated by shaka. Do not edit by hand.\n# Run `shaka ci generate-workflows` to refresh.\n#\n# Source of truth: <slot>/<project>/project.cue.\n\n";

/// Serialize a workflow to YAML with the canonical "do not edit" header.
pub fn emit(workflow: &Workflow) -> String {
    let body = serde_yaml_ng::to_string(workflow).expect("workflow serializes");
    format!("{HEADER}{body}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_apply_workflow(name: &str, project_dir: &str) -> Workflow {
        Workflow {
            name: format!("{name} apply"),
            on: On {
                push: PushTrigger {
                    branches: vec!["main".into()],
                    paths: vec![
                        format!("{project_dir}/**"),
                        format!(".github/workflows/{name}-apply.yml"),
                        ".github/workflows/tf-apply.yml".into(),
                    ],
                },
                workflow_dispatch: Empty,
            },
            permissions: Permissions {
                id_token: Some(PermissionLevel::Write),
                contents: Some(PermissionLevel::Read),
            },
            concurrency: Concurrency {
                group: format!("{name}-apply"),
                cancel_in_progress: false,
            },
            jobs: {
                let mut m = BTreeMap::new();
                m.insert(
                    "apply".to_string(),
                    Job::ReusableCall(ReusableCall {
                        uses: "./.github/workflows/tf-apply.yml".into(),
                        with: {
                            let mut w = BTreeMap::new();
                            w.insert("project_dir".to_string(), project_dir.to_string());
                            w
                        },
                        secrets: {
                            let mut s = BTreeMap::new();
                            s.insert(
                                "OP_SERVICE_ACCOUNT_TOKEN".to_string(),
                                "${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}".to_string(),
                            );
                            s
                        },
                    }),
                );
                m
            },
        }
    }

    #[test]
    fn emit_starts_with_do_not_edit_header() {
        let yaml = emit(&fixture_apply_workflow(
            "cloudflare-dns",
            "infra/cloudflare-dns",
        ));
        assert!(yaml.starts_with("# Generated by shaka. Do not edit by hand.\n"));
    }

    #[test]
    fn emit_round_trips_to_valid_yaml() {
        let yaml = emit(&fixture_apply_workflow(
            "cloudflare-dns",
            "infra/cloudflare-dns",
        ));
        let parsed: serde_yaml_ng::Value = serde_yaml_ng::from_str(&yaml).expect("valid YAML");
        assert_eq!(parsed["name"].as_str(), Some("cloudflare-dns apply"));
        assert_eq!(
            parsed["jobs"]["apply"]["uses"].as_str(),
            Some("./.github/workflows/tf-apply.yml"),
        );
    }

    #[test]
    fn emit_is_deterministic() {
        let a = emit(&fixture_apply_workflow(
            "cloudflare-dns",
            "infra/cloudflare-dns",
        ));
        let b = emit(&fixture_apply_workflow(
            "cloudflare-dns",
            "infra/cloudflare-dns",
        ));
        assert_eq!(a, b);
    }
}
