# Generated by shaka. Do not edit by hand.
# Run `shaka project generate-flakes` to update; CI fails on drift.
{
  description = "shaka — build tooling for kolohelios";

  inputs = {
    kolohelios-nix.url = "https://flakehub.com/f/kolohelios/kolohelios-nix/*.tar.gz";
    nixpkgs.follows = "kolohelios-nix/nixpkgs";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      kolohelios-nix,
      nixpkgs,
      rust-overlay,
      ...
    }:
    let
      inherit (kolohelios-nix.lib) supportedSystems workflowPackages;

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [ rust-overlay.overlays.default ];
            };
          }
        );

      rustToolchain =
        pkgs:
        pkgs.rust-bin.stable."1.95.0".default.override {
          extensions = [
            "rust-src"
            "rust-analyzer"
            "llvm-tools-preview"
          ];
        };

      rustPlatform =
        pkgs:
        pkgs.makeRustPlatform {
          cargo = rustToolchain pkgs;
          rustc = rustToolchain pkgs;
        };
    in
    {
      packages = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = (rustPlatform pkgs).buildRustPackage {
            pname = "shaka";
            version = "0.1.0";
            src = ./.;
            cargoLock.lockFile = ./Cargo.lock;
            nativeCheckInputs = [
              pkgs.cue
              pkgs.jujutsu
              pkgs.git
              pkgs.opentofu
            ];
            nativeBuildInputs = [
              pkgs.makeWrapper
              pkgs.installShellFiles
            ];
            postInstall = ''
              installShellCompletion --cmd shaka \
                --bash <($out/bin/shaka completions bash) \
                --fish <($out/bin/shaka completions fish) \
                --zsh  <($out/bin/shaka completions zsh)
            '';
            postFixup = ''
              wrapProgram $out/bin/shaka \
                --prefix PATH : ${
                  pkgs.lib.makeBinPath [
                    pkgs.jujutsu
                    pkgs.git
                    pkgs.gh
                    pkgs.nix
                    pkgs.cue
                    pkgs.just
                    pkgs.jq
                  ]
                }
            '';
          };
        }
      );

      apps = forEachSupportedSystem (
        { system, ... }:
        {
          default = {
            type = "app";
            program = "${self.packages.${system}.default}/bin/shaka";
          };
        }
      );

      devShells = forEachSupportedSystem (
        { pkgs, ... }:
        {
          default = pkgs.mkShell {
            packages = [
              (rustToolchain pkgs)
              pkgs.actionlint
              pkgs.shellcheck
              pkgs.awscli2
              pkgs.opentofu
              pkgs.taplo
              pkgs.whois
              pkgs.dnsutils
            ]
            ++ (workflowPackages pkgs)
            ++ pkgs.lib.optional pkgs.stdenv.hostPlatform.isLinux pkgs.cargo-llvm-cov;
            shellHook = ''
              if command -v shaka &>/dev/null; then
                _completions_dir="''${XDG_CACHE_HOME:-$HOME/.cache}/kolohelios-completions/shaka"
                mkdir -p "$_completions_dir"
                shaka completions zsh > "$_completions_dir/_shaka" 2>/dev/null
                FPATH="$_completions_dir:$FPATH"
                unset _completions_dir
              fi
            '';
          };
        }
      );

      formatter = kolohelios-nix.formatter;
    };
}
