# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.

resource "linode_instance" "devbox" {
  booted = true
  label  = "devbox"
}
