# Generated by shaka. Do not edit by hand.
# Run `shaka deploy generate-tf` to update; CI fails on drift.
# The source of truth is each project's `deploy:` block in project.cue.

variable "cloudflare_account_id" {
  description = "Cloudflare account ID; passed through from the parent module."
  type        = string
}
