# Generated by shaka. Do not edit by hand.
# Run `shaka deploy generate-tf` to update; CI fails on drift.
# The source of truth is each project's `deploy:` block in project.cue.

resource "cloudflare_workers_custom_domain" "portfolio_a" {
  account_id  = var.cloudflare_account_id
  zone_id     = data.cloudflare_zone.kolohelios_com.zone_id
  hostname    = "a.kolohelios.com"
  service     = "portfolio-a"
  environment = "production"
}
