terraform {
  required_version = ">= 1.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# CLOUDFLARE_API_TOKEN is read from the environment automatically.
# Source it via 1Password: see README.md.
provider "cloudflare" {}

# ── kolohelios.com ─────────────────────────────────────────────
resource "cloudflare_zone" "kolohelios_com" {
  account = {
    id = var.cloudflare_account_id
  }
  name = "kolohelios.com"
  type = "full"
}
