terraform {
  required_version = ">= 1.0"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.0"
    }
  }

  # The remote backend lives in backend.tf (generated by
  # `shaka object-store tfstate emit`).
}

# CLOUDFLARE_API_TOKEN is read from the environment automatically.
# Source it via 1Password: see README.md.
provider "cloudflare" {}

# ── kolohelios.com ─────────────────────────────────────────────
# The apex is owned by the Worker custom-domain attachment in
# infra/cloudflare-deploy (slice #3 of #186); attaching a Worker custom
# domain installs the routing record itself, and a user-owned CNAME at
# the same hostname conflicts. The zone resource stays here because
# zones are infra/cloudflare-dns's concern; per-app records sit with
# the app's deploy block.
resource "cloudflare_zone" "kolohelios_com" {
  account = {
    id = var.cloudflare_account_id
  }
  name = "kolohelios.com"
  type = "full"
}
