# DO NOT EDIT — generated by `shaka terraform emit`.
# Source of truth lives in this module's `cue/` directory.
# Re-running emit reproduces this file deterministically.

terraform {
  required_version = ">= 1.0"
  required_providers {
    cloudflare = { source = "cloudflare/cloudflare", version = "~> 5.0", }
  }
}
provider "cloudflare" {
}
variable "cloudflare_account_id" {
  description = "Cloudflare account ID for the zones managed here. Stable and not secret; visible in the dashboard URL. Passed literally rather than looked up because the consumer-token can't list accounts (matches the pattern in infra/cloudflare-tokens; see #311/#313)."
  type        = string
}
resource "cloudflare_zone" "kolohelios_com" {
  account = { id = var.cloudflare_account_id, }
  name    = "kolohelios.com"
  type    = "full"
}
output "domain_expectations" {
  description = "Per-domain expected NS pair and DNSSEC state, keyed by zone name"
  value = {
    "kolohelios.com" = {
      ns_pair        = sort(cloudflare_zone.kolohelios_com.name_servers)
      dnssec_enabled = false
    }
  }
}
